### ISSUE TITLE
Target variations creation - missing least properties

### ISSUE THREAD

**Issue by Sartor87** [OfficeDev/PnP#1004]
When creating target variations the object has missing properties, including: Label Contact (seems to be stored in the MetaInfo column) and Site Template Language. Without those properties the label timer job does not trigger to create a sub site for the variation label.

Target Environment: SharePoint Online

**Comment by VesaJuvonen** [comment]
thx Sartor87. Sorry for the massive delay on getting any response on this. I'm not quite sure if this referring to some PnP sample or oob behavior. If it's for oob APIs, we can't address those through PnP initiative. If that's for some specific sample, we would need more specific pointer on the target.
