### ISSUE TITLE
People Picker in client side Modal

### ISSUE THREAD

**Issue by krusk** [OfficeDev/PnP#1010]
I can't seem to get the People Picker to work when placed inside a Modal such as Angular UIs Modal. Is this since the People Picker loads on Dom and a Modal is post DOM? What are my options/what am I missing?

**Comment by patrick-rodgers** [comment]
Unsure, you can try the jQuery [sp.peoplepicker.js](https://github.com/OfficeDev/PnP/blob/master/Components/Core.JQuery/sp.peoplepicker.js.md) component, this has been used in Angular projects.
