### ISSUE TITLE
Add-SPONavigation cmdlet cannot add anything to TopNavigation

### ISSUE THREAD

**Issue by PerOve** [OfficeDev/PnP#1011]
I cannot add anything to the Top Navigation anymore.
Quicklaunch works fine.

cmd written in may version of the cmdlet works fine:
Add-SPONavigationNode -Title "TEST" -Location Top

Cmd written in June version:
Add-SPONavigationNode -Title "TEST" -Location TopNavigationBar

Note that Location has changed from top to TopNavigationBar. 
There is also a new choice: SearchNav

**Comment by erwinvanhunen** [comment]
The last time this cmdlet was changed in code was on the 12th of March 2013. However, when I use

Add-SPONavigation_Node -Title "TEST" -Location Top -Url https://www.test.com

The node is added as expected.

The location parameter is using an enumeration that hasn't changed either since several months ago.

**Comment by PerOve** [comment]
Hi.
I also succeed with the same command as you:
Add-SPONavigationNode -Location TopNavigationBar -Title Test -Url https://test

But if I do not use the -Url, it does not work.
Add-SPONavigationNode -Location TopNavigationBar -Title Test

So we can therefore perhaps conclude with the url is a required property, and that the cmdlet will work even if the Location parameter values changes (from Top to TopNavigationBar)

The result I am looking for is to add a heading (Folder) and then multiple links under this heading. 
Perhaps it will be possible to add this as a new feature?

**Comment by mos-easterberg** [comment]
hi, I'd need this too:
1. possibility to create headings
2. possibility to set audiences

currently not available, right?

br, mos
