### ISSUE TITLE
Limit People Picker to 1 Entry

### ISSUE THREAD

**Issue by krusk** [OfficeDev/PnP#1012]
Is there a method to limit the People Picker to 1 entry and not allow other entries after the initial is resolved? Currently, it is allowing users to enter multiple "people" for a field that only accepts one entry. I noticed that in SharePoint, if you add more than 1 person it has a message stating "You can only enter one name." but still allows multiple people instead of restricting to just one entry.

**Comment by jansenbe** [comment]
This capability is currently not implemented...any takers?

**Comment by krusk** [comment]
Thanks for confirmation and all you work on this.

**Comment by patrick-rodgers** [comment]
This is done in [sp.peoplepicker.js](https://github.com/OfficeDev/PnP/blob/master/Components/Core.JQuery/sp.peoplepicker.js.md).
