### ISSUE TITLE
Importing Term Group / Term Set / Term / Label

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP#1013]
Hi Erwin I am having issues importing a Provisioning Template containing a Taxonomy.
This does not work -
![taxonomyworks](https://cloud.githubusercontent.com/assets/8484048/8496020/f3b5099a-2169-11e5-8888-ed6e65c0c23c.JPG)

This does -
  
![taxonomyworks1](https://cloud.githubusercontent.com/assets/8484048/8496072/4f040620-216a-11e5-8f5b-084933288fff.JPG)
                  

ie No Labels

The error I am getting is "Failed to Read from or write to database"

**Comment by NPrice99** [comment]
I have narrowed it down even further and the error occurs when a Label Value is the same as the Term Name.  ie "AO" in the above example.

**Comment by erwinvanhunen** [comment]
Okay, that issue was fixed already in the dev branch. See PR #945

**Comment by NPrice99** [comment]
That's strange I got a copy of Dev a few days ago. I am using the PowerShell Cmdlets.

**Comment by erwinvanhunen** [comment]
What's the language for the site? The same as the default one of the termstore?

**Comment by NPrice99** [comment]
The Locale for the Site is English (United Kingdom)  the default for the termstore is English (Its the onlyone)

**Comment by erwinvanhunen** [comment]
Please double check if the cmdlets are really using the latest core library as that specific issue you mention is fixed. When applying the template with a label marked as default for a language that is the same as the termstore language we skip the label and write a warning to the output.

**Comment by NPrice99** [comment]
will do

**Comment by patrick-rodgers** [comment]
Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.
