### ISSUE TITLE
 Calculated Field creation order

### ISSUE THREAD

**Issue by braegelno5** [OfficeDev/PnP#1014]
Calculated field in list are not able to create by the engine before all referenced columns from the formula are present

**Comment by erwinvanhunen** [comment]
I personally don't think this is an issue but a fact. I mean, the template just has to provide the fields in the correct order.

**Comment by braegelno5** [comment]
normally yes you are right, but that's why i have done this over the sp ui, and saved the template,
so the other way is to do a reorder on template generation to put all calculated fields on the end of list fields. For this we need pr #1015 not.
