### ISSUE TITLE
<pnp:webfeatures /> causes "Invalid Template" error message

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP#1018]
In My Provisioning Template I have
&lt;pnp:features>&gt;
&lt;pnp:SiteFeatures&gt;
.
.
&lt;/pnp:SIteFeatures&gt;
&lt;pnp:WebFeatures /&gt;
&lt;/pnp:features&gt;
I get an error message "Invalid Template" When I run apply-SPOProvisioning Template>

take out &lt;pnp:WebFeatures /&gt; and It all works.

**Comment by NPrice99** [comment]
Its not just WebFeatuires but basically any <pnp:<whatever>

**Comment by Zimmergren** [comment]
I've seen this too. As far as my testing has gone, empty elements isn't always very welcome :-)

**Comment by NPrice99** [comment]
Hi Patrick
What was the fix for this issue ?
Regards
Nigel
