### ISSUE TITLE
TimerJob access denied with ExpandSubSites = true;

### ISSUE THREAD

**Issue by Zimmergren** [OfficeDev/PnP#1023]
While using the TimerJob core framework works for some of my scenarios, sometimes it doesn't. 
Here's an example of when my Global Administrator account gets access denied error. 

Program.cs file where I instantiate my job: 

```
            HealthCheckerJob healthCheckerJob = new HealthCheckerJob();
            
            // Configure Authentication Options
            healthCheckerJob.UseOffice365Authentication(WebConfigurationManager.AppSettings["SPOUsername"], WebConfigurationManager.AppSettings["SPOPassword"]);

            // Configure which sites should be included when running the job
            //healthCheckerJob.AddSite(WebConfigurationManager.AppSettings["RootSiteUrl"]);
            healthCheckerJob.AddSite(WebConfigurationManager.AppSettings["SiteCollectionsUrl"]);

            // Run the job.
            healthCheckerJob.Run();
```

And the job definition itself: 
```
        public HealthCheckerJob() : base("HealthCheckerJob")
        {
            ExpandSubSites = true; 
            UseThreading = true;        // Default
            MaximumThreads = 10;     // Default

            // Hook up the Health Checker Job Run event to the job. 
            TimerJobRun += HealthCheckerJob_TimerJobRun;
        }
```

The problem occurs only when I set ExpandSubSites = true. 
If I remove it or set it to false, I can access the context.Site object inside the job execution and get all subsites that way, without getting access denied. 

Account: Global Administrator
SiteCollectionUrl config setting (as per the code above): https://mytenant.sharepoint.com/sites/*
Status: Timer Job works as expected if I remove ExpandSubSites =true.

I'm using the (currently) latest release of the PnP NuGet.

**Comment by levalencia** [comment]
maybe duplicated?

https://github.com/OfficeDev/PnP/issues/1002

**Comment by Zimmergren** [comment]
@levalencia yes looks like I missed that one. 
Looks like it could be the same issue. Can close here and keep the other one open.
