### ISSUE TITLE
Apply‑SPOProvisioningTemplate: Sitecolumns not connected to termsets (inter tenant)

### ISSUE THREAD

**Issue by SjoerdV** [OfficeDev/PnP#1035]
With an inter-tenant migration:
1)  I used Export-SPOTaxonomy -IncludeID and import the taxonomy with Import-SPOTaxonomy on a different tenant. The termsets are created with the exact same ID's like the source tenant
2) Afterwards I made a Get-SPOProvisioningTemplate to generate the source template and I applied it to the target tenant with Apply-SPOProvisioningTemplate. All Sitecolumns are created except they are not attached to the termsets even though all the ID's match up. (I do have a workaround for the duplicate fieldnames error) while applying the template

**Comment by VesaJuvonen** [comment]
This issue was moved to OfficeDev/PnP-Sites-Core#775
