### ISSUE TITLE
Import-SPOTaxonomy: crash when reused terms are in the importfile

### ISSUE THREAD

**Issue by SjoerdV** [OfficeDev/PnP#1036]
Inter-tenant migration:
1) All terms (including 'reused' terms) are exported with Export-SPOTaxonomy correctly from the source tenant and have (obviously) the same ID as the source term. 
2) The Import-SPOTaxonomy to the target tenant will crash however when it detects a dupicate term ID. 

Feature Request: Would it be possible to have reused terms import successfully to a target tenant?

**Comment by patrick-rodgers** [comment]
I believe this is fixed in latest. If you believe this is still an issue in the latest release please re-open and let us know.
