### ISSUE TITLE
GetADFSUserNameMixedAuthenticatedContext - Null reference exception

### ISSUE THREAD

**Issue by Sartor87** [OfficeDev/PnP#1038]
When trying to authenticate against ADFS site collection, I get null reference exception at getting the authentication cookie.

ADFS version: 2.0
SharePoint Online site collection on a multi-tenant environment

**Comment by braegelno5** [comment]
Have you used fiddler to check if the adfs logon page was called?

**Comment by Sartor87** [comment]
Yes, it does. It goes to the username mixed  endpoint of the ADFS. 

When attempting to authenticate against the http://tenant.sharepoint.com/_trust/ it returns error. This is when the application throws an error for a null reference exception in TransformSamlTokenToFedAuth method in the BaseProvider. The web response does not return any cookies.

**Comment by braegelno5** [comment]
I assume the adfs client is working if you go manually on a computer which is not a member of the domain.
So my suggestion is, that this client is not the newest, there exists an older 64 bit version, we need 64 bit for now on Azure, the old 32 bit works not anymore,  but this older version works not together with the CSOM lib.

**Comment by Sartor87** [comment]
Could you please elaborate on what do you mean on "ADFS client"?

**Comment by braegelno5** [comment]
Adfs client is software installed on customer domain accessable over HTTPS, shows a login window.

**Comment by Sartor87** [comment]
OK, got it - I will check this with the admins. Your info was very valuable!
