### ISSUE TITLE
Apply-SPOProvisioningTemplate not able to set Toolbar type to None

### ISSUE THREAD

**Issue by brannmar** [OfficeDev/PnP#1042]
First of all Hi! I'm new to the community and are therefore not sure if this is the correct place to drop this issue. 

I am trying to remove the toolbar on a view using the provisioning template. But when I am setting the Type to None nothing happens. It is still the same. I have tried to remove it using ordinary csom aswell but without success. Please verify that this is a problem on your end or on my.

```xml
<View Name="{E3B1E061-5F3E-42CA-B179-1D2D481B5D6A}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="All Documents" Url="{site}/Cases/Forms/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/dlicon.png?rev=40">
    <Query>
        <OrderBy>
            <FieldRef Name="FileLeafRef" />
        </OrderBy>
    </Query>
    <ViewFields>
        <FieldRef Name="Case_x0020_number" />
        <FieldRef Name="LinkFilename" />
        <FieldRef Name="Insurance_x0020_agency" />
        <FieldRef Name="Case_x0020_Status" />
        <FieldRef Name="OMR_x0020_Category" />
        <FieldRef Name="Created" />
        <FieldRef Name="Author" />
        <FieldRef Name="Modified" />
        <FieldRef Name="Editor" />
    </ViewFields>
    <RowLimit Paged="TRUE">30</RowLimit>
    <Aggregations Value="Off" />
    <JSLink>clienttemplates.js</JSLink>
    <XslLink Default="TRUE">main.xsl</XslLink>
    <Toolbar Type="None" />
</View>
```
Image of the toolbar i want to remove
![image](https://cloud.githubusercontent.com/assets/7968452/8668497/0522cd02-2a0c-11e5-8655-2566cf270858.png)

**Comment by erwinvanhunen** [comment]
We currently do not support setting the toolbar type through the provisioning engine, e.g. the Toolbar child element as defined in the View element in your example above is ignored. As you noticed yourself, setting it through CSOM seems to have no effect, I noticed that too in a brief test. We can investigate, but it's not an issue with the PnP code and/or engine, but rather with CSOM in general it seems. I will close this issue.
