### ISSUE TITLE
Apply‑SPOProvisioningTemplate: Documentset Welcome Page View not updated

### ISSUE THREAD

**Issue by SjoerdV** [OfficeDev/PnP#1046]
The template (source) site has a Document Set configured with a Welcome Page view set to something other than "All Documents". Apply‑SPOProvisioningTemplate will provision the list, contenttype and custom listview in the target but will not apply it to the settings of the Document Set. (note: setting the Welcome Page View for a document set can only be accomplished on the Document Set contenttype at *list* level.). 
A C# equivalent can be found here: http://sharepoint.stackexchange.com/questions/119115/set-welcome-page-view-for-document-set-in-vs-project/119119#119119

**Comment by erwinvanhunen** [comment]
Thank you for feedback. We currently have no support for Document Sets in the provisioning engine, but it's on the roadmap: https://github.com/OfficeDev/PnP/wiki/Roadmap

**Comment by SjoerdV** [comment]
Thanks! always read the roadmap, right ;-)
