### ISSUE TITLE
SPOGroup additional attributes

### ISSUE THREAD

**Issue by Dean144** [OfficeDev/PnP#1053]
Please add the ability to set the all of the following attributes, Group Owner (OwnerTitle) attribute would my highest priority, but all of them would be helpful.

AllowMembersEditMembership     : False
AllowRequestToJoinLeave        : False
AutoAcceptRequestToJoinLeave   : False
CanCurrentUserEditMembership   : 
CanCurrentUserManageGroup      : 
CanCurrentUserViewMembership   : 
Description                    : Members of this group can view pages, list items, and documents.  If the document has a server rendering available, they can only view the document using the server rendering.
OnlyAllowMembersViewMembership : True
OwnerTitle

**Comment by erwinvanhunen** [comment]
CanCurrentUserEditMemberhip, CanCurrentUserManageGroup, CanCurrentUserViewMembership and OwnerTitle are not properties that can be set, only properties that can be retrieved/queried. Those values are evaluated at runtime based upon the current user that executes the session.

I added the missing attributes to both New-SPOGroup and Set-SPOGroup in PR #1055.

Closing this issue now.
