### ISSUE TITLE
BackgroundFile on ComposedLook in Provisioning Framework is not SiteCollection related

### ISSUE THREAD

**Issue by sebastienlevert** [OfficeDev/PnP#1056]
When we use the Provisioning Framework to get a SharePoint Online Provisioning Template (in my case, via Get-SPOProvisioningTemplate -Out Template.xml -PersistComposedLookFiles), the BackgroundFile comes back with its SiteCollection relative URL (/SiteAssets/Image.jpg, in my case). It should add the {sitecollection} token to the Url to ensure the file is not referred from the root Site Collection of the tenant (https://tenant.sharepoint.com/SiteAssets/Image.jpg in stead https://tenant.sharepoint.com/sites/site/SiteAssets/Image.jpg).

**Comment by VesaJuvonen** [comment]
This should be absolutely fixed with the latest builds. Sorry for the delay around responding on the issue and thanks for reporting. Composed looks have been slightly painful due numerous reasons, but should be now properly implemented.
