### ISSUE TITLE
SharePoint app using Azure Redis cache for state management / performance improvements

### ISSUE THREAD

**Issue by jansenbe** [OfficeDev/PnP#1058]
We need to add a sample that shows how Azure Redis cache can be used to manage state in a multi instance Azure web site. Any takers?

**Comment by levalencia** [comment]
Hey, Bert did you see my pull request with the Azure Redis sample? I think it hasnt been merged yet.

**Comment by levalencia** [comment]
btw, there wasnt a July community call? I also see many pull requests not merged since more than one month ago.

**Comment by erwinvanhunen** [comment]
Correct. We skipped a month due to summer vacations etc. Next one is in August.

**Comment by VesaJuvonen** [comment]
Closed with the delivery from community.
