### ISSUE TITLE
PnP - Error trying to install and apply design package using Get-SPOContext context object

### ISSUE THREAD

**Issue by sanjeev006** [OfficeDev/PnP#1065]
Hi,

When I use Get-SPOContext and pass that to DesignPackage - Install and Apply method -  I get error as shown below.

--------------------------------
$clientContext = Get-SPOContext
$site = $clientContext.Site

 Write-Host "Installing design package"
 [Microsoft.SharePoint.Client.Publishing.DesignPackage]::Install($clientContext, $site, $package, $fileRelativeURL)
 $clientContext.ExecuteQuery();

 Write-Host "Applying design package"
 [Microsoft.SharePoint.Client.Publishing.DesignPackage]::Apply($clientContext, $site, $package)
 $clientContext.ExecuteQuery()

Error message - 

Installing design package
Installation error  System.Management.Automation.MethodException: Cannot convert argument "context", with value: "Microsoft.SharePoint.Client.ClientContext", for "Install" to type
 "Microsoft.SharePoint.Client.ClientRuntimeContext": "Cannot convert the "Microsoft.SharePoint.Client.ClientContext" value of type "Microsoft.SharePoint.Client.
ClientContext" to type "Microsoft.SharePoint.Client.ClientRuntimeContext"." ---> System.Management.Automation.PSInvalidCastException: Cannot convert the "Micros
oft.SharePoint.Client.ClientContext" value of type "Microsoft.SharePoint.Client.ClientContext" to type "Microsoft.SharePoint.Client.ClientRuntimeContext".
   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConve
rt, IFormatProvider formatProvider, TypeTable backupTable)
   at CallSite.Target(Closure , CallSite , RuntimeType , Object , Object , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

-------------------------

The above code works if login in and getting context as follow.

#connect/authenticate to SharePoint Online and get ClientContext object.. 
$clientContext = New-Object Microsoft.SharePoint.Client.ClientContext($url) 
$credentials = New-Object Microsoft.SharePoint.Client.SharePointOnlineCredentials($username, $securePassword) 
$clientContext.Credentials = $credentials 

Any suggestion as to how I can make this work using Get-SPOContext instead?

Thanks,

**Comment by VesaJuvonen** [comment]
Sorry for the delay around this question. Hopefully you have been able to get this resolved and in general with questions, we would suggest to use the PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. We have released significantly enhanced PS CmdLets after this issue has been reported, so would assume that it has been already addressed. If you still see issues around this, would report the issue at PowerShell repository at https://github.com/OfficeDev/PnP-powershell.
