### ISSUE TITLE
IProvisioningExtensibilityProvider gets ClientContext with parent web

### ISSUE THREAD

**Issue by Crispify** [OfficeDev/PnP#1068]
I created a custom provider in the provisioning framework to handle some missing features. When I implement the function IProvisioningExtensibilityProvider.ProcessRequest, I receive a parameter ClientContext. In this context object I found that context.Web is the **parent web** of the web that is being provisioned at that moment. 

I expect a ClientContext object where context.Web is the web currently being provisioned.

As a workaround I am sorting context.Web.Webs by web.Created and continue with the last web in the list, which is quite safe in my scenario.

**Comment by patrick-rodgers** [comment]
@erwinvanhunen, @PaoloPia - is this expected behavior or bug?

**Comment by PaoloPia** [comment]
Maybe it's a bug. Just wondering if it happens while provisioning a Site Collection or a Sub-Site. @Crispify can you help me to fi gure out the scenario? Thanks.

**Comment by Crispify** [comment]
It's a sub-site on a second level: 
Site Collection
	 -> Sub-Site in the ClientContext
		 -> Sub-Site being provisioned

**Comment by VesaJuvonen** [comment]
This issue was moved to OfficeDev/PnP-Sites-Core#774
