### ISSUE TITLE
Incorrect assembly reference version - Provisioning.Cloud.Async.Console

### ISSUE THREAD

**Issue by relugas** [OfficeDev/PnP#1076]
Hi All, 

I am attempting to use the Provisioning.Cloud.Async.Console sample to provision sites created using the Provisioning.Clound.Async sample, however when I click Start I get an assembly reference version error:
![consolebuilderrors](https://cloud.githubusercontent.com/assets/12173263/8909702/c2363fc8-347a-11e5-8521-02d05295cfdc.PNG)

I have been able to resolve this by removing the reference and adding a previous version of the assembly (16.0.3104.1200) from an old download of PNP. By downgrading the assembly file to a previous version then the console application works as expected.

I am currently using the latest version of the repository available on the website on the day this post was created. I also find the same applies to the Provisioning.OnPrem.Async.Console sample.

Many thanks in advance,

James

**Comment by patrick-rodgers** [comment]
Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.
