### ISSUE TITLE
Add-SPOMasterpage documentation

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP#1078]
PnP/Solutions/PowerShell.Commands/Documentation/ - Dev Branch

Readme.md - Publishing -> Add-SPOMaterPage -> click -> gives 404 error

Set-SPOSearchConfiguration - Description should read "Set the Search Configuration

**Comment by erwinvanhunen** [comment]
Good find! Fixed in PR #1083, closing this issue.
