### ISSUE TITLE
YammerUtility.CreateYammerGroupDiscussionPartXml() returns webpart xml with hardcoded Version=16.0.0.0 for on-premise version of OfficeDevPnP

### ISSUE THREAD

**Issue by sadomovalex** [OfficeDev/PnP#1086]
Library version:
OfficeDevPnP.Core, Version=1.3.615.0, Culture=neutral, PublicKeyToken=null (on premise)

Method OfficeDevPnP.Core.Utilities.YammerUtility.CreateYammerGroupDiscussionPartXml() returns xml which refers to online version of ScriptEditorWebPart: 
Microsoft.SharePoint.WebPartPages.ScriptEditorWebPart, Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c

**Comment by patrick-rodgers** [comment]
Thanks for finding this - sorry for the delay in resolution. Please find updates in the dev branch [here](https://github.com/OfficeDev/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/Utilities/YammerUtility.cs#L173) and [here](https://github.com/OfficeDev/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/Utilities/YammerUtility.cs#L226) which should hopefully allow use of the correct script part. Please let us know if this is still an issue and thanks again for reporting this!
