### ISSUE TITLE
Create calculated fields in lists after creating other lists while retaining field order

### ISSUE THREAD

**Issue by erwinvanhunen** [OfficeDev/PnP#1087]
List level calculated fields can refer to other columns in the list. Right now it is required to have those fields defined before the calculated fields in order for the formulas to work. Ideally we would postpone creating calculated fields until all other list fields have been created, while retaining the list field order as defined in the template.

**Comment by NPrice99** [comment]
Same as #859 ??

**Comment by YuriLeontyev** [comment]
Receiving an error in provisioning the exported template: Apply-PnPProvisioningTemplate : The formula refers to a column that does not exist.  Check the formula for spelling mistakes or change the non-existing column to an existing column.
