### ISSUE TITLE
Provisioning Engine - List Schema should support specifying the checkout required property

### ISSUE THREAD

**Issue by mahajangaurav** [OfficeDev/PnP#1099]
The List schema of the provisioning engine does not support specifying the "Require documents to be checked out before they can be edited" property (ForceCheckout property). It will be nice to be able to specify this property via the mark up.

**Comment by patrick-rodgers** [comment]
Thank you, this is a great suggestion - we unfortunately missed this when we split out the core and hence it has not been caught. I created an issue in the new repository [here](https://github.com/OfficeDev/PnP-Sites-Core/issues/339). We will try and work it into a future release of the engine. Thank you again and sorry for the delay in responding on this.
