### ISSUE TITLE
Component.TaxonomyPicker not supported in High Trust Environment - Provider Hosted Add-In

### ISSUE THREAD

**Issue by retostadelmann** [OfficeDev/PnP#1109]
The Sample Project for the Taxonomy Picker does not seem to work for a Provider Hosted High Trust Add-In. The call to the default Keywords Termset always responds with  "Loading TermSet failed. Please refresh your browser and try again."
![2015-08-05_07-12-17](https://cloud.githubusercontent.com/assets/10433328/9078651/5ff97b22-3b41-11e5-922d-0271fdc60666.png)

**Comment by AnassKartit** [comment]
Hi,
I am facing the same issue, although it worked on my dev subscription, I am investigating the issue.

**Comment by retostadelmann** [comment]
@AnassKartit IIRC the issue on my side was not having both Default checkboxes set on the managed Metadata Service Application. See readme of the component (i opened a PR to update the readme after this issue was created and solved.):
https://github.com/OfficeDev/PnP/tree/master/Components/Core.TaxonomyPicker

**Comment by retostadelmann** [comment]
See Prerequisites Section in https://github.com/OfficeDev/PnP/tree/master/Components/Core.TaxonomyPicker

**Comment by AnassKartit** [comment]
Hi,
I am using sharepoint online, so I don't think we have the same environement and thus the same solution.

**Comment by picaca** [comment]
I was running into the same issue, when I tried to merge this taxonomy picker to the PnP partner pack project, I got the same error message: Loading TermSet failed. Please refresh your browser and try again. it occurred with SP Online.

**Comment by krunal039** [comment]
@picaca  @AnassKartit as we have same issue term does not get loaded(Loading TermSet failed) and error is for iframe forbidden ie for 

> RequestExecutor.PostMessage.Message

 in ie but works fine chrome and firefox
