### ISSUE TITLE
Bloated XML in schemaXML of a Calculated field

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP#1111]
If provision a site with Apply-SPOProvisioningTemplate and sometime later run Get-SPOProvisioningTemplate the XML for a Calculated field is bloated - 

       <Field Type="Calculated" DisplayName="Modified Date" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="1033" ResultType="DateTime" Group="XX Columns" ID="{a9cb4392-6cf9-4437-81fd-88626fde6c10}" SourceID="{59eea740-3e15-49b8-942e-78f890024f6f}" StaticName="XX_x0020_Modified_x0020_Date" Name="XX_x0020_Modified_x0020_Date" Required="FALSE" AllowDeletion="TRUE" ReadOnly="TRUE">
          <Formula>=Modified</Formula>
          <FieldRefs>
            <FieldRef Name="Modified" ID="{28cf69c5-fa48-462a-b5cd-27b6f9d2bd5f}" />
          </FieldRefs>
          <Formula>=Modified</Formula>
          <FieldRefs>
            <FieldRef Name="Modified" ID="{28cf69c5-fa48-462a-b5cd-27b6f9d2bd5f}" />
          </FieldRefs>
          <Formula>=Modified</Formula>
          <FieldRefs>
            <FieldRef Name="Modified" ID="{28cf69c5-fa48-462a-b5cd-27b6f9d2bd5f}" />
          </FieldRefs>
          <Formula>=Modified</Formula>
          <FieldRefs>
            <FieldRef Name="Modified" ID="{28cf69c5-fa48-462a-b5cd-27b6f9d2bd5f}" />
          </FieldRefs>
          <Formula>=Modified</Formula>
          <FieldRefs>
            <FieldRef Name="Modified" ID="{28cf69c5-fa48-462a-b5cd-27b6f9d2bd5f}" />
          </FieldRefs>
          <Formula>=Modified</Formula>
          <FieldRefs>
            <FieldRef Name="Modified" ID="{28cf69c5-fa48-462a-b5cd-27b6f9d2bd5f}" />
          </FieldRefs>
          <Formula>=Modified</Formula>
        </Field>

Text, Note, MultiUSer, HTML, Lookup, Choice, User all OK

**Comment by jansenbe** [comment]
Have not seen this in our test cases. Please re-open and share XML if you can still reproduce this with the latest engine version.
