### ISSUE TITLE
Provisioning Engine: Get-SPOProvisioningTemplate throws error for look up columns

### ISSUE THREAD

**Issue by mahajangaurav** [OfficeDev/PnP#1113]
Get-SPOProvisioningTemplate throws a "List does not exist" stop error if the site has a look up column that references a different web id. It should simply ignore the error, just like the Apply-SPOProvisioningTemplate does when creating such look up columns or lists which reference such look up columns

**Comment by VesaJuvonen** [comment]
Cleaning some back log and sorry for significantly delayed response on this. We should have this covered in the newest releases, but if that's not the case, could you please report that as an issue in the Core component repository at https://github.com/OfficeDev/PnP-sites-core/issues. thx.
