### ISSUE TITLE
Provisioning Engine - Apply-SPOProvisioningTemplate: Manged Metadata columns do not get associated to the term sets

### ISSUE THREAD

**Issue by mahajangaurav** [OfficeDev/PnP#1114]
I used Get-SPOProvisioningTemplate to get the terms from my source site collection. I also used the command to get the managed meta data site columns that were associated to these terms from the source. The command brings over everything including all the Ids. So you would think that provisioning the template to a new farm would not only re-create the terms and site columns but would also maintain the association between the two. This works fine when you are provisioning the template in the same farm but fails if you provision the template to a different farm. I explored the cause a bit and it turned out that the reason is that the provisioning process does not update the SSPId for the column once it gets created in the new farm. I feel like this is a quick fix that can be built into the provisioning engine. I am not sure what the process is for being able to contribute to the project but I'd love to contribute and fix such issues if you'd like & permit me to.
Thanks!

**Comment by erwinvanhunen** [comment]
You're welcome to submit a Pull Request which we will evaluate for you. To get started, please check out his wiki page: https://github.com/OfficeDev/PnP/wiki/contributing-to-Office-365-developer-patterns-and-practices

The cmdlet is just a relatively lightweight wrapper around the engine which is located in the core library at : https://github.com/OfficeDev/PnP/tree/dev/OfficeDevPnP.Core/OfficeDevPnP.Core/Framework/Provisioning

However, for your problem you're describing, there is a fix. You will have to replace the value of the SSPid with the token {SiteCollectionTermStoreId}. E.g. a search and replace in your template should suffice, e.g. find the SSPId value you want to change and replace it with "{SiteCollectionTermStoreId}". During provisioning the engine will replace that token with actual ID of the term store.

**Comment by mahajangaurav** [comment]
You guys are great! Thank you for your suggestion to use the {SiteCollectionTermStoreId} token. That did fix the issue and saved me some time having to code additional automation steps :)

A couple of things regarding the fix for the issue:
1. Thanks for pointing me to the wiki page. I will surely review it and start contributing to the project
2. Yes, I am aware that this and other cmdlets effectively refer the Core library. I have been referencing the source of the core library myself to understand the functioning of a lot of these cmdlets, especially those related to the provisioning :)
3. While using the above mentioned token was helpful in resolving my issue, my concern is that the developers/ IT pros should not manually have to replace the ids by the tokens each time they use the Get or Apply template features. Ideally, we'd fix the SspId while creating the managed metadata columns during the provisioning process. Would that be a good fix or is our concern that this solution will fail in case of multiple MMS applications? Please let me know and I'll accordingly work on fixing it.

Thanks again!

**Comment by erwinvanhunen** [comment]
Actually I would propose to the do it the other way around. During extraction of a template, check for mms fields. If any, replace the Sspid value with the corresponding token (we support 2 tokens: {SiteCollectionTermStoreId} and {KeywordsTermStoreId}. If an Sspid value matches one of those 2 values we can replace the guid with the token in the generated template. If no match, leave the Sspid value in place. If you would do it during provisioning you are a bit too aggresive during the process I think, as you're overriding something the creator of the template might have done on purpose.

Extraction of fields is happening in both ObjectField.cs and ObjectListInstance.cs.

**Comment by mahajangaurav** [comment]
Great suggestion! I absolutely agree with your recommended solution. I have a project deliverable coming up this Friday but will try and work on this over the weekend! Thanks!

**Comment by NPrice99** [comment]
Do we have an example of replacing a SspId with {SiteCollectionTermStoreId} or {KeyWordsTermStoreId} in Get-SPOProvisioningTemplate using PowerShell ? I could not see how to do it in get-help Get-SPOProvisioningTemplate

**Comment by erwinvanhunen** [comment]
no, it's not mentioned in the Get-SPOProvisioningTemplate cmdlet, as it's not cmdlet specific. The tokens are described here: https://github.com/OfficeDev/PnP/blob/master/OfficeDevPnP.Core/ProvisioningEngineTokens.md

**Comment by NPrice99** [comment]
Hi Erwin - I saw that but how do I get it to work with Get-SPOProvisioningTemplate as described above ?  I can get it to work with Apply-SPOProvisioningTemplate by Search and Replace in the Provisioning Template.  I think you need to be using C# to be able to do it using Get-SPOProvisioningTemplate not PowerShell.

**Comment by erwinvanhunen** [comment]
It is described by Paolo in this video: https://channel9.msdn.com/blogs/OfficeDevPnP/Deep-dive-to-PnP-provisioning-engine-schema starting around the 13th minute.

**Comment by erwinvanhunen** [comment]
it will not work with Get-SPOProvisioningTemplate right now. That's what I was talking about with @mahajangaurav and what he will try to make a PR from. The moment his PR is accepted and merged the Get-SPOProvisioningTemplate cmdlet (or from C# code) will produce a template where appropriate Sspid values are replaced by tokens.

**Comment by mahajangaurav** [comment]
Quick note:

The tokens do not work with the June 2015 CU. The provisioning engine throws an error if we use on of the tokes on the June 2015 CU. I can confirm that it worked fine in the same environment with an older (Dec 2014) CU. It seems like a regression bug to me introduced as part of one of the newer CUs but I'll let you confirm that.

I also was able to replicate the error by running the following script:
```Powershell
Connect-SPOnline "http://rootsiteurl" -CurrentCredentials
$context = get-spocontext
$session = get-spotaxonomysession
$store = $session.GetDefaultKeywordsTermStore()
#OR
#$store = $session.GetDefaultKeywordsTermStore()
$context.Load($store.Groups)
$context.ExecuteQuery()
$store.Groups.Count # show the number of groups in the store.
```
Also, I haven't tested this with July/ Aug CUs so am not sure if the bug still exists with the newer CUs. I'll await your confirmation if you can.

Thanks

**Comment by VesaJuvonen** [comment]
Really old one and we have done significant changes in the taxonomy field handling. If this is still an issue, would suggest to submit a new issue in the PnP Sites Core repository at https://github.com/OfficeDev/PnP-sites-core
