### ISSUE TITLE
Get-SPOTaxonomySession

### ISSUE THREAD

**Issue by mahajangaurav** [OfficeDev/PnP#1115]
The command throws the following error even after connecting to a SharePoint Root web:
format-default : The collection has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.
    + CategoryInfo          : NotSpecified: (:) [format-default], CollectionNotInitializedException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.CollectionNotInitializedException,Microsoft.PowerShell.Commands.FormatDefaultCommand

**Comment by erwinvanhunen** [comment]
The cmdlet is not to be used as is but in the following way:

```powershell
$session = get-spotaxonomysession
```
PowerShell by default tries to resolve all properties and fields in an object, if it fails to it will throw the error you're seeing. As the object returned is a ClientObject, not all the properties will be loaded by default unless requested through loading them with a context object.

The solution is to put the result of the cmdlet in a variable and use that variable for the things you want to do with it:

```powershell
$context = get-spocontext
$session = get-spotaxonomysession
$store = $session.GetDefaultKeywordsTermStore()
$context.Load($store.Groups)
$context.ExecuteQuery()
$store.Groups.Count # show the number of groups in the store.
```

So it's not an issue but actually expected behaviour. I will close this issue.

**Comment by mahajangaurav** [comment]
Thanks for the clarification Erwin! Do you mind if I go ahead and update the comments for the documentation to reflect the fact that it is returned as a ClientObject unlike some of the other objects?

**Comment by erwinvanhunen** [comment]
Please do! Keep in mind that the documentation is auto generated based on the actual comments in the code: See the cmdlet code here: https://github.com/OfficeDev/PnP-PowerShell/blob/dev/Commands/Taxonomy/GetTaxonomySession.cs

See this cmdlet for a bigger example of how to provide help in the cmdlet: https://github.com/OfficeDev/PnP-PowerShell/blob/dev/Commands/Fields/AddField.cs

Also notice that we moved the PowerShell cmdlets to it's own repository, which you can find here:

https://github.com/OfficeDev/PnP-PowerShell

Changes are to be made to the dev branch in that repository.

**Comment by mahajangaurav** [comment]
Thanks! I submitted your example as "Usage notes" for the command. I just realized though that I should have added it as an example to the actual code. My bad for doing that even after you mentioned it above :) I will fix that

**Comment by mahajangaurav** [comment]
Hey Erwin
The code sample you've provided above throws the with June 2015 CU. Looks like a regression bug to me:
Exception calling "ExecuteQuery" with "0" argument(s): "Cannot invoke method or retrieve property from null object

This CU also results in the {SiteCollectionTermStoreId} & {keywordtermstoreid} tokens to not work and throw an error while provisioning. Could you confirm that this looks like a CU regression issue to you guys as well? I haven't tested this with July/ Aug CUs so am not sure if the bug still exists with the newer CUs
Thanks
