### ISSUE TITLE
After running Get-SPOProvisioningTemplate and then Apply-SPOProvisioningTemplate get duiplicate field errors

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP#1116]
I Run Get-SPOProvisioningTemplate -Out <filename> to extract a template from a Farm created using Apply-SPOProvisioningTemplate.

If I then run Apply-SPOProvisioningTemplate -Path <filename> to create a new Farm.  I get an error "A duplicate field was found".  In the template file there is first the <Field Type="TaxonomyFieldType" DisplayName=<DisplayName> with lots of Properties eg <Name>SspId</Name> etc.  Then further down the template file is the corresponding Note Field <Field Type="Note" DisplayName="<Display Name>_0" StaticName=<Some randomset of digits>  Name=<SameSetofRandomDigits>.  Those Random Set of Digits do not appear anywhere else in the Template file.

I am using the Dev Branch from GitHub and I am on-premise.

Deleting the Note field removes the problem.

I only did this for 3 Taxonomy fields out of about 12 taxonomy fields.  There was no common denominator between those Not Fields which failed and those which did not.  In all cases the TaxonomyFieldType was before the Note field.  All Note Fields had the static name and the name as a set of digits and letters.

**Comment by VesaJuvonen** [comment]
thx Nigel,
Really old issue, which absolutely should have been fully addressed already in latest versions. There was some issues around these, but they have been addressed. If you still run into this duplicate field issue, would suggest to report that at PnP Core Team repository at https://github.com/OfficeDev/PnP-Sites-Core.
