### ISSUE TITLE
SetDefaultColumnValues does not work with special folder characters

### ISSUE THREAD

**Issue by rgueldenpfennig** [OfficeDev/PnP#1117]
We are currently integrating a library with more than 100 folders were each folder has another default value for a taxonomy column.

There are folders that contain special characters like: "®", "™", "＆", "ä", "ö", "ü"

Those characters are not escaped by SharePoint (like spaces with %20).
So in line 1046 of ListExtensions.cs in the method "SetDefaultColumnValuesImplementation" there seems to be the issue.
path = Uri.EscapeUriString(path);
In that way all special characters will get escaped. This leads to the issue that the "wrong" folder URL will be written into the "client_LocationBasedDefaults.html" file.

**Comment by VesaJuvonen** [comment]
This issue was moved to OfficeDev/PnP-Sites-Core#773
