### ISSUE TITLE
Connect-SPOnline with ADFS

### ISSUE THREAD

**Issue by arjancornelissen** [OfficeDev/PnP#1118]
Get an error message that the endpoint does not use ADFS for authentication.
When I take a look at fiddler there are 3 more roundtrips to SharePoint before the location header gives the correct ADFS location
1: /_trust/ -> location is /_layouts/15/authenticate.asxp
2: /_layouts/15/authenticate.aspx -> location is /_login/autosignin.aspx (This is a custom login page for SharePoint)
3: /_login/autosignin.aspx -> location is /_trust/default.aspx
4: /_trust/default.aspx?trust= -> location is the ADFS url.

The current code does only 1 try and fails
SPOnlineConnectionHelper.cs lines 254 - 280

**Comment by patrick-rodgers** [comment]
Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.
