### ISSUE TITLE
Access denied when trying to create objects using PowerShell

### ISSUE THREAD

**Issue by hanielc** [OfficeDev/PnP#1122]
Hi,

I'm fairly new to this, so pardon the general question.  I've been able to query information on SPO using PnP.  However, whenever I try to create new content (e.g. create site collection, import term group, add site column) I always get error messages.

Connect-SPOnline -url $siteCollectionURL -Credential (Get-Credential -Message "Please provide global admin credentials for $tenantSPRoot" -UserName $globalAdminUser)

New-SPOSite -Url $tenantSPRoot -Title $tenantTitle -Template "STS#0" -Owner $globalAdminUser -StorageQuota $storageQuota

New-SPOSite : No connection available. Use Connect-SPOService before running this CmdLet.

Import-SPOTermGroupFromXml -Path "C:\ts1.xml"

Import-SPOTermGroupFromXml : Access denied. You do not have permission to perform this action or access this resource.

Add-SPOTaxonomyField -DisplayName "Practice" -InternalName "Practice" -TermSetPath "Vorys|Practice" -Group "Vorys" -MultiValue -Required

Add-SPOTaxonomyField : Access denied. You do not have permission to perform this action or access this resource.

I'm running the code using my global tenant admin and am site collection admin on the site collection I'm working in.

Any thoughts?

**Comment by erwinvanhunen** [comment]
You are actually mixing two different modules. New-SPOSite is a cmdlet which is part of the Microsoft provided SharePoint Online cmdlets, while Connect-SPOnline is part of the PnP cmdlets.

Notice that New-SPOSite tells you to use *Connect-SPOService*, not Connect-SPOnline.

The PnP cmdlet equivalent of New-SPOSite is called New-SPOTenantSite and it has almost the same parameters.

With regards to Import-SPOTermGroupFromXml, navigate to the tenant administration site and make sure you're listed in the Managed Metadata Service as administrator.

**Comment by hanielc** [comment]
Hi Erwin,

Thank for pointing out the mix-up on the modules.  As for the Import-SPOTermGroupFromXml, I am a term store admin.  Should my context be to the admin site or the site collection I'm working with?  Export-SPOTermGroup worked fine.

**Comment by erwinvanhunen** [comment]
You context should be towards the site collection.

**Comment by VesaJuvonen** [comment]
Seems that issue has been resolved. If there's similar questions around the usage model, would suggest to use the PnP Yammer group at http://aka.ms/OfficeDevPnPYammer.
