### ISSUE TITLE
Disable Confirm not working

### ISSUE THREAD

**Issue by hanielc** [OfficeDev/PnP#1124]
I'm creating some deployment scripts that involve deleting objects that already exist (e.g. Fields).  Is there a way to disable the confirmation dialog?  I've tried appending the Remove-SPOField with -Confirm:$false and also set $ConfirmPreference = 'None' but I still get the prompts.

Remove-SPOField $oldField -Confirm:$false

Thanks,
-Haniel

**Comment by erwinvanhunen** [comment]
Hi Haniel,

Use 

Remove-SPOField $oldField -Force
