### ISSUE TITLE
Get-SPOProvisioningTemplate Not Working

### ISSUE THREAD

**Issue by ScoutmanPt** [OfficeDev/PnP#1127]
Hi, im trying to use Get-SPOProvisioningTemplate but im keep getting an error

Get-SPOProvisioningTemplate : File Not Found.

+     Get-SPOProvisioningTemplate -Web https://xxxtenant.sharepoint.com  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-SPOProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.Branding.GetProvisioningTemplate

**Comment by erwinvanhunen** [comment]
Hi!

This message could have several causes. But SharePoint has a tendency reporting 'file not found' at the weirdest spots, also when it can't find the web you're trying to connect to, or when you don't have access to it. 

You have access to the site? Do you use the -Out parameter? If so, do you have write access in the folder you're currently in?

**Comment by ScoutmanPt** [comment]
Hi Erwin, yes im full admin in the site and have full access to the current folder.

**Comment by erwinvanhunen** [comment]
Given the URL you wrote in your initial post, I assume you're working against SP online?

When you execute the cmdlet, do you get the message instantly? Or is there some progress going on first too? E.g. does it crash on a certain part in the process.

Is it an option for you to download the source and debug the code with Visual Studio?
