### ISSUE TITLE
Documentation Error in Disable-SPOFeature

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP#1131]
The title of the command is Disable-SPOFeature.
The documentation :- https://github.com/OfficeDev/PnP/blob/master/Solutions/PowerShell.Commands/Documentation/DisableSPOFeature.md
has examples using Disable-SPOOnlineFeature.

Enable-SPOFeature is OK.

**Comment by erwinvanhunen** [comment]
Thanks Nigel!

Fixed in OfficeDev/PnP-PowerShell#24.
