### ISSUE TITLE
Bug in ObjectFiles class

### ISSUE THREAD

**Issue by luismanez** [OfficeDev/PnP#1133]
Hi,
I've found a bug in the ObjectFiles class. August release adds support for using paths in the File.Src attribute, which is great. However, there's an error when checking if the file already exists in SP List:

//Original PnP (#bug): targetFile = folder.GetFile(file.Src);
targetFile = folder.GetFile(template.Connector.GetFilenamePart(file.Src));

I'm doing some real-world work with the Provisioning framework and Schema, and I would be happy to help reporting or fixing the issues/improvements I'm doing. I have no idea how to contribute and I'm quite new with Git, so I'd need little help to get started.

Many thanks!

Luis.

**Comment by erwinvanhunen** [comment]
Hi Luis, Thank you for reporting this!

We have a wiki page that helps you get up and running: https://github.com/OfficeDev/PnP/wiki/contributing-to-Office-365-developer-patterns-and-practices

**Comment by erwinvanhunen** [comment]
Notice though that that the bug you are reporting already has a pull request waiting to be merged. Have a look here: https://github.com/OfficeDev/PnP-Sites-Core/pull/3, and more specifically: https://github.com/vverbeek/PnP-Sites-Core/commit/86738035bc08552e1e4e20779e1146526df806fb

**Comment by luismanez** [comment]
Ouch! sorry @erwinvanhunen I was taking a look to the current issues and pull requests, but didn't find that one. 
I'll take a look to the How to contribute page.
Many thanks.

**Comment by erwinvanhunen** [comment]
No worries :-) The pull request was in a different repository, so it's wasn't maybe too obvious to find. We recently started to work on the split up of the main PnP repo into sub repos, and the core component has moved to https://github.com/officedev/pnp-sites-core. That's where that PR is located. I will close this issue as it will be solved by merging that pull request.
