### ISSUE TITLE
Get-SPOProvisioningTemplate throws a fatal error if a look-up site-column in the source site is referencing a list in the sub web

### ISSUE THREAD

**Issue by mahajangaurav** [OfficeDev/PnP#1142]
The error received is:
Get-SPOProvisioningTemplate: List does not exist.
The page you selected contains a list that does not exist.  It may have been deleted by another user.
At E:\Temp\Get-SPOProvisioningTemplate.ps1:5 char:1
+ Get-SPOProvisioningTemplate -Out ("Root-" + $FileName) -IncludeAllTermGroups -Fo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-SPOProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.Branding.GetProvisioningTemplate

Expected behavior:
Get-SPOProvisioningTemplate should check the web id and if the web id is different than the current web's id, it should not try to get the list.

Ideal would be to add another parameter to the filed schema so it can contain the name of the sub-web. This way, we can use that parameter in Apply-SPOProvisioningTemplate to recreate the association in the destination web

**Comment by VesaJuvonen** [comment]
This issue was moved to OfficeDev/PnP-Sites-Core#772
