### ISSUE TITLE
Provisioning Framework chokes on custom feature activation

### ISSUE THREAD

**Issue by warreq** [OfficeDev/PnP#1145]
It's a known problem that custom features cannot be activated via CSOM. Currently, The Provisioning Framework doesn't take that into consideration and will write those custom features into the XML template.

When the framework then attempts to process the feature list, it just iterates over that list and attempts to activate them, regardless of whether or not they are custom features. If a user generates a template based off of a web with a custom sandbox deployed, with a custom feature activated, attempts to provision a web based on that template will always throw a 

    ServerException: Feature with Id '<guid>' is not installed in this farm, and cannot be added to this scope.

I am unsure if this exception should be handled in the Provisioning Framework, or if it should be handled in the ProcessFeatureInternal extension method itself.

**Comment by patrick-rodgers** [comment]
Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.
