### ISSUE TITLE
RemoveExistingViews - not working with august release

### ISSUE THREAD

**Issue by xtrmdev** [OfficeDev/PnP#1146]
<pnp:Views RemoveExistingViews="true"> fails

<pnp:Views RemoveExistingViews="false"> Works

OfficeDevPnpCore15 (1.4.815.1)
In the packages the version is: 1.5.915.0 (I don't understand why ?)

ngh.Console.vshost.exe Information: 0 : 2015-08-21 13:53:27 [[PnP Provisioning]] Lists
ERROR:  Microsoft.SharePoint.Client.CollectionNotInitializedException: The collection has not been initialized. It has not been requested or the request has not
 been executed. It may need to be explicitly requested.
   at Microsoft.SharePoint.Client.ClientObjectCollection.ThrowIfCollectionNotInited()
   at Microsoft.SharePoint.Client.ClientObjectCollection`1.<GetEnumerator>d__0.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at lambda_method(Closure )
   at System.Linq.EnumerableExecutor`1.Execute()
   at System.Linq.EnumerableQuery`1.System.Linq.IQueryProvider.Execute[S](Expression expression)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source)
   at lambda_method(Closure )
   at Microsoft.SharePoint.Client.ClientQueryProvider.ExecuteExpression[TResult](Expression expression)
   at Microsoft.SharePoint.Client.ClientQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateAp
plyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningT
emplateApplyingInformation provisioningInfo)
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyi
ngInformation)
--snip

**Comment by erwinvanhunen** [comment]
<Including @jansenbe >

the version number differences are due to an emergency release we did earlier this month. We didn't upgrade the version numbers correctly. That will be fixed in the new release. 

I'll look into the removeexistingviews parameter.

**Comment by erwinvanhunen** [comment]
I just tested a template with RemoveExistingViews="true" and I received no error... Is your template XML based? If so, can you include it here so I can try your specific scenario?

**Comment by xtrmdev** [comment]
Using dotpeek and debugging, it's crashing on this line:
siteList.Views[0].DeleteObject(); Marked with <<<<<<<<< in the text below.

 foreach (ObjectListInstance.ListInfo listInfo in list2)
      {
        ListInstance templateList = listInfo.TemplateList;
        List siteList = listInfo.SiteList;
        if (Enumerable.Any<OfficeDevPnP.Core.Framework.Provisioning.Model.View>((IEnumerable<OfficeDevPnP.Core.Framework.Provisioning.Model.View>) templateList.Views) && templateList.RemoveExistingViews)
        {
          while (Queryable.Any<Microsoft.SharePoint.Client.View>((IQueryable<Microsoft.SharePoint.Client.View>) siteList.Views))
            siteList.Views[0].DeleteObject();  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<Exception
          ClientContextExtensions.ExecuteQueryRetry(web.Context, 10, 500);
        }
        ViewCollection views = siteList.Views;
        web.Context.Load<ViewCollection>(views, (Expression<Func<ViewCollection, object>>) (vs => ClientObjectQueryableExtension.Include<Microsoft.SharePoint.Client.View>(vs, new Expression<Func<Microsoft.SharePoint.Client.View, object>>[]
        {
          (Expression<Func<Microsoft.SharePoint.Client.View, object>>) (v => v.Title),
          (Expression<Func<Microsoft.SharePoint.Client.View, object>>) (v => (object) v.Id)
        })));
        ClientContextExtensions.ExecuteQueryRetry(web.Context, 10, 500);
        foreach (OfficeDevPnP.Core.Framework.Provisioning.Model.View view in templateList.Views)
          this.CreateView(web, view, views, siteList);
        if (templateList.OnQuickLaunch && templateList.RemoveExistingViews && templateList.Views.Count > 0)
        {
          siteList.RefreshLoad();
          ClientContextExtensions.ExecuteQueryRetry(web.Context, 10, 500);
          siteList.OnQuickLaunch = templateList.OnQuickLaunch;
          siteList.Update();
          ClientContextExtensions.ExecuteQueryRetry(web.Context, 10, 500);
        }
      }



Provisioning Xml:
<pnp:Lists>
    <pnp:ListInstance Title="Dokumenttyper" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/Dokumenttyper"
                      RemoveExistingContentTypes="true">
      <pnp:ContentTypeBindings>
        
        <pnp:ContentTypeBinding ContentTypeID="{ctguid}" Default="true" />
      </pnp:ContentTypeBindings>
      <pnp:Views RemoveExistingViews="true">
        <View Name="{viewguid}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Alle elementer" Url="/Lists/Dokumenttyper/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
          <Query>
            <OrderBy>
              <FieldRef Name="ID" />
            </OrderBy>
          </Query>
          <ViewFields>
            <FieldRef Name="Edit" />
            <FieldRef Name="Myfield1" />
            <FieldRef Name="Myfield2" />
            <FieldRef Name="Myfield3" />
            <FieldRef Name="Myfield4" />
          </ViewFields>
        </View>
      </pnp:Views>
    </pnp:ListInstance>
  </pnp:Lists>


This works with version: 1.3.615.0

Thanks!

**Comment by erwinvanhunen** [comment]
unfortunately your xml didn't come over correctly. You can include it if you start your reply with 3 backticks, then paste the xml, and end with 3 backticks. See http://markdotto.com/2013/04/23/formatting-code-on-github/

In the latest release we included support for delta handling (=updating existing artifacts), which is different from the build you used where it worked. I'm a bit puzzled though why it would crash on the DeleteObject call. Do you have full manage rights to the web where you want to apply the template?

**Comment by xtrmdev** [comment]
Yes, full controll. It's in my dev environment.
It looks like the Views property isn't loaded..
New try:
```
<pnp:Lists>
    <pnp:ListInstance Title="Dokumenttyper" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/Dokumenttyper"
                      RemoveExistingContentTypes="true">
      <pnp:ContentTypeBindings>
        <!--Dokumenttype-->
        <pnp:ContentTypeBinding ContentTypeID="{ctguid}" Default="true" />
      </pnp:ContentTypeBindings>
      <pnp:Views RemoveExistingViews="true">
        <View Name="{viewguid}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Alle elementer" Url="/Lists/Dokumenttyper/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
          <Query>
            <OrderBy>
              <FieldRef Name="ID" />
            </OrderBy>
          </Query>
          <ViewFields>
            <FieldRef Name="Edit" />
            <FieldRef Name="Myfield1" />
            <FieldRef Name="Myfield2" />
            <FieldRef Name="Myfield3" />
            <FieldRef Name="Myfield4" />
          </ViewFields>
        </View>
      </pnp:Views>
    </pnp:ListInstance>
  </pnp:Lists>
```

**Comment by erwinvanhunen** [comment]
Hej!

I think I found it. The list "Dokumenttyper", it's there already, correct? Before you apply the template I mean. Indeed, there is an issue with us not loading the Views collection at a certain case, which will affect you when you're specifying the 'RemoveExistingViews' attribute. I will fix it in the dev branch.

**Comment by erwinvanhunen** [comment]
It has been fixed in the new repo for Core with pull request 17: https://github.com/OfficeDev/PnP-Sites-Core/pull/17

**Comment by xtrmdev** [comment]
Perfect! Thanks!

Yep, it already exists :)

**Comment by VesaJuvonen** [comment]
Closing the issue since should be now properly fixed. Thx for your input.
