### ISSUE TITLE
Field Validation Formula Extraction Issue (GET & SET)

### ISSUE THREAD

**Issue by werocool** [OfficeDev/PnP#1164]
Hi,

When you extract and set a template for a given site with a field that contains validation. If the validation formula contains a quote ("). The resulting formula must not contain the quote (but an encoded quote: &quot).

Incorrect extraction:
![incorrectformula](https://cloud.githubusercontent.com/assets/4926713/9766870/3cc7a8ae-56e9-11e5-82c5-c72f9a34a372.jpg)

Correct extraction:
![correctformula](https://cloud.githubusercontent.com/assets/4926713/9766875/423146c4-56e9-11e5-80b4-031599e79c21.jpg)

**Comment by VesaJuvonen** [comment]
Hi Louis-Charles,
I'm really sorry for too long processing time on this. We should have this one now fixed, but if you are still running into issues around this, would appreciate if you'd report that as an issue directly to the PnP Core Component repository at https://github.com/OfficeDev/PnP-sites-core/issues.
