### ISSUE TITLE
custom.spcolor Build Action not set to None rather than Content

### ISSUE THREAD

**Issue by petecuttriss** [OfficeDev/PnP#1172]
Hi, thanks for everyone's efforts in providing such a great resource.  I've download the solution and have been trialing it.  I was getting an exception when I tried to apply the templates e.g. ContosoTemplate-01.xml.   When I stepped through I found that it was getting an exception trying to read the custom.spcolor file, and threw a FileNotFoundException.   I looked at the Azure WebJob Resources folder and found that it hadn't been deployed.   I checked the file in the project and noted that the Build Action was set to "None".  I switched this to "Content" like the other's and the file is now happily being deployed with the others to the resources folder and then system now works correctly.

Regards

**Comment by VesaJuvonen** [comment]
Hi Pete,
was not sure on the sample/solution you were referring, but assumed that this was for the Provisioning.Framework.Cloud.Async solution, which indeed had the issue for the spcolor file. This has been now fixed and checked in to the Dev branch. If this was referring to some other sample/solution, please re-open the issue with additional details.

Thx for submitting the issue.

**Comment by petecuttriss** [comment]
Hi Vesa, sorry yes, this was for the Provisioning.Framework.Cloud.Async solution.  Apology's for not noting that.   Thanks for applying the fix.
