### ISSUE TITLE
Roadmap for Provisioning.UX.App 

### ISSUE THREAD

**Issue by PieterVeenstra** [OfficeDev/PnP#1179]
In the documentation for the Provisioning.UX.App project it mentions: "Coming Updates: Sub Site Creation." When is this expected to be done. I'm using the app for one of my projects and it would be good to know if this is in progress or if we better start developing this ourselves.

**Comment by frankmarasco** [comment]
apologize for the delayed response. Right now we don't have a timeline. If you are starting in the very near future you will probably have to add the implementation.
