### ISSUE TITLE
Core.PeoplePicker

### ISSUE THREAD

**Issue by annajhaveri** [OfficeDev/PnP#1190]
Hello,

I am using csompeoplepickercontrol from Core.PeoplePicker solution in provider hosted app, which is hosted in Azure.

I have noticed that the people picker is very slow sometimes and does not show up results and showing searching text. Sometime it results in to error and the detailed error is "{\"Message\":\"There was an error processing the request.\",\"StackTrace\":\"\",\"ExceptionType\":\"\"}" 500 "Internal Server Error"

But this is intermittent, could not identify exact case when the issue occurs.

Can this be resolved?

Thanks

**Comment by VesaJuvonen** [comment]
This unfortunately cannot be solved that easily. Most likely cause is actually random throttling, which could happen or intermittent issues on the community from the provider hosted add-in to Office 365. The fact that we are getting 500 error means that people picker query was executed, but we can't really fix this random issue in the PnP side unfortunately.
