### ISSUE TITLE
Link in README for Provisioning.Cloud.Workflow.AppWeb no longer valid

### ISSUE THREAD

**Issue by johndpalm** [OfficeDev/PnP#1193]
It appears that Module 5 of the "SharePoint 2013 and SharePoint Online solution pack for branding and site provisioning" has been removed or moved from the Microsoft site.

**Comment by VesaJuvonen** [comment]
Thx John. Updated now for dev branch. This material has been moved to MSDN and corresponding article would be following: https://msdn.microsoft.com/en-us/library/office/dn985881.aspx.
