### ISSUE TITLE
Is this still recommended?

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [OfficeDev/PnP#1197]
Is it advisable to use custom master pages considering that SPO needs to push out updates every now and then? If not, shouldn't the README.md contain a note about this?

**Comment by bjorn-ali-goransson** [comment]
Wow, just realised that this repo is a megarepo containing all samples. Well, I'm talking about PnP/Samples/Branding.AlternateCSSAndSiteLogo/Branding.AlternateCSSAndSiteLogoWeb .

**Comment by kliemohn** [comment]
I see that the code skips over site collection groups.  I need to create a group that has IsSiteCollectionGroup set to true.  Is this even possible with CSOM?

**Comment by patrick-rodgers** [comment]
Hello,

You are correct, custom masterpages are no longer the preferred method - and we are in the process of reviewing all samples as things change. We will add this one to the list for review, thanks.

Cheers,

Patrick
