### ISSUE TITLE
Provide NuGet / Bower Package for PnP Core JS 

### ISSUE THREAD

**Issue by pascalberger** [OfficeDev/PnP#1217]
It would be nice to have the different JS helper scripts packaged and provided as NuGet / Bower Package, as it is already done for managed code. 

One version is here: https://github.com/OfficeDev/PnP/blob/master/Components/Core.JQuery/Core.JQuery.Promises/Scripts/officepnp.js. There are other versions in other components/samples which should be consolidated into one single core solution.

**Comment by patrick-rodgers** [comment]
Hi Pascal,

Thanks for the comment. The file and others you referenced are not meant to be a single package, just part of their respective samples. I do however really like the idea of a true package for the JavaScript common core. I'll discuss with the team and see where that falls within the other priorities, but I do think this is something in the long term plan. I have some additional JS based sessions coming up and once those are done it would make sense to start to group things and create a truly reusable package.

Cheers,

Patrick

**Comment by pascalberger** [comment]
Thanks Patrick. I've also created two PRs for improving the code in one of the samples (#1226 and #1228).

**Comment by patrick-rodgers** [comment]
Yep, saw those but haven't had a chance to review them in detail yet. Will post in those threads with status or any questions. Thanks for contributing!

**Comment by pascalberger** [comment]
And IMHO best would be to write the code in Typscript (and Typscript definitions should also be delivered with the packages) for best maintainability.

**Comment by pascalberger** [comment]
The new [Core.JavaScript](https://github.com/OfficeDev/PnP/tree/dev/Samples/Core.JavaScript) would also be a candidate to be packaged for Bower / NuGet.

**Comment by patrick-rodgers** [comment]
Going to close this, we have in the plan redoing the core as TypeScript as well as providing public packages for folks to easily add to their projects. Initially looking at npm and possibly bower. Thanks as always for your feedback!

**Comment by pascalberger** [comment]
:+1:
