### ISSUE TITLE
Link: How do I run the Office 365 Developer Patterns and Practices against SharePoint 2013 On Premises

### ISSUE THREAD

**Issue by tristian2** [OfficeDev/PnP#1222]
Hi,

the link to the "AuthenticationManager" https://github.com/OfficeDev/PnP/blob/dev/OfficeDevPnP.Core/OfficeDevPnP.Core/AuthenticationManager.cs

and GetADFSUserNameMixedAuthenticatedContext in the same page both 404.

I could do with accessing the resource to get advice on how to use the pattern and practices code to authenticate in a totally on premise scenario.

in the meantime i'll use NetworkCredential.

thanks

**Comment by rroman81** [comment]
The repo has been split. The Core project is now part of the the [PnP-Sites-Core](https://github.com/OfficeDev/PnP-Sites-core) repository, [AuthenticationManager.cs](https://github.com/OfficeDev/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/AuthenticationManager.cs). 

Take a look at the GetNetworkCredentialAuthenticatedContext() method as it's using the traditional NetworkCredential which is then used to negotiate the security context for the client call.

**Comment by VesaJuvonen** [comment]
Hi Tristian,
could you point us to the original page where that link was wrong, so that we can update it accordingly. Thanks Roman for pointing the updated location.

**Comment by tristian2** [comment]
sorry, my bad...

original link at https://github.com/OfficeDev/PnP/wiki/How-do-I-run-the-Office-365-Developer-Patterns-and-Practices-against-SharePoint-2013-On-Premises

specifically... "If you're using the PnP core library via either NuGet of via the code that you've pulled down you can also make use of the AuthenticationManager class that has the following methods to create a valid clientcontext:"


thanks

**Comment by VesaJuvonen** [comment]
Thanks Tristian, updated the broken links in the wiki now.
