### ISSUE TITLE
Provisioning.Job TemplateProviderBase GetTemplateProvider(string moduleKey)

### ISSUE THREAD

**Issue by davidhartman** [OfficeDev/PnP#1229]
Not sure if i'm doing something wrong but every time the provisioning.job console app runs it errors out when trying to return the from the GetTemplateProvider function. In ReflectionManager.cs line 88, it says that the constructor for OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLSharePointTemplateProvider does not exist. 

My temporary solution is to use OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLFileSystemTemplateProvider for the type in the ProvisioningProviders module in the provisioningSettings.config file and this appears to fix it.

**Comment by frankmarasco** [comment]
thanks for letting us know. We will look into this issue

**Comment by davidhartman** [comment]
No problem. Let me know if you need anymore information

**Comment by KrUsQ** [comment]
H. I have the same issue.

**Comment by frankmarasco** [comment]
Thanks Patrick. Sorry David for the delay.  We are still working on the issue.  Please continue to use either OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLFileSystemTemplateProvider

**Comment by frankmarasco** [comment]
Add these to your provisioning provisioningSettings.config
store your template in the hosting site https://contoso.sharepoint.com/sites/demo
store your files in the hosting site in library SiteTemplatesData and folder Assets
   <Module name="ProvisioningProviders"
                    type="OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLSharePointTemplateProvider, OfficeDevPnP.Core"
                    connectionString="https://contoso.sharepoint.com/sites/demo"
                    container="SiteTemplatesData"/>

      
      <Module name="ProvisioningConnectors"
              type="OfficeDevPnP.Core.Framework.Provisioning.Connectors.SharePointConnector, OfficeDevPnP.Core"
              connectionString="https://contoso.sharepoint.com/sites/demo"
              container="SiteTemplatesData/Assets"/>
