### ISSUE TITLE
Taxonomy Picker renders always on bottom

### ISSUE THREAD

**Issue by CBuntrock** [OfficeDev/PnP#1240]
Hello,

I was trying to use the taxonomy control on my simple page. However, it always renders on the bottom of the page. The hidden field stays where it is, but the taxonomy control is always on the bottom. This is my source:

Test<br /><input type="hidden" id="txbox" /><br />blubb

On the rendered page I always have Test and blubb together and the taxonomy control comes after it:
Test
blubb
[Control]

Is there any known bug why this happens?

Attached is my aspx file.
[taxonomy.txt](https://github.com/OfficeDev/PnP/files/42840/taxonomy.txt)

Thanks!
Best,
Christian

**Comment by CBuntrock** [comment]
Seems not to be a bug. However, solution if you use the element inside a table: It is important to put the control inside a container like a div and not directly as a table data because the javascript behind uses parent element to move the item.

**Comment by patrick-rodgers** [comment]
Seems to be no longer an issue. Please re-open if this needs further consideration. Thanks,

Patrick
