### ISSUE TITLE
Get provisioning template from sub-site. Composed look issue

### ISSUE THREAD

**Issue by KrUsQ** [OfficeDev/PnP#1242]
Hi gents. 
The situation is next:
I use ShP Online and I have created sub-site without any customization. My sub-site is a simple publishing site. The default theme of root site is Office and the theme of sub-site inherited from root, ok. If I change the root theme on, for example Orange, the theme of sub-site will be Orange. If I want to get template from this sub-site I'll get exception (Object reference not set to an instance...) .
The place of this exception is AppModelExtensions/BrandingExtensions.cs:IsMatchingTheme line 1032 calling from line 877 same cs file. The "theme" object is not null but has nulls in all properties.

Can you give me some advice about resolve this issue?
(except deleting or modified "Current" item from Composed Looks library, but also I don't know if it's correctly).

**Comment by VesaJuvonen** [comment]
Sorry for massive delay on getting this processed. We have been done significant changes on the composed look handling in the engine during spring and this should work now accordingly. If there's still any issues, would suggest to report those under the Core repository at https://github.com/OfficeDev/PnP-Sites-Core

**Comment by KrUsQ** [comment]
Thanks for the reply.
