### ISSUE TITLE
Core.JavaScript embedder on O365-D

### ISSUE THREAD

**Issue by biste5** [OfficeDev/PnP#1246]
Hi guys, 

small thing I noticed by running [Core.JavaScript.Embedder] (https://github.com/OfficeDev/PnP/tree/dev/Samples/Core.JavaScript/Core.JavaScript.Embedder) on **365 Dedicated** tenant; referencing V15 assemblies.
Line 49 in [Program.cs](https://github.com/OfficeDev/PnP/blob/dev/Samples/Core.JavaScript/Core.JavaScript.Embedder/Program.cs)
```cs
foreach (var link in  
 links.Where(l => l.Title.Equals("MyTestCustomAction", StringComparison.OrdinalIgnoreCase)))
```

returns exception *"Specified method is not supported"*
Less fancy but works instead
```cs
foreach (var link in  links)
{
   if (link.Title == "MyTestCustomAction")
  //
```

Massimo

**Comment by patrick-rodgers** [comment]
Believe this is fixed, thanks for catching that. Please let us know if you still see problems.
