### ISSUE TITLE
Inject JS on Putlishing sites

### ISSUE THREAD

**Issue by manojvnair** [OfficeDev/PnP#1247]
HI,
I'm using the PnP-master\Samples\Core.EmbedJavaScript to display a status message on all pages of my O365 sites. It works perfect on team sites but not on the home page of publishing sites.

I have tried enabling/disabling MDS but doesn't seem to make any difference. I can see the status message on document library page or site contents in publishing page but not on home page. 

The home page url is shortened in O365 hence you do not see full url to like https://site.sharepoint.com/sites/pubSite/Pages/default.aspx, even with the full url the status message doesn't show on publishing sites.

Any thoughts?

**Comment by KrUsQ** [comment]
I'm using this sample too but with my project's goals. In this sample method SP.SOD.executeOrDelayUntilScriptLoaded(function () { SetStatusBar(message); }, 'sp.js') doesn't work on some pages. Right. This is another question. Maybe something with scripts loading order or something else. Try to rewrite function :). But script and embed executed perfectly.

**Comment by patrick-rodgers** [comment]
The first two things to check would be that the JavaScript is displaying on the page markup and that there are no errors preventing it working. Also, are you using a custom masterpage or one of the OOTB ones?

**Comment by phillipharding** [comment]
Although SP.UI.Status.addStatus etc are defined in `sp.js`, the actual implementation functions are in either `core.js` or `init.js`.

It may be that either or both of `core.js` / `init.js` are not loading via the SOD framework, in which case you could try this;

```javascript
SP.SOD.executeOrDelayUntilScriptLoaded(function() {
   SP.SOD.executeOrDelayUntilScriptLoaded(function () { SetStatusBar(message); }, 'sp.js' );
}, 'core.js' );
```

**Comment by patrick-rodgers** [comment]
Thanks @phillipharding , This looks like a good answer to me - I initially misunderstood the question. The loader does not load any files other than those listed. Does this help @manojvnair?

**Comment by patrick-rodgers** [comment]
Closing because we haven't heard anything in a bit. Please do re-open if this is still an issue. Thanks!
