### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by pascalberger** [OfficeDev/PnP#1251]
What's the reason for the Version History block in the readme files, like eg [here](https://github.com/OfficeDev/PnP/blob/master/Components/Core.JQuery/readme.md)?

I don't think this makes sense at all: There is a monthly release through the master merge. The version number used in the readme files (e.g 1.1) doesn't correlate in any way to version number used for the master merge (e.g December 2015), and is also not contained in the source code at all. 
Also since this stuff is currently not available through any kind of package I don't see the reason to have any versioning.
And last but not least it is not up to date :)

**Comment by VesaJuvonen** [comment]
This would be typical Yammer discussion, so would suggest to move the discussion there. Whole point of the readme updates is that you can see if there's updates on the sample, when they were done and what they contained... In referenced sample you will see that there has been developed in September, so if you have used that for example as a reference in your own implementation, you realize that there's some changes and you can then use GitHub versioning to check them out. Actual number does not correlate on anythign else than indicates change in the sample. 

Will close this one now and if there's other pointers, would suggest that we first have a discussion in the PnP Yammer group and the create an issue, if there's changes to be applied or if there's actual bugs to fix.

PnP Yammer group can be found easily from http://aka.ms/OfficeDevPnPYammer.
