### ISSUE TITLE
Foundational sample(s) for Graph

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP#1260]
Sample(s) which are coming from Paolo around the Microsoft Graph.

*Consuming Users, and Groups*
- Consuming API metadata
- Accessing “me”
- Browsing users in the tenant
- Reading a single user by UPN
- Reading a specific user’s field/property
- Reading a specific user’s photo
- Updating “my” profile properties
- Browsing security groups

*Consuming Mail, Contacts, and Calendars*
- Browsing and querying (ODATA) mail messages of “me” inbox
- Reading a single mail message
- Sending a mail message
- Replying to a mail message
- Forwarding a mail message
- Deleting a mail message
- Browse attachments of mail message
- Browsing contacts in the tenant
- Browsing calendars of “me”
- Browsing calendars of someone else 
- Adding events to a calendar
- Reading an event in the calendar
- Accept/Decline/TentativelyAccept an invitation

*Consuming OneDrive for Business*
- Browsing and querying (ODATA) files and folders
- Creating a folder
- Uploading a file
- Copying a file
- Deleting a file

*Insights and Relationships*
- See what is trending around “me”
- See who is working with “me”

**Comment by sketa12** [comment]
It would help if we could add the following to the list
* Query the most recent changes to the OneDrive folder
* Subscribe for changes at the file or folder - and wait for notifications
* Query to find out (who has what permissions) the list of users the file/folder is shared with with edit permissions
* when the file is co-edited, detect file status (who is on the file, who is editing the file etc.)

**Comment by VesaJuvonen** [comment]
hi @sketa12, since basic sample is now done and even though your requested items are good, there's no support on them in the Graph API at the moment. If there's any questions around these, would suggest to use the PnP Yammer group at http://aka.ms/OfficeDevPnPYammer.

**Comment by sketa12** [comment]
thanks you !
