### ISSUE TITLE
(Microsoft) JavaScript programming pattern/styleguide?

### ISSUE THREAD

**Issue by Danny-Engelman** [OfficeDev/PnP#1269]
Coming from a front-end world I am trying to understand this (new) Microsoft Office365 world.

Why use

    if (window.officepnp === 'undefined') {
        $.extend(window, {
            officepnp: {}
        });
    }

instead of

    window.officepnp = window.officepnp || {};

And why are all methods declared inside the core method (making it one long page and hard to read where methods hook in) Why not more component based like:

    officepnp.core={
            _currentUserInfo: null,
            _currentUserInfoPromise: null,
            _currentUserInfoCacheKey: 'pnp-currentuserinfo'
    }
    officepnp.core.getCtxCallback = function (context, method) {}
    officepnp.core.loadFiles = function (/*string[]*/ files) {}

Is there a Microsoft Styleguide for JavaScript programming?

**Comment by patrick-rodgers** [comment]
Your first example was likely me fixing a bug with a copy/paste - it could be updated. The second point is more subjective. I prefer the way it was written - and I wrote it, so there you go. Is it better? Not really, ultimately it is the same at the end of the day.

There is not, to my knowledge, an official style guide produced by Microsoft for JavaScript programming. I did a quick search and there a bunch online, many of them conflict. I'm definitely open to a conversation within the project on how we want to format the script files.

**Comment by Danny-Engelman** [comment]
Oh yes, there are Crockford Croonies and Ad-Hoc Advocates

The first rules of A styleguide could be:

1. Code blocks (Functions, Objects, whatever) span one screen at the most
2. So Every Developer can explain code (to any other Developer)

Personally I also prefer 

* //region definitions  (Webstorm, but should also work in VS)
* utility functions in a sub-namespace (like Microsoft has done in some places with SharePoint) (that ``getQueryStringParameter`` function which pops up everywhere is an example)
* declarations with full namespace path (as shown in my first question) so you allways know What belongs where

I saw a file somewhere of some 200 lines of code of which I thought, I can fork this and make an example... but half a day later I have no clue where I saw it :-(

You can close the question, I will have some examples ready in a couple of weeks on Github related to CSR where major part of the focus is on creating readable code.

**Comment by patrick-rodgers** [comment]
Closing, please do continue the conversation on the [Yammer](https://www.yammer.com/itpronetwork/#/threads/inGroup?type=in_group&feedId=4597220) site.
