### ISSUE TITLE
PageExtensions.cs / GetWebPartXml method

### ISSUE THREAD

**Issue by KrUsQ** [OfficeDev/PnP#1279]
Hello, gents.
The new release of PnP Core has static method GetWebPartXml to export web part. Can you help me to use this method with provider hosted app? PHA use tokens and web.Context.Credentials is null. Are there any approaches to call exportwp.aspx in PHA?

**Comment by VesaJuvonen** [comment]
Since latest CSOM version, we do have export web part capability natively supported in SPO CSOM. If you have any issues on using that, would suggest to use the PnP Yammer group at http://aka.ms/OfficeDevPnPYammer for assistance.

**Comment by KrUsQ** [comment]
Good. I will check this. Thanks for the reply.
