### ISSUE TITLE
[Provisioning.UX.APP] When using the SharePoint Only Storage option the Divisions table, functions table, languages table, regions table, site classifications table and timezone table are not used

### ISSUE THREAD

**Issue by bclevering** [OfficeDev/PnP#1281]
I have configured SharePoint-Only-Storage configuration but the only thing that is loaded from Sharepoint are the template data tables. Is there something i looked over when configuring the SharePoint Only Storage?

![lists](https://cloud.githubusercontent.com/assets/8439274/12300546/52f55ba8-ba1c-11e5-8b18-f6f53a38116a.png)

**Comment by frankmarasco** [comment]
Hi,  I assume this is in related to the Provisioning.UX app. If so, can you share your PnPSiteProvisioning.xml?

**Comment by bclevering** [comment]
Yes it's indeed the Provisioning.UX app. 

[PnPSiteProvisioning.txt](https://github.com/OfficeDev/PnP/files/89313/PnPSiteProvisioning.txt)

**Comment by frankmarasco** [comment]
Hi sorry for the delay by default we do not create the template for you when using the SharePoint storage options. Thanks for bring this up as we have uncovered a issue related to using the SharePoint storage option.

**Comment by bclevering** [comment]
@frankmarasco thanks for your response! Have you got any idea when you got a fix for this issue?

**Comment by frankmarasco** [comment]
Sorry for the delay we are making the changes and testing the updates
