### ISSUE TITLE
Are the sequence working?

### ISSUE THREAD

**Issue by jeremyDaniel** [OfficeDev/PnP#1301]
hi i would like to know if sequences are working ? if tes..what is the code entry point to start a sequence (as the sequence object is not a part of the template objet) so it can not be applied by web.applyProvisionningTemplate()...
How do you launch a sequence?
Thanks a lot

**Comment by VesaJuvonen** [comment]
Unfortunately sequence support is only at schema level at the moment and there's no yet provisioning engine side implementation for it, since we wanted to ensure high quality site level handling first.

**Comment by jeremyDaniel** [comment]
Hi Vesa, thanks for answering! Does that mean the "schema level" engine-side provisioning is planned in a near future? Will there be some CSOM that will allow us to trigger the schema level XML in order to execute the sequences etc? I am currently debating on whether I should implement or not my own "sequencer" that would loop through my xml templates and apply them one after the other, but if you guys are already working on it I might as well wait for it to come out. Thanks!
