### ISSUE TITLE
Can't Get .eml attachments from outlook message.

### ISSUE THREAD

**Issue by yuribb** [OfficeDev/PnP#1311]
Hello. I have created a message with .eml files attachment. Now that i'm trying to get that message by using Microsoft.Office365.OutlookServices. I successfully received the message, but attempt to get attachment from that message using request "m_user.Messages[message.Id].Attachments" where m_user is IUserFetcher, get error "Unable to cast object of type 'Microsoft.Exchange.Services.Core.Types.ItemAttachmentType' to type 'Microsoft.Exchange.Services.Core.Types.FileAttachmentType'." in this stack trace:
"   at Microsoft.OData.ProxyExtensions.DataServiceContextWrapper.<ExecuteAsync>d__3a`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Upsafe.Office365Backup.OfficeClientWrapper.Mail.OfficeMailFolderInfo.<GetAttachmentsOfMessages>d__29.MoveNext()"."
Is it the error in the library or wrong request? Can i take my .eml attachments?
Best regard.

**Comment by VesaJuvonen** [comment]
Hi Yuri, sorry for the delay on processing this. This particular issue list is targeted around the issues in the Office 365 Dev PnP samples or solutions. Unless I understood you question wrong, that's pretty generic question around Outlook add-ins, not specifically for any sample in the PnP gallery.

If you have generic questions around Office/outlook development, would suggest to use Office 365 Technical Network and for example PnP Yammer group at http://aka.ms/OfficeDevPnPYammer.
