### ISSUE TITLE
Interesting CSOM bug

### ISSUE THREAD

**Issue by erwinvanhunen** [OfficeDev/PnP#132]
By pure chance me and @happysolutions ran into a bug in CSOM today. Or rather, not necessarily a bug if you follow the specs, but it should not be allowed what we did.

1. We used the Add-SPOField cmdlet in the PowerShell.Commands solution:
    ```
Add-SPOField -DisplayName "TestField" -Group "Test Group" -Type Text
```
2. The code was supposed to provide and static name value based upon the internal name parameter, but that one was not specified. The field XML that was created only contained a DisplayName value and null values for Name and StaticName. 
3. We received an error while creating the field, which is expected.
4. However, the field -was- created, and is listed in the Site Columns page in Site Settings. 
5. Editing the field fails from the Web UI with an error page. 
6. Retrieving the (all sitecolumn fields) fields through CSOM fails with an index out of bounds exception. 
7. Retrieving the specific field by its title fails.

E.g. we ended up in a situation where we could do nothing with the field anymore. We deleted the site collection and recreated it. We fixed the cmdlet now to make sure that the internalname parameter is required (See PR #131) but the fact that it's even possible to end up in this state my merely submitting wrong XML is not good...

The cmdlet uses the List.CreateField(string) and Web.CreateField(string) extensions in Core, which in turn use AddFieldAsXml on the FieldCollection object.

**Comment by VesaJuvonen** [comment]
Agreed to close this one. It's as designed oob functionality. Workaround is to use PnP object for creating the field.
