### ISSUE TITLE
Improved GULP process(es)

### ISSUE THREAD

**Issue by patrick-rodgers** [OfficeDev/PnP#1323]
Looking for help developing improved gulp tasks around packaging the solution as appropriate for a distribution as an npm and bower packages. Would like to include minification and file merging as possible and appropriate.

**Comment by darei-fr** [comment]
First PR around this subject performed (refactoring, browserify, tsify).
Minification & file merging ok, but seems there is issue on require function on minimized file.

**Comment by olemp** [comment]
Your PR looks good @darei-fr.

Would like dists for the separate modules aswell.

E.g. I want only pnp.provisioning.

**Comment by darei-fr** [comment]
Ok ! I understand now :)
It will be great to discuss together about all the different future dist files & dependancies.
Today I bundle all the PnP Things into one file, but of course we can change as we are going to add content.

**Comment by patrick-rodgers** [comment]
Moved to new repo: https://github.com/OfficeDev/PnP-JS-Core/issues/4
