### ISSUE TITLE
Core.JavaScript: Util.ts

### ISSUE THREAD

**Issue by olemp** [OfficeDev/PnP#1329]
When we're building the Util.ts (general JavaScript helpers/utilities), we will probably start to reflect many of the functions that already exists in underscore.js (http://underscorejs.org/).

Is this a problem? Could it be an idea to depend on it? The production dist is very lightweight (approx 5kb).

**Comment by patrick-rodgers** [comment]
Moved to new repo: https://github.com/OfficeDev/PnP-JS-Core/issues/2
