### ISSUE TITLE
Get-SPOProvisioningTemplate : The remote server returned an error: (403) Forbidden

### ISSUE THREAD

**Issue by kameronberget** [OfficeDev/PnP#1372]
I am connecting to my tenant and attempting to export the XML file. It connects just fine and seems to be processing because the status bar is moving, it gets to about 80% on 'Exporting Page Contents' and then stops with the error: **Get-SPOProvisioningTemplate : The remote server returned an error: (403) Forbidden**.

My account is a SCA.

**Comment by VesaJuvonen** [comment]
I'd test this capability with the latest April version of the Core component and also on a site which does not have that much customizations in the front page. It's also important to notice that we only export welcome page natively in the PnP engine.

**Comment by VesaJuvonen** [comment]
Hi,
if this is still an issue, could you report that directly in the PnP Core Component repository at  https://github.com/OfficeDev/PnP-sites-core/issues. thx.
