### ISSUE TITLE
 Document generator for Exported XML schema

### ISSUE THREAD

**Issue by narulasrinivas** [OfficeDev/PnP#1373]
Do we have any document generator for the exported xml from Office PnP Schema?

Please provide me some pointers.

**Comment by VesaJuvonen** [comment]
You can find the schema details and additional documentation from https://github.com/OfficeDev/PnP-provisioning-schema repository where the remote provisioning schema is version. Would also suggest to use the PnP Yammer group in future for these kind of questions to get faster response on your questions. PnP Yammer group has more than 4000 members and you can find that from http://aka.ms/OfficeDevPnPYammer.
