### ISSUE TITLE
Get-SPOProvisioningTemplate 

### ISSUE THREAD

**Issue by kameronberget** [OfficeDev/PnP#1376]
I am not able to get this cmdlet to work in office365. I have another issue open with the errors I am receiving. I have tried to use this cmdlet to connect to on premises site. The Connect-SPOnline works fine. When I try to export the ProvisioningTemplate I get "Get-SPOProvisioningTemplate : Field or property "Audit" does not exist." This is happening on a blank team site.

**Comment by ecanem** [comment]
Same issue here. By excluding Audit settings I was able to bypass this issue.

-ExcludeHandlers AuditSettings

**Comment by VesaJuvonen** [comment]
Exception indicates that you are trying to access properties, which are not exposed in your on-premises environment. This indicates that you are using older SharePoint version than supported by the PnP provisioning engine and your server side CSOM or CSOM installed on your machine where the code is running is not up to date. We have baseline of May 2015 CU for the SP2013 version.
