### ISSUE TITLE
Exception handling in Core Provisioning - Orphan Field reference in List View

### ISSUE THREAD

**Issue by MarkStokes-outlook** [OfficeDev/PnP#1381]
I am running the core provisioning commands to copy one site to another in the same tenancy and am getting an exception. (I am loving what I asm seeing in the provisioning code though. Awesome work)

`Attollo.Provisioning.Test.vshost.exe Information: 0 : 2016-03-23 12:30:20.8588	[List instances]	[10]	[Debug]	Creating view All Items	167489ms	bc99d052-2150-4484-8c97-034c1294448e
Attollo.Provisioning.Test.vshost.exe Error: 0 : 2016-03-23 12:30:20.9889	[List instances]	[10]	[Error]	Creating view failed: Column 'Target_x0020_Audiences' does not exist. It may have been deleted by another user. :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateView(Web web, View view, ViewCollection existingViews, List createdList, PnPMonitoredScope monitoredScope)	167619ms	bc99d052-2150-4484-8c97-034c1294448e
Exception thrown: 'Microsoft.SharePoint.Client.ServerException' in OfficeDevPnP.Core.dll
Attollo.Provisioning.Test.vshost.exe Information: 0 : 2016-03-23 12:30:21.5848	[List instances]	[10]	[Debug]	Code execution scope ended	168215ms	bc99d052-2150-4484-8c97-034c1294448e
Attollo.Provisioning.Test.vshost.exe Information: 0 : 2016-03-23 12:30:21.5858	[Provisioning]	[10]	[Debug]	Code execution scope ended	246520ms	bc99d052-2150-4484-8c97-034c1294448e`

It appears that a list in the source site is referring to the 'Target_x0020_Audiences' field, but this seems ot not exist.  Looks like an Orphaned field reference in one of the list views.

What the ApplyProvisioningTemplate code appears to do when I continue running is go back, start the ApplyProvisioingTemplate again and get stuck at the same point and just keep looping through.

Could the error handling be updated to just discard a field in this case? Or at the very least, update the console output to tell me which list and view this action is running on?  From the errors above, it seems to just be on an AllItem.aspx page, but I cannot tell which one.

**Comment by VesaJuvonen** [comment]
This is good feedback and we can absolutely add a check-up for the fields and ignore issue if the field is missing for a reason or another. Orphan fields are relatively rare, but absolutely possible with SharePoint (unfortunately) and having engine gracefully dealing this situation would make sense.

**Comment by VesaJuvonen** [comment]
This should be fixed in the May release, but would double check. If ti's still an issue, could you report that directly in the PnP Core Component repository at  https://github.com/OfficeDev/PnP-sites-core/issues. We do understand that it takes some time, but you could cross link this one. Just ensuring that things are not missed if they are located in wrong repository. thx.

**Comment by sivapratapkurapati** [comment]
HI,

I have used the code as mentioned. but i am getting the below error when the code executes "Web.ApplyProvisioningTemplate().

Unhandled Exception: Microsoft.SharePoint.Client.ServerException: Column 'Target_x0020_Audiences' does not exist. It may have been deleted by another user.

Please find below code part for ApplyProvisioningTemplate:
private static void ApplyProvisioningTemplate(ConsoleColor defaultForeground, string targetURL, string userName, SecureString pwd)
        {
            using(ClientContext ctx=new ClientContext(targetURL))
            { 
                ctx.Credentials = new SharePointOnlineCredentials(userName, pwd);
                ctx.RequestTimeout = Timeout.Infinite;

                Web web = ctx.Web;
                ctx.Load(web);
                ctx.ExecuteQuery();

                XMLTemplateProvider provider = new XMLFileSystemTemplateProvider(@"D:\SiteTemplate\pnpprovisioningdemo", "");
                ProvisioningTemplate template = provider.GetTemplate("PnPProvisioningDemo.xml");

                ProvisioningTemplateApplyingInformation ptai= new ProvisioningTemplateApplyingInformation();
                ptai.ProgressDelegate = delegate(String message, Int32 progress, Int32 total)
                {
                    Console.WriteLine("{0:00}/{1:00} - {2}", progress, total, message);
                };

                // Associate file connector for assets
                FileSystemConnector connector = new FileSystemConnector(@"D:\SiteTemplate\pnpprovisioningdemo", "");
                template.Connector = connector;
                web.ApplyProvisioningTemplate(template, ptai);

                Console.WriteLine("End: {0:hh.mm.ss}", DateTime.Now);

            }

Can you please help?

Regards,
Sivapratap.
