### ISSUE TITLE
_item[SiteRequestFields.STATUSMESSAGE_NAME] = statusMessage does not work for long messages

### ISSUE THREAD

**Issue by niklasosth** [OfficeDev/PnP#1383]
In **SPSiteRequestManager.cs** method **UpdateRequestStatus** the statusMessage is written to the Item's field **SiteRequestFields.STATUSMESSAGE_NAME**. That field is limited to **255 characters** in the SharePoint list instance and the update will break if the message is longer than that.

Some truncation of the message would be a good idéa:
if (statusMessage.Length >= 255) { statusMessage = statusMessage.Substring(0, 252) + "..."; }

**Comment by VesaJuvonen** [comment]
Thx Niklas, fixed now in the dev branch.
