### ISSUE TITLE
External / CDN libraries are loaded too late (Custom Actions load AFTER JSLink)

### ISSUE THREAD

**Issue by Danny-Engelman** [OfficeDev/PnP#1386]
I am almost to 2.0 with a generic CSR support library.

Having some issues with deployment:

* Adding the library as ScriptLink/Custom action loads it **before** msajaxbundle where ``Type.registerNamespace`` is defined

The workaround is to put a copy of msajaxbundle in the style library, and load it as (another) Custom Action:

![](http://i.imgur.com/5vaIR5I.jpg)

I first tried the absolute CDN url for msajaxbundle but then (for me) unwanted behaviour happens.

So I have these CustomActions: 

![](http://i.imgur.com/Wy1LQYA.jpg)

The absolute URL **is** loaded, but only way down after many scripts have loaded:

![](http://i.imgur.com/ETTIFcM.jpg)

That means: **Custom Action files with external URLs are loaded AFTER JSLinks**

And that really s*ks because I would like to have one (CDN) JS library

**Comment by VesaJuvonen** [comment]
This is good feedback around the oob behavior, but unfortunately we can't really directly control the out of the box behavior through PnP initiative and tooling, so would not consider this as an issue in the PnP sample (unless completely mistaken). Hopefully you were able to figure out a way to do this, but if more detailed discussion around the options are needed, let's have that discussion in the PnP Yammer group at http://aka.ms/OfficeDevPnPYammer.
