### ISSUE TITLE
Custom sorting not working for control

### ISSUE THREAD

**Issue by RiddhiKarani** [OfficeDev/PnP#1387]
if we apply custom sort on the term store manager the PnP control sorts alphabetically and does not sort based on the sorting applied to the term store,

**Comment by pbjorklund** [comment]
```
//sort by Name that all of the choice will return alphabeticall
this.FlatTerms.sort(function (a, b) {
    if (a.Level > topLevel) { topLevel = a.Level; }
    a = a.Name.toLowerCase();
    b = b.Name.toLowerCase();
    if (a < b) return -1;
    if (a > b) return 1;
    return 0;
});
```
This is the only sorting done by the taxonomypicker if I remember correctly.

I think an approach like the one used in https://gist.github.com/cwparsons/170be6f8b6a8c253fc46 at row 114 would work fine with this. (Could even be copy+pastable and it's actually well documented. Kudos to @cwparsons). 

I'm probably to busy with other stuff to take this on right now.

**Comment by BrianMichely** [comment]
Gautam took this one on and it's now in the dev branch. Thanks guys. Closing this issue.
