### ISSUE TITLE
Can't delete a term

### ISSUE THREAD

**Issue by i2bglobal** [OfficeDev/PnP#1395]
I tried deleting a term by highlighting the term and then pressed the delete key or tab key.
Neither of the keys worked, it actually redirected to the previous page.
Also there so no button to remove a term from the selection.
So how to delete a term ?

**Comment by VesaJuvonen** [comment]
This would indicate that you do not have sufficient permissions to delete the term in the particular site collection. In general PnP GitHub issue list is for the code related issues in the PnP assets, so would suggest rather to use IT Pro Yammer groups at https://www.yammer.com/itpronetwork/#/threads/inGroup?type=in_group&feedId=3903794
