### ISSUE TITLE
Provisioning.Framework.Console: field or property 'NoCrawl' does not exist

### ISSUE THREAD

**Issue by dulubi** [OfficeDev/PnP#1399]
I downloaded the code and run the Provisioning.Framework.Console for SharePoint 2013 on-premise but got the error : "field or property 'NoCrawl' does not exist" upon generating the site template:

ProvisioningTemplate template = ctx.Web.GetProvisioningTemplate(ptci);

Anyone encounter this?

**Comment by VesaJuvonen** [comment]
This would indicate that you are using SPO CSOM in your customizations. This means that your code is trying to access property in on-premises, which is not available. See following resources for details on using right CSOM for your environment.
- http://dev.office.com/blogs/using-correct-csom-version-for-sharepoint-customizations
- http://dev.office.com/blogs/sharepoint-CSOM-versioning-for-your-customizations
