### ISSUE TITLE
Office365Tenant QueueImportProfileProperties return error Operation is not valid due to the current state of the object

### ISSUE THREAD

**Issue by AmineHameg** [OfficeDev/PnP#1400]
When i execute this query to bulk update UPA properties
var workItemId = tenant.QueueImportProfileProperties(userIdType, userLookupKey, propertyMap, fileUrl );
ctx.ExecuteQuery();
I got this error :
"Operation is not valid due to the current state of the object"

Have you any idea about this?

**Comment by AnassKartit** [comment]
it means something has changed from the time you request the change to the time you have executed the Query, do you have a workflow/ event receiver that is probably changing a property while you executed the query.

https://social.technet.microsoft.com/Forums/en-US/e78ddb4d-5b5d-41e0-b903-1fe6f805ea98/operation-is-not-valid-due-to-the-current-state-of-the-object?forum=sharepointgeneralprevious

**Comment by VesaJuvonen** [comment]
Bulk API is only currently available in first release tenants. You'd get this exception if the capability is not yet available in your tenant. We do not currently have exact date for world wide release for non-first release tenants.

**Comment by vmunagala0117** [comment]
Hi Vesa,
I'm getting the same error as well. Also I have spun up a new dev tenant a couple of weeks ago. Does it mean the update has not reached my tenant yet?

**Comment by wobba** [comment]
@VesaJuvonen Any information on when this will be flighted for GA? I need it for my app :)

**Comment by kingfu** [comment]
@VesaJuvonen Hi I am getting a guid value of 00000000-0000-0000-0000-000000000000 whenever I run this.  No job is set up in the collection.  Do you know what could be wrong?

**Comment by wobba** [comment]
@kingfu this should work fine. You can also test with using 
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpupabulkimportjob?view=sharepoint-ps

**Comment by kingfu** [comment]
Thanks, Mikael!  That seems to be working better for me.

**Comment by wobba** [comment]
You can see the CSOM code of it at https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/UserProfiles/NewUPABulkImportJob.cs

**Comment by kingfu** [comment]
Looks like the file has to be on the local drive and not somewhere like a
SharePoint Doc lib, right?

**Comment by wobba** [comment]
No, you upload the file to a SP lib, and the job picks from there.

**Comment by kingfu** [comment]
Gosh, I know I'm going to sound like an idiot, but I'm not sure how to code
the -path part of the parameter.  When I uploaded the same file via
SharePoint Online to a document library I used the "copy link" command and
then pasted that into the -path parameter which gave me the error "local
file was not found".  I appreciate any help you can provide.
This command works:
New-PnPUPABulkImportJob -Folder "Shared Documents" -Path
"c:\assets\userprofileimport.json" -IdP
roperty "IdName" -UserProfilePropertyMapping
@{"EmpId"="EmpId";"wellnessvu"="wellnessvu";"exp"="exp";"expgiven"="expgive
n";"healthpoints"="healthpoints"}

however this one does not
New-PnPUPABulkImportJob -Folder "Shared Documents" -Path "
https://tenant.sharepoint.com/:u:
/t/SharePointServices/EXH86mKWjflOhz-hzYRguwEBt0Irgyowxkn5BjtWHg2rOQ?e=3bzvdb"
-IdProperty "IdName" -UserProfileProperty
Mapping
@{"EmpId"="EmpId";"wellnessvu"="wellnessvu";"exp"="exp";"expgiven"="expgiven";"healthpoints"="healthpoints"}

**Comment by wobba** [comment]
Because the cmdlet assumes you have a local file and then uploads it. Look at the code and see how it internally queue up the job which picks up the file from SharePoint.
