### ISSUE TITLE
Value cannot be null. Parameter name: certificate

### ISSUE THREAD

**Issue by AnassKartit** [OfficeDev/PnP#1401]
Hi,
I deployed PnP partner pack to pre-production tenant on *.azurewebsites.net and it worked.
in production using a custom domain and ssl certificate it is not working and we are receiving the value cannot be null. The PFX has been succesfully imported in the portal though.

![certificate](https://cloud.githubusercontent.com/assets/12949390/14433822/1a15af4c-0010-11e6-8ff8-45ccb6bffe52.PNG)

**Comment by PaoloPia** [comment]
Double check the thumbprint of the certificate. Often there is a trailing hidden char that makes it invalid. It often happens when you copy the thumbprint from the properties of the certificate file. Use powershell instead to load the certificate and read the thumbprint.

**Comment by AnassKartit** [comment]
I did it is not generated using powershell. However, I think I am missing this 
The certificate must be created for key exchange, exportable to a Personal Information Exchange (.pfx) file.
I imported the pfx but the option to export the private key is greyed out, is that an issue?

**Comment by PaoloPia** [comment]
Probably you did not created the certificate with the capability to export the private key. I would suggest you to follow the instructions we provide in the PnP Partner Pack site, and to create the certificate with the PowerShell script that we provide.

**Comment by pdl5p** [comment]
This can also occur if you forget to include the WEBSITE_LOAD_CERTIFICATES app setting.

**Comment by izzo2k4** [comment]
I'm having an exact same issue, but it could be failing for completely different reasons.  Which brings me to the following question.  I'm wondering if the PnP Partner Pack is supported in a multi-tenant scenario?  For example, where the Web App and the Storage Account reside in one Azure tenant, while the Azure AD App is still registered in a tenant hosting Office 365.
Thanks in advance!
