### ISSUE TITLE
provisionning stuck in step ..INFO] 04/11 - Features

### ISSUE THREAD

**Issue by AnassKartit** [OfficeDev/PnP#1408]
Hi,
we are using the continuous job to automatically provision site collections when they are created.
to create an empty site, it is working. but to create a customized site with publishing activated, custom lists and branding it is stuck in Features for two hours and it does not complete. I made the timeout infinite as below in code.

output of the job is below:

[04/19/2016 14:53:27 > 27d1c4: INFO] 01/11 - Regional Settings
[04/19/2016 14:53:28 > 27d1c4: INFO] 02/11 - Supported UI Languages
[04/19/2016 14:53:28 > 27d1c4: INFO] 03/11 - Site Security
[04/19/2016 14:53:40 > 27d1c4: INFO] 04/11 - Features

any idea?
Thanks

**Comment by VesaJuvonen** [comment]
You should absolutely get an exception from the web job as well, which is needed to understand what goes wrong. One of the things which could cause this is publishing features - they are really resource intensive and they can also timeout when activated. We are working on this internally in engineering, so that things would work faster.

**Comment by AnassKartit** [comment]
Hi Vesa,
we are branded the website and we need to activate publishing feature in the timer job, any turn arounds for this requirement? we disperately need this feature.
Thanks

**Comment by VesaJuvonen** [comment]
Hi Anass,
there has been issues around the publishing feature time outs, but these should be again resolved. Are you still getting these exceptions in your solution?

**Comment by AnassKartit** [comment]
Hi vesa,
We stopped activating publishing and I ended up creating a custom engine that does not use pnp templating based on pnp core samples to create lists webpages and branding injection based on the pnp core. We faced many issues in recreating site collections from saved templates such as the need to replace group security principals in some xml... i can share thoughts to improve and identify the issues.

**Comment by VesaJuvonen** [comment]
Absolutely interested on any details. One way to still benefit of the PnP provisioning engine is to use it for generic elements and then implement all custom requirements as a extensibility provider. This way the core engine will evolve based on the Core component updates, but you can still fully control what get's created with the templates. Here's a sample of custom extensibility provider - https://github.com/OfficeDev/PnP/tree/master/Samples/Provisioning.Extensibility. 

Obviously falling back on custom process is absolutely fine as well.
