### ISSUE TITLE
Not able to set Default Value using Add-SPOTaxonomyField Command

### ISSUE THREAD

**Issue by rahulbarua87** [OfficeDev/PnP#1415]
I am able to create a Managed Metadata Column but i am unable to set default value for the column.

`Add-SPOTaxonomyField -DisplayName "Test1" -InternalName "Test1" -TermSetPath "People|Job Title" -Group "CG Columns" -MultiValue -Required`

Please suggest is there any option by which i can set default value for managed metadata column.

**Comment by VesaJuvonen** [comment]
This issue was moved to OfficeDev/PnP-PowerShell#466
