### ISSUE TITLE
AuthenticationHelper on Core.UserProfiles.Sync should use async version of AcquireToken

### ISSUE THREAD

**Issue by robertos** [OfficeDev/PnP#1445]
The AuthenticationHelper in this sample is using AcquireToken instead of AcquireTokenAsync. This is not a high priority issue but given that this is a sample that many people use as reference I believe it's worth fixing.
 I'm planning to submit a pull request with a proposed fix soon.

**Comment by VesaJuvonen** [comment]
Fix merged as part of the #1447
