### ISSUE TITLE
Inconsistent RoleDefinitionPermission enumeration

### ISSUE THREAD

**Issue by hyankov** [OfficeDev/PnP#1464]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[X] Bug

_Some_ of the members in the **RoleDefinitionPermission** enumeration differ from the SharePoint's **SPBasePermission** enumeration members.

e.g. '**AddListItems**' instead of '**InsertListItems**', '**AddAndCustomizePages**' instead of '**WriteWebPages**', '**Open**' instead of '**OpenWeb**, '**CancelCheckout**' instead of SharePoint's '**BreakCheckout**'.

**Comment by VesaJuvonen** [comment]
This issue was moved to OfficeDev/PnP-Sites-Core#771
