### ISSUE TITLE
Issue with provisioning a site with OfficedevPnp since Friday June 17th

### ISSUE THREAD

**Issue by angelanouwens** [OfficeDev/PnP#1465]
Hi all,

We deploy certain SharePoint Online sites with the help of OfficedevPnp. This always worked fine and last Thursday we have created several sites with it. On Friday however something probably changed we now get an error.
We use the schema's of OfficeDev from august 2015 so maybe it's just outdated but would like the confirmation that installing OfficedevPnp actually does solve the issue we are experiencing since friday.
The error we get starts with [List instances Data Rows] [1] [Error] Creating listitem failed: exception from HRESULT: 0x80131904: at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)......
And gives:
"Error during provisioning of template Lists.xml - Error

Anybody any experience with this or does anyone knows it something changed on SharePoint Online which causes OfficeDevPnP to fail?

Like to know more.

**Comment by kbarret3** [comment]
+1 from me. We too are experiencing the same issue that started occurring about the same time.

**Comment by angelanouwens** [comment]
@kbarret3  which version of devPnP are you using? also an older version ?

**Comment by kbarret3** [comment]
Hi @angelanouwens. Yes my code base was I think on the first release that included the capability to provision a site based on a template site. The OfficeDevPnPCore package is at version 1.3.0615.0

**Comment by angelanouwens** [comment]
Thanks for your reaction. We are currently very busy working on the issue and probably updaten devPnP as soon as possible to see if this solves the issue.
Will keep you updated when we have found a solution

**Comment by johnsandersnl** [comment]
+1 We have the same issue/error. Also the schema from august 2015.

**Comment by VesaJuvonen** [comment]
This issue was moved to OfficeDev/PnP-Sites-Core#770
