### ISSUE TITLE
GetAzureADAppOnlyAuthenticatedContext MissingMethodException / GetAzureADNativeApplicationAuthenticatedContext: TypeLoadException 

### ISSUE THREAD

**Issue by TimDaborn2** [OfficeDev/PnP#1469]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ ] Bug

#### Environment
[ ] Office 365 / SharePoint Online

#### Expected or Desired Behavior
Not to crash!

#### Observed Behavior
I seem to be suffering a NuGet conflict with the pnp library and any version package of the Microsoft.IdentityModel.Clients.ActiveDirectory after 2.26.

The current version is 3.10.  The source references  version 2.18 - originally released in June 2015.

Using any of the last 3 versions of the Microsoft.IdentityModel.Clients.ActiveDirectory package, commands such as 
	AuthenticationManager().GetAzureADAppOnlyAuthenticatedContext
	AuthenticationManager().GetAzureADNativeApplicationAuthenticatedContext

raise Missing Method exception and TypeLoadExceptions, respectively.

**Comment by VesaJuvonen** [comment]
This issue was moved to OfficeDev/PnP-Sites-Core#769
