### ISSUE TITLE
Set-SPOTaxonomyFieldValue can't set multiple terms

### ISSUE THREAD

**Issue by revelationzero** [OfficeDev/PnP#1470]
PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[X] Bug
[X] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Call Set-SPOTaxonomyFieldValue should be able to set multiple Terms for example, I was expecting like the following line of code might work, but was not able to get it working.  
	
Set-SPOTaxonomyFieldValue -ListItem $newListItem -InternalFieldName "TaxonomyColumn" -termpath "TermGroup|TermSet|Term;TermGroup|TermSet|Term"

I would suggest having a Add-SPOTaxnomyFieldValue, and Remove-SPOTaxonomyFieldValue cmdlet that can add terms to value(s) to a taxonomy column that allows for multiple values.

**Comment by VesaJuvonen** [comment]
This issue was moved to OfficeDev/PnP-PowerShell#465
