### ISSUE TITLE
Spelling error and wrong link

### ISSUE THREAD

**Issue by rolandoldengarm** [OfficeDev/PnP#1475]
The third link of alternative solutions (Provisioning UX App) [here](https://github.com/OfficeDev/PnP/tree/master/Solutions/Provisioning.Cloud.Sync) should point to 
https://github.com/OfficeDev/PnP/tree/master/Solutions/Provisioning.UX.App

There is also a spelling error in the title of the link.

**Comment by VesaJuvonen** [comment]
thx Roland, small thing, but obviously should be corrected. Now finally fixed in dev branch and will merged to master early Sep.
