### ISSUE TITLE
JavaScript Override create subsites not working in the new Modern look Site Contents Page

### ISSUE THREAD

**Issue by StaffanNelemans** [OfficeDev/PnP#1484]
How to override the new Create Subsite in the Modern look Site Contents Page (_layouts/15/viewlsts.aspx?view=14) ?

**Comment by ufchacho** [comment]
Hello Staffan, have you been able to find an alternative solution?

It seems that the panel that contains the "new subsite" link is managed by a kind of a KnockoutJS app... As it is appending and removing the content from the page, I'm not able to override the event.

Regards,
Ricardo.

**Comment by VesaJuvonen** [comment]
You can keep on using Classic mode or slightly different approach with the sub site creation, which has been now included in the dev branch. With the new approach, we also check if we land on the sub site creation page and do automatic redirect from there. This means that you'll land on custom page also with new experience. It's not 100% optimal implementation, but works for now, until we from engineering will provide more polished solution.

**Comment by VesaJuvonen** [comment]
Updated today to dev branch, will be merged this Friday (9th of Sep) to master branch - https://github.com/OfficeDev/PnP/tree/dev/Samples/Provisioning.SubSiteCreationApp
