### ISSUE TITLE
Possible issue with remove event receiver sample

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP#153]
Reported through email.
Sample: Core.EventReceiver 

the code does deploy to Office365 … but it never seems to run the http://localhost:44375. Also, in Office365 is says: “Sorry, something went wrong with adding the app.”. 

Thus, I feel the sample always is failing due to me not doing something.

**Comment by danbudimir** [comment]
Here's a tl;dr to get the sample running
1) From Azure PowerShell execute the following command to create a Azure Service Bus Namespace
**new-azuresbnamespace "namespace" "region" –createacsnamespace $true –namespacetype  Messaging**
Replace **"namespace"** and **"region"** with the appropriate values.
2) Copy the ConnectionString returned in the Azure PowerShell console window and paste it into the **"Microsoft Azure Service Bus connection string"** text box from the SharePoint tab in the Properties window of your SharePoint project in Visual Studio.

**The long version:**

Here are your options in order of "Most likely".

1) Set up Azure Service Bus - This is required for debugging Remote Event Receivers through o365.  The links below will give you the steps for getting it set up.  One caveat, you can no longer create a service bus namespace through the Azure Portal UI that supports ACS, ACS is required for remote debugging a Remote Event Receiver, so you must use Azure PowerShell.

**Important: Do not skip.**  [Service Bus Authentication and Authorization] (https://msdn.microsoft.com/en-us/library/azure/dn170478.aspx)
[How to: Debug a remote event receiver in an app for SharePoint](https://msdn.microsoft.com/en-us/library/office/dn275975.aspx)
[How do I debug Remote Event Receivers?] (https://msdn.microsoft.com/en-us/library/office/dn456315.aspx#RER_DebugRER)

Other options are 
2) Run the test in a closed environment on a dev vm where SharePoint is installed.
3) Ensure that the URL to the RER that you are testing is resolvable by the server where SharePoint is running.

Calls to remote event receivers(RER) are made from the SharePoint server directly to the web site where the RER is running, they do not use the S2S connection typically associated with Provider Hosted Apps. The o365 server cannot resolve http://localhost:44375 so you end up with an error indicating that there is no endpoint listening.

**Comment by VesaJuvonen** [comment]
Let's update the original Sample (https://github.com/OfficeDev/PnP/tree/master/Samples/Core.EventReceivers) with the this additional information as well for the benefit of the community and close the issue after that... so that we have this tracked.

**Comment by VesaJuvonen** [comment]
readme.md has the needed reference to MSDN material. Closing the issue.
