### ISSUE TITLE
Business.O365StarterIntranet Deployment errors

### ISSUE THREAD

**Issue by smushkat** [OfficeDev/PnP#1530]
#### Which PnP repository to report the issue?
[https://github.com/OfficeDev/PnP/tree/master/Solutions/Business.O365StarterIntranet]https://github.com/OfficeDev/PnP/tree/master/Solutions/Business.O365StarterIntranet

#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I'm getting the error below when running the .\Deploy-Solution.ps1 script for the Business.O365StarterIntranet solution.  I've done through the steps all of the prior steps, no errors or warnings, and I'm using the June 2016 Intermediate 3 SharePointPnPPowerShellOnline cmdlets.

I've tried this on two separate Windows 10 boxes with the same results.  I am running PowerShell as an admin, and I'm SCA on my target site collection which was created with the Publishing template.  Steps 1 and 2 completed without errors.

#### Observed Behavior
The error messages from PowerShell are:

![o365intranetinstallerrors](https://cloud.githubusercontent.com/assets/3729134/18803001/89fa3086-81ba-11e6-80ba-cfb4cb2eca42.JPG)

The text of the first message is:
3# Apply the provisioning template to the root site...
Apply-SPOProvisioningTemplate : Specified argument was out of the range of valid values.
Parameter name: lcid
At D:\PnP-master\PnP-master\solutions\Business.O365StarterIntranet\Deploy-Solution.ps1:98 char:1
+ Apply-SPOProvisioningTemplate -Path $ProvisioningRootSiteTemplateFile ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-SPOProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate

#### Steps to Reproduce
I walked through the "Set up your Environment" instructions twice with the same results, as shown above.

Thanks for putting this sample together!  Looks like it will be a big help.

**Comment by FranckyC** [comment]
Hi @smushkat. I think the problem is that the french language is not activated in your term store. I've just fixed this  this prerequisite in the dev version (see the README file).

Let me know!

**Comment by smushkat** [comment]
@FranckyC , merci beaucoup!  Enabling French in the term store got me past this error.  I still had some trouble with the current master branch, but then decided to give the Dev branch a try with the September 2016 PnP Online Powershell release, and that worked just fine.  The Deploy-Solution.ps1 script ran through to completion.

**Comment by FranckyC** [comment]
@smushkat Enjoy this solution and don't hesitate if you have questions!
