### ISSUE TITLE
Can't webpack PnP Starter Intranet for Office 365/SharePoint Online

### ISSUE THREAD

**Issue by Kaermic** [OfficeDev/PnP#1549]
#### Category

[X] Bug
[ ] Enhancement
#### Environment

[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013
#### Expected or Desired Behavior

I was trying to install PnP Starter Intranet for Office 365/SharePoint Online as described in the md file. (https://github.com/OfficeDev/PnP/tree/master/Solutions/Business.O365StarterIntranet). 
I follow all instructions until webpack.
#### Observed Behavior

When i "webpack" the app folder, there are a many ERRORs like "error TS2339: Property 'web' does not exist on type 'Rest'." and many others, all in TS files.
#### Steps to Reproduce

I think it could come from a missing dependency but i can't figure which one.
I'm also new at using TypeScript ... Can you help me ?

TypeScript 1.8.10
WebPack 1.13.2
All other dependencies comes from the configuration files.

**Comment by FranckyC** [comment]
Hi @Kaermic. I think this is due to the "sp-pnp-js" package version. Which version do you use? You have to get the 1.0.4 version because there are big differences between the 1.0.4 and 1.0.5. To force this version, open the package.json file and remove the "^" character for the sp-pnp-version module ("sp-pnp-js": "1.0.4"). Let me know!

**Comment by Kaermic** [comment]
Hi @FranckyC, tanks for your quick answer.
Forcing the sp-pnp-js version to 1.0.4 solve all "ERROR" messages during the webpack.
Looking forward to try that solution, thank you for your work on it :)

**Comment by FranckyC** [comment]
@Kaermic Did you try the solution? Is everything ok for you?

**Comment by Kaermic** [comment]
Everything seems ok, really nice job.
