### ISSUE TITLE
Truncated internal name

### ISSUE THREAD

**Issue by bubuthebeast** [OfficeDev/PnP#1556]
Hi to all.
I don't know if it can be defined bug or feature or simply a question:
Is it possible that PnP Provisioning truncates field internal name to 32 character?

In my XML I've a Name="xxxxxxxxxxxxxxxxxxxxxxxManagerApproval" (38 char) and once this field is deployed, its internal name is "xxxxxxxxxxxxxxxxxxxxxxxManagerAp" (32 char).

Really, the site column is right, the site column inside the site content type is right, the list content type is truncated and the list column is truncated.

Thanks,
Sergio

**Comment by bubuthebeast** [comment]
Hi.
It seems that is a SharePoint limit applicable only on the list: if I create the list using the feature way all works fine.

http://benhuang.blogspot.it/2009/08/32-character-limit-in-sharepoint-lists.html

**Comment by VesaJuvonen** [comment]
Since this is SP internal limitation, we can't really fix this in the PnP engine, since PnP relies on the out of the box APIs. Closing the issue, since issue solved / resolved with your follow up comment.
