### ISSUE TITLE
Retrieve more items than Threshold limit with JSOM and REST - batched queries happen twice each

### ISSUE THREAD

**Issue by thunderstorm654** [OfficeDev/PnP#1564]
####Which PnP repository should you use to report the issue?####
- PnP Samples - https://github.com/OfficeDev/PnP/Samples/Core.ListViewThreshold.JSOMAndREST/

#### Category
[ ] Bug

#### Environment
[ ] Office 365 / SharePoint Online

#### Expected or Desired Behavior
The code for either JSOM or REST should return all the results of your query in a large list in batches of 5000 until the total number are returned. E.g. my list has 12213 items and the query covers returning all of them, so there should be two batches of 5000 items then a final batch of 2213 returned.

#### Observed Behavior
Each batch seems to execute twice. This occurs for both JSOM and REST. So you get the first 5000 items twice, second 5000 twice, then final 2213 twice. So every result is duplicated.

#### Steps to Reproduce
The code in App.js has to be updated to actually loop the results.

Here is my updated code:
//This function for testing ListView Threshold for REST
function REST() {
    var configuration = SharePointClient.Configurations;
    var utility = new SharePointClient.Utilities.Utility();
    //configuration.IsApp = true;
    
    var listServices = new SharePointClient.Services.REST.ListServices();

     //REST Listservices class for accessing list services
    var listServices = new SharePointClient.Services.REST.ListServices();

    //Set response type
    var responseType = SharePointClient.Constants.REST.HTTP.DATA_TYPE.JSON;

    var listTitle = "Workflow Tasks";
    //Create Caml object
    var camlConstant = SharePointClient.Constants.CAML_CONSTANT;
    var camlQuery = new SharePointClient.CamlExtension.REST.CamlQuery();
    camlQuery.SetViewScopeAttribute(camlConstant.CAML_QUERY_SCOPE.RECURSIVE_ALL)
    .SetViewFieldsXml("<FieldRef Name='ID'/><FieldRef Name='Title'/>")
        //.SetQuery("<Where><Geq><FieldRef Name=\"Modified\" /><Value Type=\"DateTime\" IncludeTimeValue=\"TRUE\""
    //+ "StorageTZ=\"TRUE\">2014-08-05T15:50:08</Value></Geq></Where>")
    .SetQuery("<Where><Geq><FieldRef Name=\"Modified\" /><Value Type=\"DateTime\" IncludeTimeValue=\"TRUE\">2014-08-05T15:50:08</Value></Geq></Where>")
    .OverrideQueryThrottleMode(camlConstant.CAML_QUERY_THROTTLE_MODE.OVERRIDE)
    .OverrideOrderByIndex()
    .SetRowLimit(5000);

    //Get All list items batch by list name
    listServices.GetListItemsBatchByListName(listTitle, camlQuery.BuildQuery(), responseType).Execute(function (result) {
        //logic for working with returned result set
        
        console.log(result);

        var tasksHTML = "";
        var results = JSON.parse(result.d.RenderListData);

        console.log(results);
        console.log(results.Row.length);

        for (var i = 0; i < results.Row.length; i++) {
            tasksHTML = tasksHTML +
                "<p><h1>" + results.Row[i].Title +
                "</h1>" + results.Row[i].ID +
                "</p><hr>";
        }

        $("#taskresults").append(tasksHTML);

    });
}

//This function for testing ListView Threshold for JSOM
function JSOM() {
    var configuration = SharePointClient.Configurations;
    var utility = new SharePointClient.Utilities.Utility();
    //configuration.IsApp = true;
    

    SharePointClient.Services.JSOM.Initialize(function () {
        var listServices = new SharePointClient.Services.JSOM.ListServices();

        //Get SP clientContext
        var context = new SharePointClient.Services.JSOM.Context();

        var listTitle = "Workflow Tasks";
        //Create Caml object
        var camlConstant = SharePointClient.Constants.CAML_CONSTANT;
        var camlQuery = new SharePointClient.CamlExtension.JSOM.CamlQuery();
        camlQuery.ViewAttribute(camlConstant.CAML_QUERY_SCOPE.RECURSIVE_ALL)
        //.Query("<Where><Geq><FieldRef Name=\"Modified\" /><Value Type=\"DateTime\" IncludeTimeValue=\"TRUE\""
        //+ "StorageTZ=\"TRUE\">2015-08-05T15:50:08</Value></Geq></Where>")        
        .Query("<Where><Geq><FieldRef Name=\"Modified\" /><Value Type=\"DateTime\" IncludeTimeValue=\"TRUE\">2015-08-05T15:50:08</Value></Geq></Where>")
        .ViewFieldsXml("<FieldRef Name='ID'/><FieldRef Name='Title'/>")
        .QueryThrottleMode(camlConstant.CAML_QUERY_THROTTLE_MODE.OVERRIDE)
        .OrderByIndex()
        .RowLimit(5000);

        //Get All list items batch by list name
        listServices.GetListItemsBatchByListName(context, listTitle, camlQuery.BuildQuery()).Execute(function (result) {
            //Read all items

            console.log(result);
            console.log(result.get_count());

            var tasksHTML = "";

            var ListEnumerator = result.getEnumerator();
            while (ListEnumerator.moveNext()) {
                var currentItem = ListEnumerator.get_current();
                // do something with your list item
                var title = currentItem.get_item("Title");
                tasksHTML = tasksHTML +
                    "<p><h1>" + currentItem.get_item("Title"); +
                    "</h1>" + currentItem.get_item("ID"); +
                    "</p><hr>";
            }

            $("#taskresults").append(tasksHTML);

        }); 
    });
}

You'll see in the console that each batch runs twice, e.g for my list of 12213 items I see the following logged - e.g. for the JSOM version:
![image](https://cloud.githubusercontent.com/assets/16837607/20347203/ee18ceda-abf7-11e6-8ecc-aee8016b5a4b.png)

And every item therefore gets written to the page twice as I am appending them to a div.

I have made **no changes** to any other code except the above to try and iterate/output the results returned.

Any suggestions on how to fix would be great, I'm not quite sure what the issue is (presumably in the method in SharePointClient.js).

Thanks!

**Comment by thunderstorm654** [comment]
Closed- realised the issue was actually with the click event being added in document.ready() and it was getting registered twice!

**Comment by thunderstorm654** [comment]
The problem was actually the onclick event being registered in document.ready - it was getting added twice. Closed.

**Comment by ahsanranjha** [comment]
i am getting error invalid index. 

 configuration.IsApp =true;
    configuration.SPUrl = '/';
    configuration.IsCrossDomainRequest = true;

**Comment by PrashantRatanpara** [comment]
I am getting 0 Rows in second auto call when i keep OverrideOrderByIndex(). But when i remove the line then it works but will not work with all the list it gives error in some.

**Comment by PrashantRatanpara** [comment]
When i use Lookup column in then next auto call will not bring any rows, but with normal column it works and iterates and bring respected data.
