### ISSUE TITLE
Taxonomy picker on sharepoint hosted app

### ISSUE THREAD

**Issue by levalencia** [OfficeDev/PnP#166]
I tried to make the taxonomy picker with a sharepoint hosted app. I based my code on the Core.TaxonomyPicker example, I used jquery 2.1.1, and modified the references to js files like this:

<head>
    <meta charset="utf-8" />
    <title>Learning bootstrap</title>    
    <meta name="viewport" content="width=device-width, initial-scale=1">   

    <link href="../Content/bootstrap.min.css" rel="stylesheet" /> 
    <link href="../Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link rel="Stylesheet" type="text/css" href="../Content/taxonomypickercontrol.css" />
    <script src="../Scripts/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="/_layouts/15/sp.runtime.js"></script>
    <script type="text/javascript" src="/_layouts/15/sp.js"></script>

    <script src="../Scripts/app.js" type="text/javascript"></script>
    <script src="../Scripts/taxonomypickercontrol.js" type="text/javascript"></script>
</head>

on the body I have this:

         <div class="ms-core-form-line" style="margin-bottom: 0px;">
                               <input type="hidden" id="taxPickerContinent" />

                            </div>

and on the app.js I have this:
  $('#taxPickerContinent').taxpicker({ isMulti: false, allowFillIn: false, useKeywords: false, termSetId: "51f18389-f28a-4961-a903-ee535f7c620d", levelToShowTerms: 1 }, context, initializeCountryTaxPicker);
                                    taxPickerIndex["#taxPickerContinent"] = 0;

The picker works fine, except for 2 things:
1.  When I allow fill in choices and I try to add to the root node, the item disappears, If I try to add to a child term, it works.
2. When I start typing, nothing is suggested.

I have also asked this here:
http://stackoverflow.com/questions/25949758/cannot-read-property-children-of-null-when-trying-to-add-terms-via-sharepoint-ho

**Comment by VesaJuvonen** [comment]
Core.TaxonomyPicker is only for provider hosted app at least for now, you should use oob taxonomy picker with SharePoint hosted app implementation.
