### ISSUE TITLE
Request time out exception for OneDriveCustomizer

### ISSUE THREAD

**Issue by anderswaller** [OfficeDev/PnP#183]
When applying a theme in OneDriveCustomizer I got time out exception. 

Uploading the theme works rootWeb.DeployThemeToWeb(...)
but  rootWeb.SetThemeToWeb("SPC") causes the time out. 

The theme gets applied but the web property value is never updated (because of the time out) and therefore OneDriveCustomizer always runs and tries deploying the theme and set the theme. Anyone else experiencing the same problem? 

I'm running this code in a Azure web role in a Cloud Service.

**Comment by VesaJuvonen** [comment]
https://github.com/OfficeDev/PnP/tree/master/Solutions/OD4B.Configuration.Async shows the process as async patter with Azure which will tackle this issue.
