### ISSUE TITLE
Securing provider hosted app 

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP#185]
Future enhancement to include. Sample and documentation on how to secure provider hosted app in Azure with http module (oAuth) and/or with membership provider. Pretty classic request with the provider hosted apps, so let's get this one documented as reference solution.

**Comment by PaoloPia** [comment]
I think this one is still open. In that case I can take it, if you like.

**Comment by jansenbe** [comment]
please do :)

**Comment by VesaJuvonen** [comment]
Closed to clean up the backlog.
