### ISSUE TITLE
Core.TaxonomyPicker should catch backspace

### ISSUE THREAD

**Issue by pbjorklund** [OfficeDev/PnP#19]
Backspace triggers in browser command "back" even when terms selected.
It should delete the term.

IE 11.0.9600 @ win 8.1

**Comment by danbudimir** [comment]
I am unable to repro the behavior described with the latest code so I'm closing this one.  Please re-submit with detailed steps for repro if I am incorrect.

**Comment by jansenbe** [comment]
When you open the dialog, add a few terms, select them and then press backspace the issue will happen. When in the dialog, backspace should trigger the deletion of the last added label

**Comment by danbudimir** [comment]
My fault.  Got it now.  Thanks

**Comment by patrick-rodgers** [comment]
Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.
