### ISSUE TITLE
ExecuteQuery parameter in CreateField methods, Obsolete?

### ISSUE THREAD

**Issue by erwinvanhunen** [OfficeDev/PnP#257]
Would it be an option to remove the executequery parameter in the createfield methods? I understand the idea behind it, but from an execution flow perspective, it's pretty complex to figure out when to execute or the request anyway. I doubt many people actually use the parameter to batch up the request before they execute it. Besides that, we don't expose that option in any of the other methods anyway...

**Comment by VesaJuvonen** [comment]
Decision and changes on the Core around this were already implemented. Closing the issue.
