### ISSUE TITLE
DesignPackage.Install wipes design catalog (_catalogs/design, list template 124)

### ISSUE THREAD

**Issue by jansenbe** [OfficeDev/PnP#260]
Bert,

Do you have access/visibility to get this bug fixed. Details below:

The lines below (in OfficeDev PnP, from InstallSolution()) wipe/clear all items in the composed looks aka design catalog (_catalogs/design, list template 124):

    DesignPackage.Install(site.Context, site, packageInfo, packageServerRelativeUrl);
    site.Context.ExecuteQuery();

The solution package should be loaded into the solutions catalog (_catalogs/solutions, list template 121).

A clue to the bug is in the DesignPackage.UnInstall() method which, when the solution does not exist throws an error (mentioned in the code above).

The full text of the error message is: "Invalid field name.
{33e33eca-7712-4f3d-ab83-6848789fc9b6}
/sites/test.pnp.sg6/_catalogs/design"

Note that it is referring to the design catalog URL, indicating that this function is accessing the wrong list. This may be a misunderstanding due to the name "DesignPackage" and confusion between design catalog vs solution catalog.

I am going to disable the tests so they doesn't break the theme tests.

Sly

**Comment by hhtech1** [comment]
Please check this related topic in User Voice, which discusses some of the issues with DesignPackage and the need for better support for activating sandbox solutions instead of the DesignPackage workaround: 
https://officespdev.uservoice.com/forums/224641-general/suggestions/5633494-add-support-for-sandbox-solutions-upload-and-activ

**Comment by VesaJuvonen** [comment]
Since this is actually oob behavior of the CSOM APIs, we can't fix this in the PnP side. Will work with the feature crew on this based on the input at the user voice.
