### ISSUE TITLE
BrandingExtensions.cs: ServerRelativeUrl is not initialised

### ISSUE THREAD

**Issue by zrahui** [OfficeDev/PnP#280]
For the BrandingExtensions.cs, inside the below method:
```
public static ListItem GetPageLayoutListItemByName(this Web web, string pageLayoutName)
```
The property `ServerRelativeUrl` is not initialised before this line:
```
 var fileRefValue = 
string.Format("{0}/{1}{2}", masterPageGallery.RootFolder.ServerRelativeUrl, pageLayoutName,
                ".aspx");
```

I'm not sure if hardcoding the file extension is really worth it? From a provisioning point of view, wouldn't you want to specify the entire filename + extension? That would keep it consistent with other Property values.

**Comment by arnabbhowmick** [comment]
Hello,

Is the issue raised by zrahui is resolved? I am still getting error if I try to set available page layouts page name with ".aspx" extension. If I pass the layout name without the extension, then it is working fine.

Thanks & Regards,
Arnab Bhowmick

**Comment by jansenbe** [comment]
Hi Arnab,

I've reopened the issue...we'll further investigate this. Can you provide us the exact error message and stack trace. I also assume you're using a recent PnP Core library version?

**Comment by arnabbhowmick** [comment]
Hello,

The error message is "Object reference not set to an instance of an object".

We are calling "SetAvailablePageLayouts" method which in tern calling "GetPageLayoutListItemByName". This method is throwing error while we are passing layout page name with extension.

Call Stack:

.....
at Microsoft.SharePoint.Client.BrandingExtensions.CreateXmlNodeFromPageLayout(XmlDocument xd, Web web, Web rootWeb, String pageLayoutName)
   at Microsoft.SharePoint.Client.BrandingExtensions.SetAvailablePageLayouts(Web web, Web rootWeb, IEnumerable`1 pageLayouts)

**Comment by patrick-rodgers** [comment]
Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.
