### ISSUE TITLE
Core.DialogWeb UserCustomAction

### ISSUE THREAD

**Issue by JulesAnime** [OfficeDev/PnP#299]
Trying to get this sample to work on-premise and keep getting:- 
Original error: System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.SharePoint.SPUserCustomAction.set_CommandUIExtension(String value)  

I have turned on verbose logging on SP Foundation CSOM to see if anything detailed .. Visual Studio just comes back with Unknown Error

This occurs when trying to add a custom action to the SiteActions "Add menu item", the site page option works fine; however I can not figure why I am getting this problem.

The issue occurs when trying to execute the following snippet in the NavigationExtensions.cs:-

            targetAction.Update();
            web.Context.Load(web, w => w.UserCustomActions);
            web.Context.ExecuteQuery(); --- Error here

**Comment by jansenbe** [comment]
There was a small bug in the custom action remove functionality that has been fixed today...might be related?

**Comment by jansenbe** [comment]
@JulesAnime : do you still have this issue?

**Comment by VesaJuvonen** [comment]
Let's reopen if issue can be reproduced again.
