### ISSUE TITLE
Core.EventReceivers Not Authorized 401 - On Premise

### ISSUE THREAD

**Issue by JulesAnime** [OfficeDev/PnP#308]
I have been struggling with this now for a while, and at some point it worked, but now it is broken again.

As per the title I am trying to get this working On Premise just using your code in Visual Studio 2013. I have replaced all the references to the 15 version of the DLL; set the properties of the Core.EventReceivers.Web with:
Anonymous Authentication: Disabled, 
Windows Authentication: Enabled
SSL Enabled: True

This results in the AppEventReceiver.svc as being un-reachable as the SVC page displays "The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'NTLM,Negotiate'. ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized"

If I then make the following properties:
Anonymous Authentication: Enabled, 
Windows Authentication: Enabled
SSL Enabled: True

The call to the AppEventReceiver.svc is executed but the clientContext.ExecuteQuery() is unauthorized 401 Access Denied

I have even added and removed "AllowAppOnlyPolicy" in the AppManifest

As I say I got this working (somehow) but am unable to get it working again and we are hoping to use Remote Event Receivers this is critical.

Is this still the correct PnP to use for RER and if so what is the correct combination of settings.

**Comment by frankmarasco** [comment]
@JulesAnime Sorry for the vary delayed response to this. But you do need to enable anonymous and have an SSL endpoint. Are still having issues?

**Comment by frankmarasco** [comment]
closing for now but will reopen if needed.
