### ISSUE TITLE
FxCop custom rules for PnP

### ISSUE THREAD

**Issue by jansenbe** [OfficeDev/PnP#316]
From Erwin: 

I just created a custom FxCop rule that can check for it. It requires that we create a specific ruleset for the PnP project and include the assembly with the rule code somewhere in the dev branch. We then point to our custom rule set in the code analysis setting. I guess we then also should add the FxCop rule code to the dev branch. The code will of course not get compiled into the Core library, but it's a nice touch to have the FxCop rule visible too for other people to reuse. 

Of course it adds a bit of 'overhead'.
•We add a new project to the dev branch containing the FxCop fule (a separate project because it needs references to 2 assemblies that are of no use for the Core library)
•We create a new custom ruleset and add our custom rule to it
•We use that ruleset for code analysis
•This would open up things for more rules in the future of course :-)

Any comments?

[Update] It seems that Visual Studio likes the compiled assembly to be in place if it wants to use it in a ruleset. That's a bit ugly. Dynamically building the project and then using the assembly with the rules seems not to work for me.

**Comment by erwinvanhunen** [comment]
Maybe we should close the issue for now. The pattern is pretty clear among the core team members that perform the merges.

**Comment by jansenbe** [comment]
Indeed :)
