### ISSUE TITLE
Move PnP.Core to it's own repository

### ISSUE THREAD

**Issue by pbjorklund** [OfficeDev/PnP#319]
The repo is really large right now. Let's discuss ways to get it leaner.

I would really prefer a PnP.Core repo with only the core and tests for the core project. Then it would be possible to have a repo for PS, one for samples/solutions etc.
Each repo could have it's own README.md which gives an overview of the actual part.

**Comment by pbjorklund** [comment]
The entity framework repo is 20mb.

**Comment by VesaJuvonen** [comment]
Basically we have outgrown the reasonable size, so we will need to start splitting the repo. This will be one topic for Jan community call with suggestion for comments.

**Comment by frankmarasco** [comment]
I think we should look at other options by splitting things out

**Comment by jansenbe** [comment]
We've split off the guidance part to a separate repository (https://github.com/OfficeDev/PnP-Guidance) which will result in a smaller repo size. Given scenarios and solutions depend on PnP and to not add additional complexity for contributors the core team choose to keep all code together in the PnP repo.
