### ISSUE TITLE
Use of ex.Message.IndexOf in code

### ISSUE THREAD

**Issue by nanddeepn** [OfficeDev/PnP#326]
Hello, 
At most of the places, code depends on exception message.

For e.g.:
In TenantExtensions.cs, the check is 
if (ex.Message.IndexOf("Unable to access site") != -1)

Which will work only if the site follows English language and will not work for sites getting created in other languages, because the ex.Message will be that language specific.

Hope, I have valid concern.

**Comment by jansenbe** [comment]
Duplicate of #392, closing this one.
