### ISSUE TITLE
CreateComposedLookByName creates new context object and breask app only process

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP#337]
CreateComposedLookByName method creates new context or tries to create new context to the root site of site collection. This could work with user credentials, but fails with app only toke usage with async patterns. 

There's no way currently to upload or create easily theme to root site of  site collection using app only token. This capability has been removed or marked as deprecated, which obviously has to be fixed.

**Comment by jansenbe** [comment]
CreateComposedLookByName has been tested using app only (see unit test changes for app only testing) and the Clone change makes it work under app only

**Comment by VesaJuvonen** [comment]
Will be fixed in the Nuget package when the Jan release will be pushed out. Issue still exists in the Dec Nuget package.
