### ISSUE TITLE
Apply branding with master pages??

### ISSUE THREAD

**Issue by bobbyware** [OfficeDev/PnP#351]
Why is this sample still in this repository?
https://github.com/OfficeDev/PnP/tree/master/Samples/Branding.ApplyBranding

Custom master pages is advised against, so it should not be in this repo I'd guess? It's confusing!

**Comment by VesaJuvonen** [comment]
We indeed recommend to use alternative options than custom master page for branding. This is however recommendations and they are absolutely supported and of the used. You can still definitely use them as well, as long as you make knowingly decision to do so with possible future maintenance cost. They are pretty commonly used in portal side, but not that often in collaboration sites.

This is why we have actually still multiple examples in PnP for custom master page deployment and we will keep on having them in as long as custom master pages are supported. Removal of custom master page support from Offfice 365 is not even decided, so these samples will be still available.
