### ISSUE TITLE
Updating the Office365Api.Overview

### ISSUE THREAD

**Issue by PaoloPia** [OfficeDev/PnP#357]
Bert,
can I update the Office365Api.Overview sample targeting the latest releases of the ADAL and Office365 APIs? As far as I can see it targets an old version. I'm asking before moving on, just in case somebody else is already working on it.

Thanks,
Paolo

**Comment by jansenbe** [comment]
Please go ahead Paolo :)

**Comment by VesaJuvonen** [comment]
Excellent...

**Comment by frankmarasco** [comment]
Thanks Paolo looking forward to seeing the updated verision
