### ISSUE TITLE
Error when Debugging UserProfile.Manipulation.CSOM 

### ISSUE THREAD

**Issue by jtrimblecraez** [OfficeDev/PnP#364]
I am trying to use the patterns and practices examples called userprofile manipulation CSOM to understand more about the ability to change info in a users profile field. I may have found a bug in the code. I am working with a office 365 sharepoint site. The project will build and install on a dev site but when I click on the link to one of the senarios I get an error in the code behind for the codesample1 that the reads the clientcontext is null. Is there some thing that I am doing that is not correct?

**Comment by frankmarasco** [comment]
I will try to repo the issue. please allow me sometime.

**Comment by frankmarasco** [comment]
HI jtrimblecraez, I was unable to repo the issue. Which scenario did you have issues with?

**Comment by VesaJuvonen** [comment]
Same here, could not repo. Tested the sample without issues. One possible challenge might be though the CSOM version what you are using. Please check that you have the latest CSOM from this location - http://aka.ms/spocsom. 

Second option would be to go and change the version number from app.config file with leading .1. That would force the app to be reinstalled to the site, if trust failed for some reason.

**Comment by VesaJuvonen** [comment]
Please let us know what was the result.

**Comment by jtrimblecraez** [comment]
Thank you both for checking into this issue .... I would say that the issue is with the CSOM version. I need to understand more about how to install that version. I will report back with my findings.

**Comment by frankmarasco** [comment]
Anytime. I will keep this open just awhile longer until you get back to us.

**Comment by jtrimblecraez** [comment]
forgive me as I am a rather new developer. I think that I have the correct Csom version as I have went into my references in the project and see that the version of the microsoft.sharepoint client is version 16. and runtime version v4.0.30319.... is this the correct version?

**Comment by frankmarasco** [comment]
No worries. Yes that is the correct version if you are using Office 365 MT.
![snippet](https://cloud.githubusercontent.com/assets/7659319/5670338/9ee7847e-9744-11e4-8c5c-4a7ea895938d.PNG)

**Comment by jtrimblecraez** [comment]
Well shoot, 

That is the correct Version and yes I am using O365 MultiTenant. we are actually going in a different direction being that we are using angular. We are going to use json. I will try to sweep back around on this issue and wee if I can work on this in my spare time to try a few other things. thank you both for your time and I am sure it is something that I am dong wrong. you can close this issue out.

**Comment by frankmarasco** [comment]
Feel free to ping us back or reach out to us at http://aka.ms/OfficeDevPnPYammer
