### ISSUE TITLE
How can I use People Picker in MVC Application (cshtml file)? 

### ISSUE THREAD

**Issue by johnflaster** [OfficeDev/PnP#365]
I need to use this People Picker in a cshtml file.

**Comment by SharePointRadi** [comment]
Can you clarify if your MVC application is completely standalone and will always point to 1 tenant, or you are creating a provider-hosted app in ASP.NET MVC?

In both cases you can get this going.

**Comment by johnflaster** [comment]
My app is ASP.NET MVC provider-hosted.

**Comment by SharePointing** [comment]
Is it single tenant (ie only to be used against one single tenant at a time) or multi-tenant (you want to use the same provider for multiple O365 tenants)

Both are possible but there are some different considerations for MT.

**Comment by jansenbe** [comment]
@johnflaster : did you manage to get this working?

**Comment by MeenakshiVirk** [comment]
Hey johnflaster, did u get this working. please upload solution

**Comment by VesaJuvonen** [comment]
Closed due lack of response. Capability is also demonstrated in the PnP Partner Pack with ASP.NET MVC application.

**Comment by DennisJantos** [comment]
It seems that the People Picker implementation in the PnP Partner only works with one principal. If you allow multiple principals, you will get an issue with removing principals. The array of principals send to the server has invalid indexes. Did someone get the People Picker working with ASP.NET MVC with multiple principals enabled?
