### ISSUE TITLE
Easier upload to sub folders in libraries

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP#371]
From Yammer group.
Q - "Using the PnP for the O365 branding. What would be the best recommendation around loading files into subfolders (e.g. files\styles\blue\blue.css), it doesn't seem that the current PnP caters for this type of scenario. I am busy modifying the functions to cater for it, but just want to hear others thoughts.."

A - "That is good feedback and we should indeed improve this in the Core component to have capability for more simpler sub folder targets. Right now you would have to loop through the folders by yourself in CSOM. 

It would be great if we would have capability to simply provide target folder path for example simply with string "files\syles\blue" and the method would hide the complexity to check folder existence and possible creation if it's not there. "

**Comment by jansenbe** [comment]
There's an option to call EnsureFolderPath ([FileAndFolderExtensions](https://github.com/OfficeDev/PnP/blob/dev/OfficeDevPnP.Core/OfficeDevPnP.Core/AppModelExtensions/FileFolderExtensions.cs)) to create a folder structure before calling UploadFile. Would that be sufficient?

**Comment by VesaJuvonen** [comment]
Closed to clean up the backlog.
