### ISSUE TITLE
Adding multiple values to key using PowerShell.Commands Set-SPODefaultColumnValues gives an error

### ISSUE THREAD

**Issue by ronaldvanherk** [OfficeDev/PnP#376]
I need to add multiple values to the defaultcolumnvalue of a list and with the Set-SPODefaultColumnValues I cannot get it working.

Is it supported? If not, can that be created? If it is supported, what is the syntax to use for value?
I tried with an array but get an error:

Set-SPODefaultColumnValues : Cannot bind parameter because parameter 'Value' is specified more than once. To provide multiple values to parameter
s that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".

PS: I love this solution
Regards,
Ronald

**Comment by erwinvanhunen** [comment]
How do you use the command?

The correct syntax is 

Set-SPODefaultColumnValues -List "Test" -Field "Test" -Value "Value 1","Value 2","Value 3".

**Comment by ronaldvanherk** [comment]
I tried your example and it works now, with just the values as string with a comma seperated.
Thanks Erwin.
