### ISSUE TITLE
Possible issue with term store import which needs to be checked

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP#384]
From PnP Yammer group
"I was trying to make those two Powershell-Skripts work. The Export worked quite good and I also put the ID's into the file (txt). but if I try to import I always get an error saying that Group names must be unique. Also I didn't found a way to tell the System to which SiteCollection to bind the imported TermStore. It's a Site Navigation that I try to get from Test to Production. Any Tips on how to achieve this..."

**Comment by erwinvanhunen** [comment]
Indeed, that sounds like a bug, and an enhancement at the same time. I'll dive into it.

**Comment by erwinvanhunen** [comment]
I can confirm this being an issue. I'm investigating the bug.

**Comment by erwinvanhunen** [comment]
Fixed several issues in PR #395
