### ISSUE TITLE
Do not check for literal exception message text

### ISSUE THREAD

**Issue by erwinvanhunen** [OfficeDev/PnP#392]
In the Core library there is code that checks for the actual exception message. E.g.:

if (ex.Message.StartsWith("Invalid field name. {33e33eca-7712-4f3d-ab83-6848789fc9b6}", StringComparison.OrdinalIgnoreCase))

This check will fail on those site collections where the default language is not English. We need guidance/examples on how to handle these cases correctly.

**Comment by SharePointRadi** [comment]
Duplicate with #326. What is the best way to handle this?

**Comment by jansenbe** [comment]
I'll close #326 with a reference to this bug.

**Comment by jansenbe** [comment]
FYI: Have fixed this for tenant extensions. Others still todo

**Comment by jansenbe** [comment]
Fixed most others...
