### ISSUE TITLE
Sample for header and footer model

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP#419]
We have few JS injection samples already there, but we should also provide one complete sample with classic monster header and footer injection, together with personalization and taxonomy driven approach. Just to tie in the guidance and to have one sample which shows how to achieve this, including proper client side caching. 

Something in line of https://github.com/OfficeDev/PnP/tree/master/Samples/OD4B.NavLinksInjection, but to have personalized links controlled from taxonomy terms and footer which is also dynamic.

**Comment by ashuetawah** [comment]
I would like to take this up.

**Comment by jansenbe** [comment]
Would be awesome :)

**Comment by aaclage** [comment]
Dear all, can i extend the https://github.com/OfficeDev/PnP/tree/dev/Samples/Core.GlobalBreadcrumbRibbon to include this option, with taxonomy and footer?

**Comment by VesaJuvonen** [comment]
Hi André, that would absolutely work and would be the best option. I'd almost be tempted then though to update the sample name slightly to match on the capabilities, but adding footer would certainly be highly helpful.

**Comment by aaclage** [comment]
agreed, about the naming i am open for suggestions, i'm starting to think this sample is turning more like a a solution....

**Comment by VesaJuvonen** [comment]
If not too much burden, would suggest to change the name as Core.EmbedJavaScript.HeaderFooter, so that it would be grouped with other samples which are also user the UserCustomAction collection and embedded JavaScript.

**Comment by aaclage** [comment]
ok sample Core.GlobalBreadcrumbRibbon will be renamed to Core.EmbedJavaScript.HeaderFooter, correct?

**Comment by VesaJuvonen** [comment]
Yes. That would be the optimal setup. Thx.

**Comment by aaclage** [comment]
As discuss in topic #419 the solution "Core.GlobalBreadcrumbRibbon" was changed to new Sample "Core.EmbedJavaScript.HeaderFooter" with old features [Header, Custom Breadcrumb "SharePoint Data + JSON" and Custom Ribbon] + new features [Footer with BreadCrumb and JSON Editor] + fixes [code issues]. 
After validation and approval of Sample "Core.EmbedJavaScript.HeaderFooter" the "Core.GlobalBreadcrumbRibbon" can be deleted by the administrator.

**Comment by VesaJuvonen** [comment]
Sample included in the package. Closing this issue. Thx Andre for your assistance on this.
