### ISSUE TITLE
Sample for search based top navigation

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP#422]
See https://technet.microsoft.com/en-gb/library/dn850367 for inspiration

**Comment by ashuetawah** [comment]
You would like to build a sample from this?

**Comment by jansenbe** [comment]
Yes, we would love to have a simple sample that shows how to search navigation.

**Comment by ashuetawah** [comment]
I am starting on this.

**Comment by jansenbe** [comment]
Awesome. Thanks a lot!

**Comment by ashuetawah** [comment]
Hey Bert, when I hit a query like https://<site>/_api/search/query?querytext='contentClass="STS_Web"+path:https://<site>'&trimduplicates=false&enablefql=false, the primary result table is blank. could you please give a try?

**Comment by VesaJuvonen** [comment]
Closing issue to clear up the roadmap. Sample is still absolutely welcome, if in progress. With technical challenges, would suggest to use the PnP Yammer group at http://aka.ms/OfficeDevPnPYammer.
