### ISSUE TITLE
Rely on ?? operator at call site instead of passing default values to Get-methods  

### ISSUE THREAD

**Issue by ronnieholm** [OfficeDev/PnP#435]
Would pull request https://github.com/OfficeDev/PnP/pull/433 be accepted if I re-submit it based on the dev branch?

The pull request changes the external core interface, but for one of the two methods the behavior isn't working anyway.

**Comment by jansenbe** [comment]
Hi Ronnie,

We've discussed this and we're not going to change this cause it's not really adding additional and complicates things as the web property bag methods are widely used...would not want to update the signature for those.

**Comment by ronnieholm** [comment]
Remember to fix the use of the default value. It's not used by accident in one of the methods.

**Comment by jansenbe** [comment]
Got it...nice catch. I've just updated
