### ISSUE TITLE
CSOM New-SPOTenantSite for On-Prem

### ISSUE THREAD

**Issue by johnnliu** [OfficeDev/PnP#442]
Hi guys.  I've been doing some updates to New-SPOTenantSite for On-Premises, largely following Vesku's post here.

http://blogs.msdn.com/b/vesku/archive/2014/06/09/provisioning-site-collections-using-sp-app-model-in-on-premises-with-just-csom.aspx

On the server:

PS C:\Users\john.liu> $site =get-spsite http://spg-dev-sp2013a
PS C:\Users\john.liu> $site.AdministrationSiteType
TenantAdministration

(looks like step 4 in the blog post is done).

On the laptop, via CSOM + OfficeDevPnP I'm trying both v16 and v15 (with some changes)

My fixes largely involves separating out a bit of New-SPOTenantSite since it's marked as 
 !CLIENTSDKV15 and not available in a v15 build.

PS C:\Users\john.liu> New-SPOTenantSite -title "SC1" -url "http://spg-dev-sp2013a/sites/sc1" -timezone 71
New-SPOTenantSite : Argument SiteUrl must be a tenant administration site.
At line:1 char:1
+ New-SPOTenantSite -title "SC1" -url "http://spg-dev-sp2013a/sites/sc1" -timezone ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SPOTenantSite], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,OfficeDevPnP.PowerShell.Commands.NewTenantSi
   te

A quick look at the ULS says:

02/11/2015 10:25:16.50 	w3wp.exe (0x0E04)                       	0x4208	SharePoint Foundation         	General                       	al5ny	High    	Not a TA site	c77fe89c-d144-e0f4-e2f4-84db3b2b5971
02/11/2015 10:25:16.67 	w3wp.exe (0x0E04)                       	0x4208	SharePoint Foundation         	CSOM                          	ahjq1	High    	Exception occured in scope Microsoft.Online.SharePoint.Dedicated.TenantAdministration.Tenant.ctor. Exception=System.InvalidOperationException: Argument SiteUrl must be a tenant administration site.     at Microsoft.Online.SharePoint.Dedicated.TenantAdministration.TenantAdminHelper.DoSecurityValidation()     at Microsoft.Online.SharePoint.Dedicated.TenantAdministration.TenantServerStub.InvokeConstructor(XmlNodeList xmlargs, ProxyContext proxyContext)     at Microsoft.SharePoint.Client.ServerStub.InvokeConstructorWithMonitoredScope(XmlNodeList args, ProxyContext proxyContext)	c77fe89c-d144-e0f4-e2f4-84db3b2b5971
02/11/2015 10:25:16.67 	w3wp.exe (0x0E04)                       	0x4208	SharePoint Foundation         	CSOM                          	agmjp	High    	Original error: System.InvalidOperationException: Argument SiteUrl must be a tenant administration site.     at Microsoft.Online.SharePoint.Dedicated.TenantAdministration.TenantAdminHelper.DoSecurityValidation()     at Microsoft.Online.SharePoint.Dedicated.TenantAdministration.TenantServerStub.InvokeConstructor(XmlNodeList xmlargs, ProxyContext proxyContext)     at Microsoft.SharePoint.Client.ServerStub.InvokeConstructorWithMonitoredScope(XmlNodeList args, ProxyContext proxyContext)	c77fe89c-d144-e0f4-e2f4-84db3b2b5971
02/11/2015 10:25:16.67 	w3wp.exe (0x0E04)                       	0x4208	SharePoint Portal Server      	Microfeeds                    	aizmo	Medium  	SocialRESTExceptionProcessingHandler.DoServerExceptionProcessing - SharePoint Server Exception [System.InvalidOperationException: Argument SiteUrl must be a tenant administration site.     at Microsoft.Online.SharePoint.Dedicated.TenantAdministration.TenantAdminHelper.DoSecurityValidation()     at Microsoft.Online.SharePoint.Dedicated.TenantAdministration.TenantServerStub.InvokeConstructor(XmlNodeList xmlargs, ProxyContext proxyContext)     at Microsoft.SharePoint.Client.ServerStub.InvokeConstructorWithMonitoredScope(XmlNodeList args, ProxyContext proxyContext)]	c77fe89c-d144-e0f4-e2f4-84db3b2b5971

So it looks like it's a server side thing, and the CSOM call is going through.

And there's where I'm stuck.  Going to have a bit more look this weekend and see if I can get further.  Have you guys tried New-SPOTenantSite for on-prem?

**Comment by jansenbe** [comment]
The New-SPOTenantSite is currently not available for v15. You can however create site collections using CSOM in on-premises as is shown in https://github.com/OfficeDev/PnP/blob/master/Samples/Provisioning.Hybrid.Simple/Provisioning.Hybrid.Simple.OnPrem/SiteRequestService.cs. Hope that helps
