### ISSUE TITLE
Provisioning.SubSiteCreationApp SPAppWebUrl is null

### ISSUE THREAD

**Issue by ssandu** [OfficeDev/PnP#451]
In SharePointContext, CreateSharePointContext httpRequest.QueryString[SharePointContext.SPAppWebUrlKey] is null in a onPrem situation

**Comment by jansenbe** [comment]
Could it be that you've not added an element to the SharePoint app? If there's no SharePoint element (I always added a dummy module) then at install there's no AppWeb created and as such the SPAppweb url will be null. 

I'm closing this issue for now, but don't hesitate to re-open it in case the above was not the problem.

**Comment by getalex** [comment]
is the dummy module an absolute requirement to this date?
