### ISSUE TITLE
Create*FromXML

### ISSUE THREAD

**Issue by Hennadiy** [OfficeDev/PnP#453]
In the FieldAndContentTypeExtensions in method CreateContentTypeFromXML on following line is a bug:
              var contentTypes = from cType in xDocument.Elements(ns + "ContentType") select cType;
after xDocument missed property Root. xDocument.Elements - seek only on first level (on root level), not inside it. And always it returned nothing. The same is in CreateFieldFromXML method.

**Comment by danbudimir** [comment]
Hey Hennaidy, thanks so much for reporting this issue.  We were erroneously using the Elements collection of XDocument when we should have been using Descendants.  The new code has been checked into the dev branch.  Give it a spin and let us know if there were any issues.

**Comment by jansenbe** [comment]
@danbudimir : thanks for taking care of this one :-)

cc: @VesaJuvonen
