### ISSUE TITLE
Enable PowerShell Add-SPOJavaScriptBlock to accept a Site object

### ISSUE THREAD

**Issue by pkskelly** [OfficeDev/PnP#454]
When attempting to provide a script that should be applied at the Site level, think GoogleAnalytics, it would be great to have the PowerShell cmdlet accept a Site object to create the UserCustomAction at the Site level.

**Comment by jansenbe** [comment]
One for @erwinvanhunen :)

**Comment by erwinvanhunen** [comment]
Fixed in PR #456
