### ISSUE TITLE
Package on build in Provisioning.PreventDeleteSites

### ISSUE THREAD

**Issue by paulewert** [OfficeDev/PnP#466]
The Provisioning.PreventDeleteSites.HostWeb project has a dependency on PreventDeleteSites.wsp which is why it is included in the project. The Provisioning.PreventDeleteSites project attempts to provide a copy of the WSP upon build with a PostBuildEvent. However, simply building the project does not package the WSP. To do this--and prevent a copy error on build--add the following to the PropertyGroup node in the Provisioning.PreventDeleteSites.csproj XML right before the PostBuildEvent:
```xml
<IsDebugging>false</IsDebugging>
<PostBuildEventDependsOn>$(PostBuildEventDependsOn);CreatePackage</PostBuildEventDependsOn>
```

**Comment by jansenbe** [comment]
Thanks Paul. We'll make this change

**Comment by jansenbe** [comment]
implemented.
