### ISSUE TITLE
Move batch provisioning from code gallery to PnP repo

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP#476]
Moving this sample from MSDN code gallery to the PnP as a sample with proper name of Provisioning.Cloud.Batch - https://code.msdn.microsoft.com/Provision-sites-in-batches-fcf31bc6

**Comment by VesaJuvonen** [comment]
We need to relocate these for few reasons and better to get them close to other similar samples related on the provisioning.

**Comment by jansenbe** [comment]
Please leave a comment here if you take up the challenge...want to avoid duplicate work.

**Comment by SharePointRadi** [comment]
Just to understand the task, the MSDN code sample and article must be moved to a PnP sample, with the code and description?

The MSDN sample has a Provider-Hosted App with it - it does nothing apart from assist in the deployment procedure. In the console app samples we can easily register the clientId and secret with appregnew & appinv.aspx, so I don't think the web application and SP app is needed at all. I would love some hints on the ground rules/guidance for this kind of stuff. 
If I understand what I need to do - I will go ahead and get it done this weekend :)

**Comment by VesaJuvonen** [comment]
This is just about relocation of the sample from MSDN to PnP side and renaming it correctly and to provide possibly additional context where needed.

**Comment by jansenbe** [comment]
Sample has been moved
