### ISSUE TITLE
Moving Site Provisioning workflow samples to PnP

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP#477]
We need to move PnP related sample from MSDN code gallery to the PnP. There's two closely related samples for this one. 

Site provisioning workflow - https://code.msdn.microsoft.com/SharePoint-2013-Use-e2ee88dd
Site provisioning workflow in app web - https://code.msdn.microsoft.com/SharePoint-2013-Use-2b96feb7

Both should be under Samples and named as Provisioning.Cloud.Workflow and Provisioning.Cloud.Workflow.AppWeb

We need to relocate these for few reasons and better to get them close to other similar samples related on the provisioning.

**Comment by jansenbe** [comment]
Please leave a comment here if you take up the challenge...want to avoid duplicate work.

**Comment by erwinvanhunen** [comment]
I'll take it

**Comment by erwinvanhunen** [comment]
Done through PR #502 . Closing the issue.
