### ISSUE TITLE
Component and Sample taxonomypicker is not in sync

### ISSUE THREAD

**Issue by pbjorklund** [OfficeDev/PnP#480]
Both rely on different versions of the taxonomypicker now.

**Comment by pbjorklund** [comment]
I can probably dig into this this weekend if thats ok with you @jansenbe, I want to see whats up with the child-node creation anyways.

**Comment by pbjorklund** [comment]
Ok, child node creation seems to be solved with #484. Think I'l wait for review of that before I tackle this.

**Comment by jansenbe** [comment]
child node creation is fine now, thanks Patrik. Would be nice if you could also add the updated taxonomy picker to the Core.TaxonomyPicker sample.

**Comment by pbjorklund** [comment]
I did this in #738.

Now that they provide the same feature set (except for the useasrootnode bool, which I don't know why it exists) it's worth thinking about why they exist as both a component and a sample. Just seems confusing.

Did not help that they were both actually built on separate versions of the taxpicker with different implementations in some areas :)

So bringing the old over to the new actually meant brining over some functionality that the component did not support yet, like being able to filter terms.

Thoughts @jansenbe ?
