### ISSUE TITLE
CheckOutFile seems to have a bug if file does not exist

### ISSUE THREAD

**Issue by vverbeek** [OfficeDev/PnP#489]
Hi,

First of all thanks for this awesome library. It saves me writing a whole bunch of code!
I have come across what I think is a bug in the web.CheckOutFile method. Currently the implementation is as follows: 

            File file = web.GetFileByServerRelativeUrl(serverRelativeUrl);
            web.Context.Load(file, x => x.Exists, x => x.CheckOutType);
            web.Context.ExecuteQueryRetry();

            if (file.Exists)
            {
                if (file.CheckOutType == CheckOutType.None)
                {
                    file.CheckOut();
                    web.Context.ExecuteQueryRetry();
                }
            }

Since you are checking if file.Exists I know this is your intention. However, also loading x.CheckOutType straight away causes the first ExecuteQueryRetry() to fail with file not found exception. In order to fix this, you could do something like this:

            File file = web.GetFileByServerRelativeUrl(serverRelativeUrl);
            web.Context.Load(file, x => x.Exists);
            web.Context.ExecuteQueryRetry();

            if (file.Exists)
            {
                web.Context.Load(file, f => f.CheckOutType);
                web.Context.ExecuteQueryRetry();

                if (file.CheckOutType == CheckOutType.None)
                {
                    file.CheckOut();
                    web.Context.ExecuteQueryRetry();
                }
            }

Thanks again and please keep up the great work!
Cheers,
Vincent

**Comment by jansenbe** [comment]
fixed by @erwinvanhunen via #508. Closing this issue.
