### ISSUE TITLE
TaxonomyExtension export with duplicated groups

### ISSUE THREAD

**Issue by cntmnl** [OfficeDev/PnP#494]
I have used the TaxonomyExtension in order to export the whole taxonomy of a tenant. The problem happens when a term has several children. 
In the code below, the subTermPath variable will repeat the group several time because there is a format of groupPath and termsetPath, which is actually already merged with the group in the step before. 

var subTermPath = string.Format("{0}{3}{1}{3}{2}", groupPath, termsetPath, termPath, delimiter);

Moreover in order that the IMPORT will work it is ncessary to add the the line to the termsString collection ONLY once and not like today several times because otherwise the import will fail. 

The import phase looks like also to have a problem: it is possible to pass a stream with several TermSet but actually the code does not reset the variable which implies that if I have more than one TermSet all the terms will added below the first termset. 

I have locally solved both the problem, but am not connected to GitHub; I am available to help you to reproduce the problem and show them how I have fixed it. 

Thanks,

Manuel Conti

**Comment by jansenbe** [comment]
Thanks for letting this know Manuel. Appreciated :)

Will further follow-up with you for the details

**Comment by patrick-rodgers** [comment]
Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.
