### ISSUE TITLE
[TaxonomyExtensions] Default value for path delimiter should be ':'

### ISSUE THREAD

**Issue by biste5** [OfficeDev/PnP#500]
In the TaxonomyExtensions methods, methods that work with term's path, should use ':' (colon) as default delimiter (current is '|') to be more consistent with the constants defined in the server object model.

The value for TaxonomyField.TaxonomyTermPathDelimiter in server object model is ':', and by default when a Term is configured to display its full path you'll obtain in SharePoint a label like
TermSet:Term Parent:Term Child

Methods such as TaxonomyExtensions.GetTaxonomyItemByPath should have ':' as default value for delimiter parameter.
I understand such a change can break some code..

**Comment by erwinvanhunen** [comment]
This will actually break _all_ code that uses that method if they don't specify the delimiter. While I can see your reasoning, it's a pretty heavy change, too heavy almost in my opinion.

**Comment by biste5** [comment]
Hi Erwin,

I'm on the same line as your. Anyway I thought would be eventually better to change this before pushing 1.0, seen it's a breaking code change.
But yes, I don't feel like taking the responsibility of making this change myself :)

**Comment by VesaJuvonen** [comment]
Closed based on the discussion outcome.
