### ISSUE TITLE
404 links in the PowerShell documentation

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP#509]
Moved from received email

"several of the readme links are throwing 401’s on https://github.com/OfficeDev/PnP/tree/master/Solutions/PowerShell.Commands. Looks like it might just be an issue of incorrect capitalization.

For example, Get-SPOSubWebs readme is linked to https://github.com/OfficeDev/PnP/blob/master/Solutions/PowerShell.Commands/Documentation/GetSPOSubwebs.md but it looks like it should be https://github.com/OfficeDev/PnP/blob/master/Solutions/PowerShell.Commands/Documentation/GetSPOSubWebs.md "

**Comment by jansenbe** [comment]
Has been fixed by @erwinvanhunen
