### ISSUE TITLE
Error in Chrome - Uncaught SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by kunalv** [OfficeDev/PnP#518]
I am trying to use the people picker, however i m facing issues. In IE, the UI is not available at all. In chrome, UI is available and i can see the people picker. It also searches for user when we start typing and shows the user below in list but when we click on user we get error in console - "Uncaught SyntaxError: Unexpected token ILLEGAL" which is pointing to first line of default.aspx. 

Appreciate any help.

**Comment by jansenbe** [comment]
Very weird, the people picker does work in IE in Chrome (tested with IE11 and Chrome 41.0.2272.89). Are you testing our sample https://github.com/OfficeDev/PnP/tree/master/Components/Core.PeoplePicker or are you embedding the people picker in your app? If the latter is the case then please validate the correct working in our sample.

**Comment by VesaJuvonen** [comment]
Closed due lack of information and lack of response. If there's any questions like this around the technical implementation, would recommend using PnP Yammer group at http://aka.ms/OfficeDevPnPYammer.
