### ISSUE TITLE
PnP/Components/Core.TaxonomyPicker - Loading term labels based on lcid

### ISSUE THREAD

**Issue by rjesh-git** [OfficeDev/PnP#527]
Thanks for the nice component.
I have a query when I pass the LCID in the options, will it load the term label based on that?  I'm having difficulty in achieving that, added some French labels to the terms in term store. Passing French LCID in the options still seeing the term values in the default language. Any samples or documentation will be helpful!

**Comment by jansenbe** [comment]
This control has to my knowledge not been tested for doing that...think this however can be added. Any takers?
