### ISSUE TITLE
broken link in http://dev.office.com/code-samples

### ISSUE THREAD

**Issue by mauricionr** [OfficeDev/PnP#528]
Hi, i'm trying to access this link https://github.com/OfficeDev/OfficeGraphExplorer
from here http://dev.office.com/code-samples
but 404.

**Comment by jansenbe** [comment]
Are you talking about this one: https://graphexplorer.cloudapp.net/ ? If so I couldn't find the source...can you provide the filter criteria used to obtain the above?

**Comment by mauricionr** [comment]
the filter is "Delve".

**Comment by jansenbe** [comment]
@jthake can you have a look at this.

**Comment by jthake** [comment]
ah it is still a private repo :-( with no code in it. must have slipped off my radar. I believe that is @richdizz repo I created for him ;-)
