### ISSUE TITLE
SiteGovernanceJob exception when adding additional site collections

### ISSUE THREAD

**Issue by LordLaser** [OfficeDev/PnP#533]
There appears to be a threading issue when running the timer job on a more than one site collection that have the same hostname.

For example, in the Program.cs within the Main method I have two AddSite lines:

governanceJob.AddSite("https://cgtestdemo.sharepoint.com/sites/test");
governanceJob.AddSite("https://cgtestdemo.sharepoint.com/sites/contosobeta");

When I run it, I receive an exception within OfficeDevPnP.Core.AuthenticationManager.GetAuthenticationManager(string url) with the exception detail of:

System.ArgumentException was unhandled
  HResult=-2147024809
  Message=An item with the same key has already been added.

I can see that the authenticationManagers dictionary already contains a uri.Host of "cgtestdemo.sharepoint.com" and is trying to add another one. This issue does not occur when this code is wrapped in a lock.

**Comment by jansenbe** [comment]
Thanks for letting us know. Late refactoring resulted in this problem, good that you've found it. Problem has been fixed by using a thread safe dictionary please get the latest from the dev branch.
