### ISSUE TITLE
PublishFileToLevel - The property or field 'ForceCheckout' has not been initialized

### ISSUE THREAD

**Issue by tommykri** [OfficeDev/PnP#536]
When using the extension method "PublishFileToLevel" I always get the error message:

*The property or field 'ForceCheckout' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.*

Looking at the code

```
var checkOutRequired = parentList.ForceCheckout;
try
{
    context.ExecuteQueryRetry();
    publishingRequired = parentList.EnableMinorVersions; // minor versions implies that the file must be published
    approvalRequired = parentList.EnableModeration;
}
catch (ServerException ex)
{
      if (ex.Message != "The object specified does not belong to a list.")
      {
            throw;
      }
}
```

The error occurs in the first line in this example. 
Shouldn't property parentList.ForceCheckout be accessed after it has been loaded with context.ExecuteQueryRetry()?

```
try
{
    context.ExecuteQueryRetry();
    checkOutRequired = parentList.ForceCheckout;
    publishingRequired = parentList.EnableMinorVersions; // minor versions implies that the file must be published
    approvalRequired = parentList.EnableModeration;
}
catch (ServerException ex)
{
      if (ex.Message != "The object specified does not belong to a list.")
      {
            throw;
      }
}
```

**Comment by patrick-rodgers** [comment]
This [appears to be fixed](https://github.com/OfficeDev/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/AppModelExtensions/FileFolderExtensions.cs#L1118) in latest, please let us know if this is still an issue.
