### ISSUE TITLE
Also include the REST API's in the upload file API sample and documentation

### ISSUE THREAD

**Issue by jansenbe** [OfficeDev/PnP#545]
https://github.com/OfficeDev/PnP/tree/dev/Samples/Core.LargeFileUpload only shows and talks about CSOM methods for file upload. Would be good to also explain the REST options for uploading files.

**Comment by CampbellNash** [comment]
Having done a lot of work around the REST i would like to 2nd this!

**Comment by VesaJuvonen** [comment]
Sample included as https://github.com/OfficeDev/PnP/tree/dev/Samples/Core.RestFileUpload. Closing this for now. Thx for Rodrigo Romano on providing this one.
