### ISSUE TITLE
Incorrect Example for Get-SPOContentType

### ISSUE THREAD

**Issue by Dean144** [OfficeDev/PnP#560]
This following explanation is not correct, it looks like it may have been copied from Set-SPOContentType.

PS:> Get-SPOContentType -Identity "Project Document"
This will add an existing content type to a list and sets it as the default content type

**Comment by erwinvanhunen** [comment]
Thanks for reporting this one!

Is was already fixed in the dev branch: https://github.com/OfficeDev/PnP/blob/dev/Solutions/PowerShell.Commands/Documentation/GetSPOContentType.md

Closing the issue
