### ISSUE TITLE
Provisioning.OneDrive Issue?

### ISSUE THREAD

**Issue by Nilking** [OfficeDev/PnP#579]
Hi having a issue with Provisioning.OneDrive runnning it onprem. (It works fine in O365)

I get "An exception of type 'Microsoft.SharePoint.Client.ServerException' occurred in Microsoft.SharePoint.Client.Runtime.dll but was not handled in user code

Additional information: The object id "site:b00bdd23-c764-456f-aa86-865976f1cf48" is invalid." 

when running the following code:

 // Site already exists, let's modify the branding by applying a theme... just as well you could upload
// master page and set that to be shown. Notice that you can also modify this code to change the //branding later and updates would be reflected whenever user visits OneDrive host... or any other //ocation where this
 app part is located. You could place this also to front page of the intranet for ensuring that it's applied.

                    Web rootWeb = personalSite.RootWeb;
                    clientContext.Load(rootWeb);
                    clientContext.ExecuteQuery();

**Comment by antonsmislevics** [comment]
Hi,

I've observed this issue recently with one of my customers. It looks that this exception is thrown when you try to get personalSite.RootWeb in user context. However, it works with app-only context. As a workaround, we've modified the code to: 1) get URL of personal site in user context; 2) switch to app-only context to update the site. Here is the updated else block in OneDriveCustomizer.aspx.cs, that uses app-only authentication.
To make this work, you need to check "Allow the app to make app-only calls to SharePoint." in AppManifest.xml.

    else
    {
        // Site already exists, let's modify the branding by applying a theme... just as well you could upload
        // master page and set that to be shown. Notice that you can also modify this code to change the branding
        // later and updates would be reflected whenever user visits OneDrive host... or any other location where this
        // app part is located. You could place this also to front page of the intranet for ensuring that it's applied.

        // switch to app-only context in order to avoid site id not valid exception in v15
        string personalSiteUrl = personalSite.Url;
        Uri siteUri = new Uri(personalSiteUrl);
        string realm = TokenHelper.GetRealmFromTargetUrl(siteUri);
        string accessToken = TokenHelper.GetAppOnlyAccessToken(TokenHelper.SharePointPrincipal, siteUri.Authority, realm).AccessToken;
        using (var appOnlyCtx = TokenHelper.GetClientContextWithAccessToken(siteUri.ToString(), accessToken))
        {
            Web appOnlyRootWeb = appOnlyCtx.Web;
            appOnlyCtx.Load(appOnlyRootWeb);
            appOnlyCtx.ExecuteQuery();

            //Let's set the theme only if needed, note that you can easily check for example specific version here as well
            if (appOnlyRootWeb.GetPropertyBagValueInt(OneDriveCustomizer.OneDriveMarkerBagID, 0) < 2)
            {
                // Let's first upload the contoso theme to host web, if it does not exist there
                var colorFile = appOnlyRootWeb.UploadThemeFile(HostingEnvironment.MapPath(string.Format("~/{0}", "Resources/Themes/SPC/SPCTheme.spcolor")));
                var backgroundFile = appOnlyRootWeb.UploadThemeFile(HostingEnvironment.MapPath(string.Format("~/{0}", "Resources/Themes/SPC/SPCbg.jpg")));
                appOnlyRootWeb.CreateComposedLookByUrl("SPC", colorFile.ServerRelativeUrl, null, backgroundFile.ServerRelativeUrl, string.Empty);

                // Setting the Contoos theme to host web
                appOnlyRootWeb.SetComposedLookByUrl("SPC");

                // Add additional JS injection with the policy statement to the site
                appOnlyRootWeb.AddJsLink("OneDriveCustomJS", BuildJavaScriptUrl());

                // Let's set the site processed, so that we don't update that all the time. Currently set as "version" 1 of branding
                appOnlyRootWeb.SetPropertyBagValue(OneDriveCustomizer.OneDriveMarkerBagID, 2);
                // Write output if enabled
                WriteDebugInformationIfNeeded(string.Format("OneDrive for Business site existed at {0}. Custom branding applied.", personalSite.Url));
            }
            else
            {
                // Just to output status if enabled in the app part
                WriteDebugInformationIfNeeded(string.Format("OneDrive for Business site existed at {0} and had right branding.", personalSite.Url));
            }
        }

**Comment by Nilking** [comment]
I solved it similar but used GetS2SClientContextWithWindowsIdentity. Works fine
```
 var spContext = SharePointContextProvider.Current.GetSharePointContext(Context);

            using (ClientContext clientContext = spContext.CreateUserClientContextForSPHost())
            {
                // Get user profile
                ProfileLoader loader = Microsoft.SharePoint.Client.UserProfiles.ProfileLoader.GetProfileLoader(clientContext);
                UserProfile profile = loader.GetUserProfile();
                Microsoft.SharePoint.Client.Site personalSite = profile.PersonalSite;

                clientContext.Load(personalSite);
                clientContext.ExecuteQuery();

                // Let's check if the site already exists
                if (personalSite.ServerObjectIsNull.Value)
                {
                    // Let's queue the personal site creation using oob timer job based approach
                    // Using async mode, since end user could go away from browser, you could do this using oob web part as well
                    profile.CreatePersonalSiteEnque(true);
                    clientContext.ExecuteQuery();
                    WriteDebugInformationIfNeeded("OneDrive for Business site was not present, queued for provisioning now.");
                    return;
                }
                else
                {
                    oneDriveUrl = profile.PersonalSite.Url;
                }


            }
            //Strange error here, I could not use the web object from above. Solved it by open a new Clientcontext.

            var hostUri = new Uri(oneDriveUrl);
          
            using (ClientContext clientContext =TokenHelper.GetS2SClientContextWithWindowsIdentity(hostUri, HttpContext.Current.Request.LogonUserIdentity))
            {
                var oneDriveWeb = clientContext.Web;
                clientContext.Load(oneDriveWeb, w => w.AllProperties, w => w.ServerRelativeUrl);
                clientContext.ExecuteQuery();

                if (oneDriveWeb.GetPropertyBagValueInt(Default.OneDriveMarkerBagID, 0) < 1)
                {

                   //Do my stuff 
                    //Set propertybag value 
                    oneDriveWeb.SetPropertyBagValue(Default.OneDriveMarkerBagID, 1);
                    WriteDebugInformationIfNeeded(string.Format("OneDrive for Business site existed at {0}. Custom branding applied.", oneDriveWeb.Url));
                }
                else
                {
                    WriteDebugInformationIfNeeded(string.Format("OneDrive for Business site existed at {0}. Custom branding applied.", oneDriveWeb.Url));
                }
            }
```

**Comment by VesaJuvonen** [comment]
Since issue is solved, will close the issue.
