### ISSUE TITLE
Get-SPOFeature does not get all features

### ISSUE THREAD

**Issue by Dean144** [OfficeDev/PnP#586]
The  get-spofeature does not return all of the features.  For example, the MS providing PublishingInfrastructureFeature is not shown, It is also not returning a custom feature that i have added. I have tried this with the Scope parameter set to both Site and Web. Other MS provided features appear to be missing also

**Comment by erwinvanhunen** [comment]
As Vesa mentioned on Yammer, the get-spofeature only returns activated features. I will update the description of the cmdlet to clarify this.

**Comment by Dean144** [comment]
Would it be possible to modify this cmdlet to include a Status parameter to allow us to get the active or inactive features?

**Comment by erwinvanhunen** [comment]
Unfortunately not. The SharePoint Client Object model only allows to request activated features. E.g. we cannot see inactive features.

**Comment by Dean144** [comment]
How can i submit a request to enhance the SP Client Object model?

**Comment by Dean144** [comment]
I just ran another test, the UI is showing that the SharePoint Server Publishing Infrastructure feature is Active for the Site Collection, but 
PS C:\> Get-SPOFeature -Scope Site | Sort-Object displayname does not show this feature in the listing that is returned

**Comment by Dean144** [comment]
I just found the problem, the feature name is showing as Publishing Site, which is different than what is displayed in the browser UI. It looks like the cmdlet is working after all. Thanks for your help

**Comment by erwinvanhunen** [comment]
Indeed, the browser UI doesn't not always match the internal naming of functionality/features.

To submit a request of an enhancement to the client model you can create an entry or vote for an entry on UserVoice: https://officespdev.uservoice.com/

I will close this issue now.
