### ISSUE TITLE
People Picker JSON with Ajax Update Panel Not working

### ISSUE THREAD

**Issue by RajkumarTCS** [OfficeDev/PnP#613]
People picker (JSON) is not working if we put it inside the Ajax Update Panel. It working fine on first time page load and stopped working once we have partial post back by Ajax call.

we tried rebinding the controls by adding Sys.WebForms.PageRequestManager.getInstance().add_endRequest(pageLoaded); in pageLoad also but it not working. 

Please help us to resolve this issue, or do we have any limitation on using this people picker

**Comment by patrick-rodgers** [comment]
Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.
