### ISSUE TITLE
Core.TaxonomyPickerWeb - taxonomypickercontrol.js - forEach function not compatible in IE8

### ISSUE THREAD

**Issue by asadrefai** [OfficeDev/PnP#614]
Hi,

Its an excellent component. Many thanks for sharing.

While I was using this component in IE8, I came across an error, which is the modal pop up opens up with no terms in tree view.

On my investigation. 

Issue:
Function "buildTermSetTreeLevel" in taxonomypickercontrol.js uses forEach to loop around termList and create a tree structure. IE8 does not support forEach function, hence it causes error.

Resolution: 
There can be many solutions to it but I am mentioning 2. 
1) We can use jQuery.each instead.
Or
2) We can add a prototype for forEach in project initiating scripts allowing use of forEach() in implementations that don't natively support it
prototype code can be referred at below link
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

**Comment by pbjorklund** [comment]
The bigger question is: What browsers to PnP in general support, what versions should the components support?

Switched over from forEach to a plain old for loop in the #621 PR which should resolve the issue.

**Comment by pbjorklund** [comment]
@jansenbe I think this issue can be closed now that #621 is merged

**Comment by jansenbe** [comment]
yes, thx for your great work here!
