### ISSUE TITLE
Enable-spofeature does not work with sandbox solution feature

### ISSUE THREAD

**Issue by Dean144** [OfficeDev/PnP#620]
When i try to use Enable-SPOFeature with a feature that was deployed in a sandbox solution, it does not work. Is this the expected behavior? can the cmdlet be modified to provide this functionality?

This article provides an approach that may be helpful
http://geeks.ms/blogs/lmanez/archive/2013/09/29/office-365-enable-disable-feature-from-power-shell-using-csom.aspx

**Comment by erwinvanhunen** [comment]
Thanks Dean!

I fixed it with PR #631 , it will be there in the next master merge at the end of this month.

/Erwin
