### ISSUE TITLE
'Promoted Links' list cannot be provisioned

### ISSUE THREAD

**Issue by jansenbe** [OfficeDev/PnP#622]
Copied from Yammer:

I've been working with the new scenario 'Provisioning.Framework.Console' and it's a great solution, thanks so much for all your hard work. 

 I have some feedback. When using the 'Save site as template' option in the framework on one of my sites that had a 'Promoted Links' list, this resultated in an XML template with a ListInstance that had the TemplateType=170 . As you can see on https://msdn.microsoft.com/en-us/library/office/microsoft.sh… , 170 is not supported. So when applying this template to a different site, it resulted in a 'Listtemplate invalid' error. However, if you can also specify the FeatureId (ListCreationInformation.TemplateFeatureId) and provide that with the OOTB Feature ID that contains the Promoted Links definition, that would allow the code to run succesfully and the list to be created. So perhaps it would be possible to include this in the XML schema and provisioning engine. Or is there a different way to provision a OOTB Promoted Links list? 

Yammer: https://www.yammer.com/itpronetwork/#/threads/inGroup?type=in_group&feedId=4597220

**Comment by erwinvanhunen** [comment]
This would require a schema change. The actual implement is pretty straightforward. I'll work on this together with @PaoloPia

**Comment by erwinvanhunen** [comment]
TemplateFeatureID is now exposed in the domain model, see PR #629. We're currently working on getting exposed into the schema as well.

**Comment by VesaJuvonen** [comment]
Old old stuff. Should be fine now, so closing the issue.
