### ISSUE TITLE
FileFolderExtensions.GetFile(SPFolder folder, string fileName) fails when folder is root

### ISSUE THREAD

**Issue by n0marko** [OfficeDev/PnP#626]
Exception calling "ExecuteQuery" with "0" argument(s): "Cannot invoke method or retrieve property from null object. Object returned by the following call stack is null. "ListItemAllFields".

var web = folder.ListItemAllFields.ParentList.ParentWeb;
var file = web.GetFileByServerRelativeUrl(fileServerRelativeUrl);
folder.Context.Load(file);
folder.Context.ExecuteQueryRetry();

"folder.ListItemAllFields" is always null for a root folder. 

I discovered this when attempting to provision page layouts into the masterpage gallery using the Web.ProvisionElementFile() method.

**Comment by erwinvanhunen** [comment]
Fixed in #630
