### ISSUE TITLE
Provisioning.Framework does not work on sites without default groups

### ISSUE THREAD

**Issue by scoreman** [OfficeDev/PnP#632]
Ran GetProvisioningTemplate on a HNSC created in an on-premises environment and got an exception in CreateEntities (ObjectSiteSecurity) because there where no default Groups on the site. After creating Groups (using CreateDefaultAssociatedGroups) the error was gone.

**Comment by erwinvanhunen** [comment]
Tack Johan!

I'll look into this.

/Erwin

**Comment by erwinvanhunen** [comment]
Fixed in PR #633. I'll close this issue now. If you find it not working for you, please report back and I'll open it again.

**Comment by scoreman** [comment]
wow! that was fast :-)
