### ISSUE TITLE
Provisioning.Framework only adds users to non-empty groups

### ISSUE THREAD

**Issue by scoreman** [OfficeDev/PnP#635]
AddUserToGroup only adds users if the Group already has at least one member. Code:

            if (group.Users.Any())
            {
                foreach (var user in members)
                {
                    var existingUser = web.EnsureUser(user.Name);
                    group.Users.AddUser(existingUser);
                }
                web.Context.ExecuteQueryRetry();
            }

**Comment by erwinvanhunen** [comment]
Thanks!

Fixed in PR #636 

/Erwin
