### ISSUE TITLE
FileFolderExtensions.PublishFileToLevel(this File file, FileLevel level) exception

### ISSUE THREAD

**Issue by n0marko** [OfficeDev/PnP#637]
"The property or field 'ForceCheckout' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested."

var parentList = file.ListItemAllFields.ParentList;
context.Load(parentList,
                            l => l.EnableMinorVersions,
                            l => l.EnableModeration,
                            l => l.ForceCheckout);
<b>var checkOutRequired = parentList.ForceCheckout;</b>

Move the bold line to after the try/catch.

**Comment by erwinvanhunen** [comment]
Good catch! Fixed and merged in PR #640. I'll close this issue now.
