### ISSUE TITLE
SiteExist method always returning true

### ISSUE THREAD

**Issue by hephie** [OfficeDev/PnP#638]
In the TenantExtensions.cs, the SiteExists method is always returning true.
Basically, you seem to be able to load properties from an unexisting site, the exception catch is never "triggered"... :-(
I'm using the nuget package for Online O365.

 //Get the site name
var properties = tenant.GetSitePropertiesByUrl(siteFullUrl, false);
tenant.Context.Load(properties);
tenant.Context.ExecuteQueryRetry();

// Will cause an exception if site URL is not there. Not optimal, but the way it works.
return true;

**Comment by erwinvanhunen** [comment]
I'm not able to reproduce this issue. I just ran the SiteExistsTest we have in the test project (OfficeDevPnP.Core.Tests.AppModelExtensions.TenantExtensions.cs) and that one fails to find a non existing site collection and it returns false for me.

**Comment by VesaJuvonen** [comment]
Closed due unable to repro. We can re-open if needed.
