### ISSUE TITLE
Provisioning.Framework GetTemplate and default Connector

### ISSUE THREAD

**Issue by scoreman** [OfficeDev/PnP#639]
Not sure it this is by design but when reading template from disk like this:

            XMLFileSystemTemplateProvider provider = new XMLFileSystemTemplateProvider(@"c:\temp\pnpprovisioningdemo", "");           
            template = provider.GetTemplate("template.xml");

The Connector for the template is created using default constructor. This results in an error when trying to read asset streams from disk. If I add the below after GetTemplate the code executes as expected:

            template.Connector = provider.Connector;

**Comment by erwinvanhunen** [comment]
Yes, the template is not automatically hooked up to the connector of the provider you're using to read the template. This was a design decision, to allow for instance to store the template in a different location from the assets. 

I'll bring this issue up in the next meeting, as I think it makes sense to default to the same connector that is used to retrieve the template, allowing you to optionally override it if required.

**Comment by VesaJuvonen** [comment]
Fixed in the latest releases, so closing the issue. Connector can be updated on fly without this issue.
