### ISSUE TITLE
Provisioning Engine does not work on Azure Web Jobs

### ISSUE THREAD

**Issue by levalencia** [OfficeDev/PnP#641]
I have a template, I only need 2 activate 3 features and add one property bag.

<?xml version="1.0" encoding="utf-8" ?>
<pnp:SharePointProvisioningTemplate ID="xx" Version="1.0"
  xmlns:pnp="http://schemas.dev.office.com/PnP/2015/03/ProvisioningSchema"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <pnp:PropertyBagEntries>
    <pnp:PropertyBagEntry Key="xx.PlantillasIntranet.Version" Value ="1" />
  </pnp:PropertyBagEntries>
  <pnp:Features>
    <pnp:SiteFeatures>
      <pnp:Feature ID="f6924d36-2fa8-4f0b-b16d-06b7250180fa" />
      
    </pnp:SiteFeatures>
    <pnp:WebFeatures>
      <pnp:Feature ID="41e1d4bf-b1a2-47f7-ab80-d5d6cbba3092" />
      
      <pnp:Feature ID="94c94ca6-b32f-4da9-a9e3-1f3d343d7ecb" />
      
    </pnp:WebFeatures>
  </pnp:Features>
</pnp:SharePointProvisioningTemplate>
and my code is like this:

public static void ActivateFeatures(ClientContext cc)
{
    XMLFileSystemTemplateProvider provider = new XMLFileSystemTemplateProvider(AppDomain.CurrentDomain.BaseDirectory+ "/Template/","");
    string templateName = "features.xml";

    // Load the template
    ProvisioningTemplate p2 = provider.GetTemplate(templateName);

    // Apply template to existing site
    try
    {
        cc.Web.ApplyProvisioningTemplate(p2);
    }
    catch (Exception ex)
    {
        System.Diagnostics.Trace.TraceError(ex.Message);
    }
    System.Diagnostics.Trace.TraceInformation("App installed finished");
}
}

On debug mode I can see that the template has been loaded on p2, because I can see the variables correctly set for property bags and features

however on the ApplyProvisionTemplate line I get this:

A first chance exception of type 'Microsoft.SharePoint.Client.CollectionNotInitializedException' occurred in Microsoft.SharePoint.Client.Runtime.dll

This worked perfectly fine on an azure web site (Provider hosted app)

void SimpleJob_TimerJobRun(object sender, TimerJobRunEventArgs e)
        {
            Console.WriteLine("Timer Job Started");
            try
            {

                bool containsKey = e.WebClientContext.Web.PropertyBagContainsKey("Vinculosc.PlantillasIntranet.Aprovisionado");
                if (containsKey) //El sitio es un sitio al que se le ha instalado la app de Intranet
                {
                    e.WebClientContext.Load(e.WebClientContext.Web, p => p.Title);
                    e.WebClientContext.ExecuteQueryRetry();
                    Console.WriteLine("Site contains key Vinculosc.PlantillasIntranet.Aprovisionado {0}", e.Url);

                    string aprovisionado = e.WebClientContext.Web.GetPropertyBagValueString("Vinculosc.PlantillasIntranet.Aprovisionado", "0");
                    if (aprovisionado == "0")
                    {
                        Stopwatch stopWatch = new Stopwatch();
                        stopWatch.Start();
                        Helpers.ActivateFeatures(e.WebClientContext);
                        string libraryName = "ConfiguracionColores";

bug also documented here
http://sharepoint.stackexchange.com/questions/137862/how-to-use-the-pnp-provisioning-engine-with-an-azure-job

**Comment by erwinvanhunen** [comment]
Did you try running the timerjob on your local machine? Like in a simple console application?

**Comment by VesaJuvonen** [comment]
Problem is following line in your code:

XMLFileSystemTemplateProvider provider = new XMLFileSystemTemplateProvider(AppDomain.CurrentDomain.BaseDirectory+ "/Template/","");

This is assuming that you are have the xml files relatively to the location where the WebJob is running, which is actually not the case. When you deploy assets (this case xml files) to template folder, those will be deployed under the Azure WebSite, but the actually WebJob execution location is different.

You should be able to get this fixed just by updating the above line as follows. 
XMLFileSystemTemplateProvider provider = new XMLFileSystemTemplateProvider(Path.Combine(Environment.GetEnvironmentVariable("WEBROOT_PATH"), "Template"),"");

This is just due the way WebJobs are executed in the PAAS platform and this is not really that widely documented. It's also really difficult to spot, since you do not see this difference when you do on-premises debugging. You could resolve this only with WebJob debugging, which could be painful with the network latencies.

Please confirm that this was the case, so that we can close this.

**Comment by levalencia** [comment]
Hello Vesa, Erwin

I am testing this, when testing on premises, this line is null:
Environment.GetEnvironmentVariable("WEBROOT_PATH")

What would you recommend me? I need that the same piece of code works when I debug locally and works when I put it on Azure webjobs too

**Comment by levalencia** [comment]
BTW:

Maybe I am missing something here, but this line works perfect locally:
XMLFileSystemTemplateProvider(AppDomain.CurrentDomain.BaseDirectory+ "/Template/","");

When I check in the debugger the p2 variable it has loaded the property bag and the feature properties.

The error, is when I call the Apply WebTemplate method.

'Microsoft.SharePoint.Client.CollectionNotInitializedException' occurred in Microsoft.SharePoint.Client.Runtime.dll


I really doubt that CollectionNotInitializedException has something to do with the path,that generally happens when you try to use a variable/property/collection when you havent explicitly specified in the Load Method, however as I am calling the ProvisioningEngine using the e.WebContext then I dont have control of how it was loaded/built from inside the timer job.

Your input is really appreciated, I can share the project if needed and I could available via yammer chat too.

**Comment by erwinvanhunen** [comment]
are you deploying to a standard team site? and if so, are you deploying to the same site when testing in both environments (e.g. local dev machine and azure webjob)

The current master branch has an issue when you try to deploy to a site that has one or more associated groups missing (e.g. Associated Visitors Group, Associated Members Group or Associated Owners Group)

**Comment by levalencia** [comment]
Its a developer site

-----Original Message-----

**Comment by levalencia** [comment]
You can close this issue, for some reason in another project it didnt work, but when tested in a new clean console app the code works perfectly.

And for the record the webroot environment is totally different 

  public static void ActivateFeatures(ClientContext cc)
        {
            Console.WriteLine("Current path AppDomain.CurrentDomain.BaseDirectory :" + AppDomain.CurrentDomain.BaseDirectory);
            Console.WriteLine("Current pathath.Combine(Environment.GetEnvironmentVariable(WEBROOT_PATH) :" + Path.Combine(Environment.GetEnvironmentVariable("WEBROOT_PATH")));

             XMLFileSystemTemplateProvider provider = new XMLFileSystemTemplateProvider(AppDomain.CurrentDomain.BaseDirectory + "\\Template\\", "");
            //XMLFileSystemTemplateProvider provider = new XMLFileSystemTemplateProvider(Path.Combine(Environment.GetEnvironmentVariable("WEBROOT_PATH"), "Template"), ""); 
            string templateName = "features.xml";

            // Load the template
            ProvisioningTemplate p2 = provider.GetTemplate(templateName);

            // Apply template to existing site
            try
            {
                Console.WriteLine("Aprovisionamiento iniciadp");
                cc.Web.ApplyProvisioningTemplate(p2);
                Console.WriteLine("Aprovisionamiento terminado");
            }
            catch (Exception ex)
            {
                Console.Write("Aprovisionamiento fallo:" + ex.Message);
            }
            System.Diagnostics.Trace.TraceInformation("App installed finished");
        }


What I see in the azure console 

[04/13/2015 20:20:32 > f217cd: INFO] Current path AppDomain.CurrentDomain.BaseDirectory :D:\local\Temp\jobs\continuous\ConsoleApp\gcxsipgb.pyy\
[04/13/2015 20:20:32 > f217cd: INFO] Current pathath.Combine(Environment.GetEnvironmentVariable(WEBROOT_PATH) :D:\home\site\wwwroot

as you can see both paths are totally different and it worked with the first one.

**Comment by levalencia** [comment]
maybe this would be interesting to be added to the documentation.

http://stackoverflow.com/questions/29612155/how-to-get-current-path-on-azure-webjob-console-app
