### ISSUE TITLE
Import-SPOTaxonomy issue with Sharepoint OnPremise

### ISSUE THREAD

**Issue by miguelillo** [OfficeDev/PnP#642]
I've been trying to import a taxonomy file into my Sharepoin OnPremise and it won't work. The exception message is:

Import-SPOTaxonomy : Value cannot be null.
Parameter name: path

It happens when importing a file and when inputing the "Terms" parameter directly. The strange thing is that using the same script (with the v16 assemblies) against Office365, it works fine.

Thanks.

**Comment by erwinvanhunen** [comment]
Is it possible that you provide with a (snippet) of the taxonomy file you're trying to import?

**Comment by miguelillo** [comment]
Hi Erwin


$urlSite = Read-Host -Prompt "Insert Url"
Connect-SPOnline -Url $urlSite -Credentials (Get-Credential) -Verbose
$ctx = Get-SPOContext
Import-SPOTaxonomy -Terms 'TerminosPowerShell|Locations|StockHolm'


This Throws this exception:


Import-SPOTaxonomy : Value cannot be null.
Parameter name: path2
At line:1 char:1
+ Import-SPOTaxonomy -Terms 'TerminosPowerShell|Locations|StockHolm'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Import-SPOTaxonomy], ArgumentNullException
    + FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.ImportTaxonomy



The connection and the context are obtained correctly.

**Comment by erwinvanhunen** [comment]
It likely has to do with the fact that the default site collection termstore is null in your on-premises farm. In O365 it's set by default, but that's not always the case in on-prem farms.

See  https://mohitvash.wordpress.com/2014/02/18/sharepoint-defaultsitecollectiontermstore-is-null/

Please confirm if that solves your issue, if so I will close this item.

**Comment by miguelillo** [comment]
I've tried and the default site collection termstore is not null, this is how I tested it:


            SPSite sitio = new SPSite("http://MySite/");
                   

            var session = new TaxonomySession(sitio);

            var termStore = session.DefaultSiteCollectionTermStore;

            if (termStore != null)
            {
                Console.WriteLine(termStore.Id);
                Console.ReadKey();
            }

That returns the correct Guid of the default site collection termsore, but the cmdlet still won't work

**Comment by erwinvanhunen** [comment]
Okay, interesting. I will do some tests on my own farms.

**Comment by erwinvanhunen** [comment]
I found the issue. It seems that you're using a newer version of the cmdlets for your on-prem farm than you used for O365, as the latest builds introduces this issue. I will fix it in the dev branch.

**Comment by erwinvanhunen** [comment]
A temporary workaround is to put your terms in a file and specify that file with the Path parameter

**Comment by miguelillo** [comment]
Ok many thanks, and good job on the project.


Working in it....

**Comment by erwinvanhunen** [comment]
Fixed in PR #643. Closing this issue now.

**Comment by miguelillo** [comment]
Checked! It Works Fine!
