### ISSUE TITLE
Context not properly initialized in Web.SiteSearch()

### ISSUE THREAD

**Issue by eBerdnA** [OfficeDev/PnP#655]
I'm just trying to use the example from scenario 'Core.SiteEnumeration' with my own on-premises installation. For this I'm simply using the scenario as it is only with the data for my environment.

So basically I'm doing this:
```csharp
ClientContext cc = new AuthenticationManager().GetNetworkCredentialAuthenticatedContext("http://dev", "myFarmAdmin", GetPassWord(), "myDomain");
List<SiteEntity> sites = cc.Web.SiteSearch();
```
Just with these two lines you should be able to reproduce the problem as it occurs in `Microsoft.SharePoint.Client.WebExtensions.SiteSearch(this Web web, string keywordQueryValue, bool trimDublicates = true)` when trying to create a new KeywordQuery with the following line of code:

```csharp
KeywordQuery keywordQuery = new KeywordQuery(web.Context);
```

Am I doing something wrong or is this kind of a bug?

**Comment by patrick-rodgers** [comment]
Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.
