### ISSUE TITLE
PageExtensions.AddPublishingPage Issue

### ISSUE THREAD

**Issue by narulasrinivas** [OfficeDev/PnP#657]
Hi,

When I try to add page at sitecollection level. It is throwing error. When I checked the code, looks like current version does not support the creation of page at sitecollection.

PageExtensions.AddPublishingPage(clientContext.Site.RootWeb, "Home", "PageLayoutName");

Below is the error: 
An unhandled exception of type 'Microsoft.SharePoint.Client.ServerException' occurred in Microsoft.SharePoint.Client.Runtime.dll

Additional information: The file "Pages/Home1.aspx" is not checked out.

Please advise on this.

Regards,
N.Srinivas

**Comment by erwinvanhunen** [comment]
Hi,

A couple of things: as we're using extension methods, you can write your line above as:

clientContext.Site.RootWeb.AddPublishingPage("Home","PageLayoutName");

I checked the code and we're not checking if the file actually needs to be checked in at all. E.g. we just call checkin on it. That's a bug and should be fixed.

**Comment by erwinvanhunen** [comment]
I fixed it in PR #667 which means that the fix will be available in the next master merge /nuget package release for May.

As a workaround you could either decide to enable the requirement to checkout files on your library or, if you need this functionality sooner than the upcoming release, copy the code of the specific function  out of the dev branch and add the extension method code to your own application. The method starts here: https://github.com/OfficeDev/PnP/blob/dev/OfficeDevPnP.Core/OfficeDevPnP.Core/AppModelExtensions/PageExtensions.cs#L957

Alternatively (but not recommended) you can decide to use the core library from the dev branch. You'll have to build the assembly yourself then.

**Comment by narulasrinivas** [comment]
Thanks for the response and Nice that this change comes in next version.
I already wrote that line to complete my requirement.

**Comment by erwinvanhunen** [comment]
Great! I'll close the issue then.
