### ISSUE TITLE
Idea of model refactoring in provisioning framework

### ISSUE THREAD

**Issue by pbjorklund** [OfficeDev/PnP#661]
I created PR #660 to illustrate how we could start to change the design of the Models directory (and probably other parts of the solution as well).

Cloning the description here:

I was looking around the Model dir of the provisioning framework and got to thinking about how the code could be updated to be a bit more generic.

So I played around with the ComposedLook and PropertyBagEntry models to get an idea of what I was thinking about.

1. Came up with the idea of using attributes to mark properties that the hashcode should be built on and then having a generic implementation read the property value of attributes marked with ```[HashCodeIdentifier]```

2. Added a refactoring of the equality comparers into separate Equator classes. Could also build attributes that work in a similar way as nr 1.

None of the changes actually change how the models are used from a consumer perspective. But I was wondering why we don't use any IoC container to set things up. Then we could add and remove formatters, comparers and whatnot there.

Thought I would check with everyone if there is any value in starting to move in this direction.

(Also, a PR might not be the best way to show a design-idea, but I could not think about a neater way)

**Comment by VesaJuvonen** [comment]
Based on discussions during spring, closing this one. Let's continue the discussion as needed for the new structures and thanks again on the input around the engine.
