### ISSUE TITLE
MMSSync - Custom Sort - No Functionality / Issue

### ISSUE THREAD

**Issue by narulasrinivas** [OfficeDev/PnP#668]
Hi All,

When I tried to sync the changes between the TermSets in different environments. Custom Sorting is not getting synced in destination as the source one.

Do I need to pass any other parameter(s) or Is there any limitation to sync custom sort between termsets in different tenants?

Please advise on this.

Regards,
N.Srinivas

**Comment by patrick-rodgers** [comment]
Thank you for the feedback - currently the team has no plans to implement this feature, however would invite community work in this area to help resolve.
