### ISSUE TITLE
GetProvisioningTemplate not working onprem

### ISSUE THREAD

**Issue by Djemel** [OfficeDev/PnP#671]
Hi,
I tried using the GetProvisioningTemplate from the Provisioning Framework on SP2013 onprem and got following error message: "The property or field 'AlternateCssUrl' has not been initialized".
I dig into this and there are lots of issues even skipping this AlternateCssUrl.

I looked at the code and commented
template.ComposedLook.AlternateCSS = Tokenize(web.AlternateCssUrl, web.Url);
and
template.ComposedLook.SiteLogo = Tokenize(web.SiteLogoUrl, web.Url);

Unfortunately a new exception is raised in IsUsingOfficeTheme
with The object id "ThemeInfo-{8525ee72-58dd-4103-b980-2123387ef92e}" is invalid.
and I am stuck here.

Any way to workaround this and make this great feature onprem compatible ?

Thank you

**Comment by jcmartinez23** [comment]
Exactly the same that happens to me. I've tried that workaround and the output is the same.

**Comment by KristofVanGils** [comment]
Same issue here

**Comment by VesaJuvonen** [comment]
Pull request associated to this merged and we have been testing engine now properly in the on-premises. If there's still issues, please let us know the version (Cu) and open a new issue. thx.
