### ISSUE TITLE
GetSiteCollections in OnPremise

### ISSUE THREAD

**Issue by nanddeepn** [OfficeDev/PnP#695]
Hello,
The method GetSiteCollections works fine in O365 to get all the site collections. Is there any API support to get the site collections in OnPremise?
I tried setting the Tenant context to Mock admin and central admin, but no luck.

**Comment by jansenbe** [comment]
The only API to this remotely is using Search. The timerjob framework does a search with filter contentclass:"STS_Site"...tenant admin API code in v15 only works and is supported for the creation and deletion of site collections

**Comment by nanddeepn** [comment]
Thank you Bert!
