### ISSUE TITLE
site provisioning engine enhancement

### ISSUE THREAD

**Issue by jansenbe** [OfficeDev/PnP#696]
See https://www.yammer.com/itpronetwork/#/Threads/show?threadId=527258941 

from Marat Bakirov:
Hi. We are trying to add our page of the specific content type we need with the new XML provisioning engine. However seems that there is no way to specify a property bag into the file element.

**Comment by erwinvanhunen** [comment]
This has been implemented now in the dev branch.

**Comment by maratbakirov** [comment]
There is another issue with the current implementation.

The file properties has to be set BEFORE the web parts processing. Now they are set up AFTER web parts. 

The reason for this is one of the properties is a page layout. And this page layout defines the web part zones. If we do not setup a page layout first, then we cannot add the web parts!

**Comment by maratbakirov** [comment]
created a new issue 
https://github.com/OfficeDev/PnP/issues/773

**Comment by VesaJuvonen** [comment]
Fixed based on issue status, so closing this one as well.
