### ISSUE TITLE
issue with provision engine and 15-version assemblies

### ISSUE THREAD

**Issue by scoreman** [OfficeDev/PnP#697]
Linq (Select-statements) in ObjectContentType/ObjectField/ObjectListInstance fail because IEnumerable.GetEnumerator is not implemented in 15-version of Microsoft.SharePoint.Client.ClientQueryable<T>.

16-version:

		IEnumerator IEnumerable.GetEnumerator()
		{
			return this.Provider.Execute<IEnumerable>(this.Expression).GetEnumerator();
		}

15-version:

		IEnumerator IEnumerable.GetEnumerator()
		{
			throw new NotSupportedException();
		}

**Comment by dmdj** [comment]
I have encountered same or similar issue.  For existingFields in ObjectField.cs I have added AsEnumerable to get around this:

   var existingFieldIds = existingFields.AsEnumerable().Select(l => l.Id).ToList();

**Comment by VesaJuvonen** [comment]
15 version of the Nuget should now work without any issues for the on-premises as well, so this is considered as fixed. Please re-open if needed.
