### ISSUE TITLE
PeoplePicker is not working with ADFS for provider hosted app

### ISSUE THREAD

**Issue by raghuureddy** [OfficeDev/PnP#706]
PeoplePicker control works fine with the windows authentiaction for provider hosted app but when the application is configured to use ADFS it's not working.

The below steps have been followed to setup ADFS & application works fine with ADFS except the people picker control.
http://www.wictorwilen.se/sharepoint-2013-with-saml-claims-and-sharepoint-hosted-apps

Can you please help me on this? Let me know if you need more details on the issue?

Thanks,
Raghu

**Comment by quannum76** [comment]
Hi,
We had a similar problem with the people picker and ADFS when we were testing out our SharePoint installation. Kirk Evans came to the rescue, http://blogs.msdn.com/b/kaevans/archive/2013/05/26/fixing-people-picker-for-saml-claims-users-using-ldap.aspx.

We have been using the LDAP / AD Claims Provider (http://ldapcp.codeplex.com/) mentioned in his post and now the people picker is working as expected. 

HTH

**Comment by raghuureddy** [comment]
Hi, thanks for the reply.

Looks like we need to deploy a wsp on Sharepoint farm & also it addresses only the sharepoint people picker.

We are developing apps on on-premise but in near future we are migrating these provider apps to cloud. So wsp deployment is not allowed on our farms.

Thanks,
Raghu

**Comment by quannum76** [comment]
You mention that your apps are provider hosted app. Are they MVC or SharePoint hosted apps?

**Comment by raghuureddy** [comment]
MVC SharePoint Provider Hosted App...

This People Control for PHA has been used with Windows auth.
https://github.com/OfficeDev/PnP/tree/master/Components/Core.PeoplePicker
