### ISSUE TITLE
Content type bindings are not resolved with applying a template to a subweb.

### ISSUE THREAD

**Issue by erwinvanhunen** [OfficeDev/PnP#733]
From: https://www.yammer.com/itpronetwork/#/threads/show?threadId=528732346&messageId=529245804

I have the following scenario, one of my apps needs to be installed on a subsite not on the site collection level, the provisioning engine works perfectly fine on the site collection level. It creates the site columns, content types and then the lists.

However I know this app will be installed on a subsite, so I started testing.
I gave Full Site Collection Permissions and I refactored the code to provision 2 templates.

One that will create the site columns and content types and another one that will create the list instances.

The first one works perfectly fine, when I check site colums and content types are there. However the second one apparently the ContentType Bindings is not working the lists are created but the content types are not bound.

http://screencast.com/t/miElt3jrD

http://screencast.com/t/4OJzNV3mGs

**Comment by levalencia** [comment]
thanks for creating this issue, please let me know if I can be of any help for testing it once its fixed on the dev branch.

**Comment by erwinvanhunen** [comment]
Fixed in PR #735 and available in the dev branch now.

**Comment by levalencia** [comment]
I just tested it from the  dev branch and it works perfect.

For the sake of documentation, if someone reads this in the future the code is this:

            XMLFileSystemTemplateProvider provider = new XMLFileSystemTemplateProvider(System.Web.Hosting.HostingEnvironment.MapPath("~/Template/"), "");
                    string templateName = "features.xml";
                    string templateName2 = "ContentTypes.xml";
                    string templateName3 = "template.xml";

                    try
                    {
                        ProvisioningTemplate p1 = provider.GetTemplate(templateName);
                        cc.Web.ApplyProvisioningTemplate(p1);
                        ProvisioningTemplate p2 = provider.GetTemplate(templateName2);
                        cc.Site.RootWeb.ApplyProvisioningTemplate(p2);
                        ProvisioningTemplate p3 = provider.GetTemplate(templateName3);
                        cc.Web.ApplyProvisioningTemplate(p3);

                    }


First xml activates features on the subsite
Second XML creates site fields and content types on the site collection level (root web)
Third xml creates lists instances and views on the subsite.

**Comment by levalencia** [comment]
You can mark it as fixed/closed.

**Comment by erwinvanhunen** [comment]
Thanks!
