### ISSUE TITLE
Problem with Nuget Package when updating

### ISSUE THREAD

**Issue by levalencia** [OfficeDev/PnP#744]
Today I updated the nuget package from Office PnP with latest version, from 14/04. After doing the update it also updates the Sharepoint.Client dlls with the latest versions, however on my web project it deleted 3 important files:

1. SharepointContext
2. TokenHelper
3. SharepointContextFilter

No big deal I could restore them from source control.

**Comment by patrick-rodgers** [comment]
Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.
