### ISSUE TITLE
Please allo updates to existing content types, at least an ability to add new fields

### ISSUE THREAD

**Issue by maratbakirov** [OfficeDev/PnP#747]
So a simple scenario. In a new version of our solution that contains fields and content types we need to add a few additional fields. Old version has been deployed and widely used. 

So if we do not go the pure code way, we have two options. One is and "old" (I call it old as it existsed before the new one) PnP provisioning engine which can be found in CreateContentTypeFromXMLFile method in \PnP-dev\OfficeDevPnP.Core\OfficeDevPnP.Core\AppModelExtensions\FieldAndContentTypeExtensions.cs.

Another is the new one.

So far both engine do not handle the case of the existing content type.
An old one just ignores the content type if it is already there.

The new one 
https://github.com/OfficeDev/PnP/blob/dev/OfficeDevPnP.Core/…

has an "overwrite" option. However the overwrite option just tried to delete the existing content type which is not possible if it used already....

What I would think would be good to have is to "update" the existing content type, go through all field references and add them if they are missing.

**Comment by erwinvanhunen** [comment]
This functionality is on the road map (https://github.com/OfficeDev/PnP/wiki/Roadmap: Updating of existing artifacts / deltas)
