### ISSUE TITLE
XMLTemplateProvider does not copy file Connector parameters

### ISSUE THREAD

**Issue by maratbakirov** [OfficeDev/PnP#748]
PnP-dev\OfficeDevPnP.Core\OfficeDevPnP.Core\Framework\Provisioning\Providers\Xml\XMLTemplateProvider.cs

has the following lines 

            // Get the XML document from a File Stream
            Stream stream = this.Connector.GetFileStream(uri);

            // And convert it into a ProvisioningTemplate
            ProvisioningTemplate provisioningTemplate = formatter.ToProvisioningTemplate(stream, identifier);

in my case this calls 

DH.iNhouse\PnP-dev\OfficeDevPnP.Core\OfficeDevPnP.Core\Framework\Provisioning\Providers\Xml\XMLPnPSchemaV201505Formatter.cs

ToProvisioningTemplate

this function DOES NOT copy the connector properties such as CONNECTION_STRING and CONTAINER

this leads to the fact that when the underlying engine tries to read the file from 
XML, the full path is lost

here is my xml and code 
            var templateProvider = new XMLFileSystemTemplateProvider(
            String.Format(@"{0}",
            AppDomain.CurrentDomain.BaseDirectory), "MasterPages & PageLayouts");
            var template = templateProvider.GetTemplate("elements.xml");
            cc.Web.ApplyProvisioningTemplate(template);

elements.xml:

<?xml version="1.0" encoding="utf-8" ?>
<ProvisioningTemplate ID="ID1" Version="1.0" xmlns="http://schemas.dev.office.com/PnP/2015/05/ProvisioningSchema">
  <Files>
    <File Src="Snapshot.aspx" Folder="_catalogs/masterpage" Overwrite="true">
      <Properties>
        <Property Key="ContentTypeId" Value="0x01010007FF3E057FA8AB4AA42FCB67B453FFC100E214EEE741181F4E9F7ACC43278EE811" />
        <Property Key="Title" Value="Snapshot" />
        <Property Key="PublishingAssociatedContentType" Value=";#Snapshot;#0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF3900242457EFB8B24247815D688C526CD44D0069ABD5868FD7DA41AA3839984418DC0101;#" />
      </Properties>
    </File>
  </Files>
  </ProvisioningTemplate>

I have a folder MasterPages & PageLayouts that contains 2 files
Snapshot.aspx
and elements.xml

the only way to make it work now is to add 
            System.IO.Directory.SetCurrentDirectory(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "MasterPages & PageLayouts"));

before applying the template

**Comment by erwinvanhunen** [comment]
Check out this snippet which comes from the Apply-SPOProvisioningTemplate powershell cmdlet:

````
   XMLTemplateProvider provider = new XMLFileSystemTemplateProvider(fileInfo.DirectoryName, "");

            var provisioningTemplate = provider.GetTemplate(fileInfo.Name);

            if (provisioningTemplate != null)
            {
                var fileSystemConnector = new FileSystemConnector(fileInfo.DirectoryName, "");
                provisioningTemplate.Connector = fileSystemConnector;´
           ....
````

The provisioningTemplate has a connector property that allows you to specify where the files mentioned in your template will come from, allowing scenarios where the (XML) template is located in a different place from the actual files you're deploying.

**Comment by maratbakirov** [comment]
well yes but as XMLTemplateProvider also has a connector with parameters I really do not get why they are not copied to the provisioning template...

thanks anyhow
