### ISSUE TITLE
Rating settings support for pnp core

### ISSUE THREAD

**Issue by jansenbe** [OfficeDev/PnP#753]
https://github.com/OfficeDev/PnP/tree/dev/Samples/Core.ListRatingSettings shows how to enable ratings for a library in a publishing web. This is excellent IP to be included in the PnP core library.

**Comment by akhileshnirapure** [comment]
Hi @jansenbe 

I've added support to Core. created a pull request from the same.

Added required Test

Thanks
Akhilesh Nirapure

**Comment by VesaJuvonen** [comment]
Thanks for the work @akhileshnirapure. Sorry for late follow up.
