### ISSUE TITLE
Bug when creating site columns as Integers with the provisioning Engine

### ISSUE THREAD

**Issue by levalencia** [OfficeDev/PnP#756]
I havent tested this when using plain CSOM, I tested this with the provisioning engine.

I created some site columns, date, text and integer.  The text and date fields are there
http://screencast.com/t/qWSRjKwZJI0F

but the Integer site column is not there
http://screencast.com/t/DJfPqLgnz

If I go to the content type, unbelievable the column is there, but its not coming from site columns, I can not even click on it
http://screencast.com/t/H5DbmvbsuJa

**Comment by levalencia** [comment]
I tested this with the nuget package and also with the Core Project from the dev branch, same behavior on both.

**Comment by VesaJuvonen** [comment]
I'm really sorry for the delay on getting any response around this. Just tested and verified this with newest builds and it's all good, like expected.
