### ISSUE TITLE
Token Helper is inconsistent

### ISSUE THREAD

**Issue by maratbakirov** [OfficeDev/PnP#763]
PnP-dev\OfficeDevPnP.Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\TokenDefinitions\SiteCollectionToken.cs

and

PnP-dev\OfficeDevPnP.Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\TokenDefinitions\SiteToken.cs

for the root site (i.e. http://xx.sharepoint.com/) they return "/"

for not root site they return the path without ending slash

http://xx.sharepoint.com/sites/aa) 
the value will be "/sites/aa"

this leads to inconsistency when using the tokens

for example we do not know if we shoud write ~sitecollection_catalogs/masterpage/layout.aspx

or 
for example we do not know if we shoud write ~sitecollection/_catalogs/masterpage/layout.aspx

I suggest to make it consistent and always not to have the trainling slash (it is easier to add the slash than to remove it so it is better to have a token without the trailing slash)

**Comment by maratbakirov** [comment]
Suggested change 
https://github.com/OfficeDev/PnP/commit/fa957bd341177214286adbef02c68b6b5cd41005

I am not issuing a pull request as it will suggest my other changes to issues 762 and 747

https://github.com/OfficeDev/PnP/issues/762
https://github.com/OfficeDev/PnP/issues/747

and I am not sure if 762 is going to be approved.

**Comment by erwinvanhunen** [comment]
That's a very valid argument you're making! I'll fix it.

**Comment by erwinvanhunen** [comment]
Merged with PR #766

**Comment by erwinvanhunen** [comment]
I will close this issue now

**Comment by maratbakirov** [comment]
I have posted a pull request as well:) might be conflitcts. thanks for quick fix though!
