### ISSUE TITLE
New provisioning engine : put properties before web parts

### ISSUE THREAD

**Issue by maratbakirov** [OfficeDev/PnP#773]
PnP-dev\OfficeDevPnP.Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectFiles.cs

The file properties has to be set BEFORE the web parts processing. Now they are set up AFTER web parts. 

The reason for this is one of the properties is a page layout. And this page layout defines the web part zones. If we do not setup a page layout first, then we cannot add the web parts!

related issue and discussion

https://github.com/OfficeDev/PnP/issues/696

https://www.yammer.com/itpronetwork/#/Threads/show?threadId=527258941

**Comment by erwinvanhunen** [comment]
Thank you for this suggestion! Fixed in PR #774
