### ISSUE TITLE
XML structure for Content Types in Export seems incorrect

### ISSUE THREAD

**Issue by dmdj** [OfficeDev/PnP#777]
When exporting a template is this the intended XML structure?  In Apply Template it seems to only be looking inside the FieldRefs element but the export has Field elements outside of FieldRefs.  Was the intent to mimic standard SP declarative schema (https://msdn.microsoft.com/en-us/library/office/aa544268.aspx)?  If not, is the schema document separately somewhere?

![contenttypesample](https://cloud.githubusercontent.com/assets/11617909/7431527/fc39ea7e-efe4-11e4-9273-be3babf29569.png)

**Comment by erwinvanhunen** [comment]
In the V201503 version of the schema we do not generate the XML for the content type but we take the server generated XML for the content type. As we only support FieldRefs in our engine we only parse the FieldRefs part of the content type XML.

In the V201505 version of the schema and engine (which is currently in the dev branch) we handle the content types differently and as a result the fields collection will not show up in the generated XML anymore.

**Comment by dmdj** [comment]
I'm confused about the schema support.  Is the May release *also* supporting the "community driven" (http://github.com/OfficeDev/PnP-Provisioning-Schema/0.5) schema?  I'm only seeing references to the PnP/2015/05/ProvisioningSchema namespace in the current master.

**Comment by dmdj** [comment]
I think I may have read May release notes too literally!  The phrase "Support for" threw me off.  To avoid confusion, I think the first bullet should read:

• *Incorporated updates* from the community driven provisioning schema. The previous version of the PnP schema is still supported...
