### ISSUE TITLE
Support for pre-Dec 2014 CU

### ISSUE THREAD

**Issue by dmdj** [OfficeDev/PnP#778]
For customers not on (or willing to move to) recent CUs would it be possible to support *not* setting MajorVersionLimit and MajorWithMinorVersionsLimit.  Even though EnableVersioning might be false in template an error is thrown regarding set_MajorVersionLimit method not being available.

Ref: http://blogs.msdn.com/b/vesku/archive/2014/12/15/latest-api-updates-in-client-side-object-model-dec-2014-cu-for-sp2013.aspx

**Comment by martindr** [comment]
I second this request. Provisioning is breaking in our client's environment and there's no way they'll accelerate their CU deployment just for this.

The engine should fail gracefully when encountering non-supported attributes. Is that reasonable to achieve?

**Comment by VesaJuvonen** [comment]
Due resourcing constraints, we'll need to select a supported CU version for the on-premises. This means that we simply cannot implement different supports for the CUs even request does make sense. If you need to use the engine with older version, we would suggest to pull down the code, change the code and compile the engine again for your usage.
