### ISSUE TITLE
Making out of the box Seattle master responsive

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/PnP#779]
Making out of the box Seattle master responsive won't work the way it was presented to Pattern and Practices. Despite the fact that Heather Solomon created a responsive CSS that contains media queries she edited the master page at the end of her blog post to make it work.
Without a proper meta viewport definition the media queries won't have any effect on any device. This week I was curious about this thing an thought about how to get the viewport without editing the master pages. I found a solution by using the SEO Meta tag definitions and it worked perfectly. I tested it on various Emulators on MacOS X, iPad, iPhone and Google Chrome. Even the settings pages rendered the view port tag correctly.
I documented this in the following blog post: http://www.n8d.at/blog/how-to-add-viewport-meta-without-editing-the-master-page/

**Comment by patrick-rodgers** [comment]
Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.
