### ISSUE TITLE
AddJsLink API adds file twice on MDS enabled sites

### ISSUE THREAD

**Issue by nanddeepn** [OfficeDev/PnP#795]
Hello,
Tested on team site (which is MDS enabled by default).

Steps to reproduce:
1. Use API JavaScriptExtensions.AddJsLink to add any JS file to team site.
2. Navigate to team site home page from IE. 
3. Use F12 to open developer tools. Click "Script" tab. See your file is in dropdown.
4. Now click Site action -> Site contents (partially loads because of MDS)
5. Again use F12 to see that file is included twice.

![js_twice](https://cloud.githubusercontent.com/assets/8310319/7537066/6c01e4ec-f59e-11e4-8803-e926848b73cf.png)

**Comment by nanddeepn** [comment]
Thanks ZeBobo5

**Comment by jansenbe** [comment]
Zebobo5's fix has been merged...closing this issue
