### ISSUE TITLE
Extend the apps for sharepoint Project Template

### ISSUE THREAD

**Issue by ministainer** [OfficeDev/PnP#798]
Create additional Project Item templates for the "apps for sharepoint" project template which contains (or create additional project template)
1-List Instance (Hostweb) includes List Data
2-Site Column (HostWeb)
3-Content Type (HostWeb)
4-Custom User Action (HostWeb) to inject JS file
5-Module Element (hostWeb)

add a way to enforce  the order of the provisioning execution steps for example we might need to upload js file then add custom user action.

**Comment by levalencia** [comment]
I believe that this is not a feature of Office PnP, thats a native feature of Visual Studio. (Visual Studio UserVoice)

**Comment by patrick-rodgers** [comment]
This would need to come from the product team, please feel free to add it on [http://visualstudio.uservoice.com](http://visualstudio.uservoice.com).
