### ISSUE TITLE
Synonyms not working in Taxonomy picker

### ISSUE THREAD

**Issue by krusk** [OfficeDev/PnP#799]
I have terms that have synonyms, but when I type in the form field, these don't work as they would in a normal managed metadata field. Is there an option to get these working?

**Comment by pbjorklund** [comment]
Interesting question. I can investigate this

**Comment by krusk** [comment]
Thank you 

Sent from myMail for iOS


Monday, May 11, 2015, 1:27 PM -0400 from Patrik Björklund  <notifications@github.com>:

**Comment by krusk** [comment]
As an update, I plan on using this in a SharePoint page, not a SharePoint App. I test both scenarios (embedding in a SharePoint page, and use in a SharePoint App) and received the same behavior.

**Comment by krusk** [comment]
Any updates on this issue? Any information I can provide to assist?

**Comment by pbjorklund** [comment]
Have not started looking into this yet.

**Comment by krusk** [comment]
Thanks for the update.

**Comment by VesaJuvonen** [comment]
Right now the taxonomy control does not support this, but absolutely interesting question and all contributions from the community side around this are more than welcome.
