### ISSUE TITLE
Core.PeoplePicker- Not working

### ISSUE THREAD

**Issue by Arullingam** [OfficeDev/PnP#802]
In my provider hosted app, I used the Core.PeoplePicker control. It is working fine in dev environment ( visual studio & sharpeoint installed in the same server ). However when it is moved to QA environment (web application is hosted in a remote IIS server), It throws an error "Error Performing user search". When I applied error log, I found the error: "There is no trusted URL configured for app deployment". 

Sometimes, it throws the error "Sorry, we had some trouble accessing your site".
![pp](https://cloud.githubusercontent.com/assets/12426393/7607745/8b04adf2-f981-11e4-9359-0bb6f4128719.png)

Please let me know If I miss any configuration.

**Comment by phillipharding** [comment]
Usually when I see this kind of error with the people picker, its some kind of issue concerning the use of the cross domain library and the appWeb...is the SPAppWebUrl passed to the remote web app correct, has the QA env has been configured correctly for Apps?

**Comment by Arullingam** [comment]
Thanks for your reply...
Yes, SPAppWebURL is correct. Can you please give some idea/article how to trouble shoot whether QA configuration is correct or not. In my testing all other functionalities are working as expected apart from people picker"

**Comment by getalex** [comment]
for me the SPAppWeb query string is not being passed. it's missing from the url. what's a good way to ensure this will be passed into the app?

**Comment by patrick-rodgers** [comment]
This is likely due to the sites being in different security zones in the browser.

Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.

**Comment by sangeetkumar1988** [comment]
Can you please open this issue again. As I am facing the same issue, as discussed above. Unable to find any solution.
Can anyone helpe me out withi this issue??

**Comment by HariprasathPremraj** [comment]
Is there any fix available for this issue. This issue still exists.

![image](https://cloud.githubusercontent.com/assets/23640245/21995153/572670e0-dc49-11e6-8757-085762a4e0c0.png)
