### ISSUE TITLE
Input box within Taxonomy Picker not functioning

### ISSUE THREAD

**Issue by krusk** [OfficeDev/PnP#803]
The input box to the right of the select within the taxonomy picker does not appear to be working. I can't enter by typing and if I select a term, the term populates, but I can't remove it. It appears as a real thin input box until you select an item instead of allowing entry or manipulation. The line of code from debugging is this:

    <div class="cam-taxpicker-dialog-selection-editor" restrictpastetotext="true" allowmultilines="false"></div>

**Comment by krusk** [comment]
As an update, I plan on using this in a SharePoint page, not a SharePoint App. I tested both scenarios (embedding in a SharePoint page, and use in a SharePoint App) and received the same behavior.

**Comment by patrick-rodgers** [comment]
Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.
