### ISSUE TITLE
Get-SPOField -Identity "Test" should throw exception or return $null if field doesnt exist

### ISSUE THREAD

**Issue by kolliparachandra** [OfficeDev/PnP#807]
Get-SPOField -Identity "Test" if it threw an exception would help in upgrading existing field lists and adding new fields.
Scenario: If we have a set of fields in a project in release 1 and if we added 2 new fields in release 2, we can use same script if we can check and create fields that don't exist yet or newly created. Its fine if it returns null also

Pseudo code: 
try
{
Get-SPOField -Identity "Test"
}
catch(EXCEPTION)
{
create field as it doesn't exist
}
or

$test = Get-SPOField -Identity "Test"
if($test -ne $null)
{
do something
}
else
{
}

**Comment by erwinvanhunen** [comment]
You can handle this scenario as follows in PowerShell:

try
{
    Get-SPOField -Identity "Test" -ErrorAction Stop
} catch 
{
    Write-Host "Field does not exist"
}

**Comment by kolliparachandra** [comment]
Hi Erwin,
 Thanks so much works perfect
 Regards
 Chandrashekar Kollipara

**Comment by erwinvanhunen** [comment]
Closing this issue

**Comment by westerdaled** [comment]
Yep, this has just helped me too as I auto generate a load of survey mulitchoice questions. Out of interest why does Add-PnPField -List $listName -InternalName $question -DisplayName $question seem to happily allow me to had fields to a list with the same static name.?
