### ISSUE TITLE
Feature request - Can we have Exists-SPOField and Exists-SPOContentType 

### ISSUE THREAD

**Issue by kolliparachandra** [OfficeDev/PnP#808]
Can we have Exists-SPOField and Exists-SPOContentType , these would check for field exists with given identity at given scope or Content type exists with given identity at given scope.

**Comment by erwinvanhunen** [comment]
When it comes to Content Types:

```
$ct = Get-SPOContentType -Identity "Test Content Type"
if($ct -eq $null)
{
     Add-SPOContenType etc. etc.
}
```

When it comes to Fields:

```
$f =  Get-SPOField -Identity "Test Field" -ErrorAction SilentlyContinue
if($f -eq $null)
{
     Add-SPOField etc.
}
```

**Comment by kolliparachandra** [comment]
Hi Erwin,
Thanks so much works perfect
Regards
Chandrashekar Kollipara

**Comment by erwinvanhunen** [comment]
Closing this issue.
