### ISSUE TITLE
Responsive Taxonomy Picker

### ISSUE THREAD

**Issue by krusk** [OfficeDev/PnP#809]
Is there a method to make the client side taxonomy picker responsive using bootstrap or other CSS means? When I open it on a mobile device and use the taxonomy picker, it is opening to much larger than the screen/not usable.

**Comment by pbjorklund** [comment]
There is not. And CSS really isn't my favorite thing. So feel free to work on writing CSS to make it responsive :)

**Comment by krusk** [comment]
Thanks for the update. I will start by looking at the classes created by the picker and see what I can target via CSS.

**Comment by patrick-rodgers** [comment]
Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.
