### ISSUE TITLE
Feature request - Can we have Add-SPOHtmlPublishingPageLayout take destination path?

### ISSUE THREAD

**Issue by kolliparachandra** [OfficeDev/PnP#822]
Can we have Add-SPOHtmlPublishingPageLayout take destination path, currently it is set to just deploy straight in root folder, in code there is destination path but not exposed as parameter on the powershell command?
Thanks 
Chandrashekar Kollipara

**Comment by erwinvanhunen** [comment]
This has been implemented through PR #828 now. It will be part of the master merge at the end of this month. Closing this issue.
