### ISSUE TITLE
Add-SPOFile when used to deploy DisplayTemplate only generates .js file if deployed to root

### ISSUE THREAD

**Issue by kolliparachandra** [OfficeDev/PnP#823]
Add-SPOFile when used to deploy DisplayTemplate only generates .js file if deployed to root, if we deploy to sub folder it doesn't generate the corresponding .js file.
If we use following powershell script it generates .js files fine
$stream= New-Object System.IO.FileStream($filePath,[IO.FileMode]::Open) 

        $fileCreationObject = New-Object Microsoft.SharePoint.Client.FileCreationInformation
        $fileCreationObject.ContentStream=$stream
        $fileCreationObject.Url=$fileUrl
        $fileCreationObject.Overwrite=$true

        $uploadedfile = $folder.Files.Add($fileCreationObject)

        $context.Load($uploadedfile)
        $context.ExecuteQuery()

Thanks
Chandrashekar Kollipara

**Comment by erwinvanhunen** [comment]
This is the code we use in the core library 

```
            var newFileInfo = new FileCreationInformation()
            {
                ContentStream = stream,
                Url = fileName,
                Overwrite = overwriteIfExists
            };

            Log.Debug(Constants.LOGGING_SOURCE, "Creating file info with Url '{0}'", newFileInfo.Url);
            var file = folder.Files.Add(newFileInfo);
            folder.Context.Load(file);
            folder.Context.ExecuteQueryRetry();
```

That code is called from the cmdlet, and it's not fundamentally different from your code snippet above...

**Comment by erwinvanhunen** [comment]
I just updated the Add-SPOFile cmdlet in the dev branch.

When using it like this:
```
Add-SPOFile -Path displaytemplate.html -Folder "_catalogs/masterpage/display template/test" 
```
it uploads the file (and it creates the folder if not there yet, that's a change I did to cmdlet), and it also creates a corresponding JS file for me... E.g. I can't reproduce your issue?
