### ISSUE TITLE
Remove-SPOUserFromGroup : User not found

### ISSUE THREAD

**Issue by tomgron** [OfficeDev/PnP#827]
I get an error of "User not found" (but in finnish) while trying to remove user from group by login name.

Here's the error in full (some information removed for privacy reasons)

PS C:\> Remove-SPOUserFromGroup -LoginName "tommi.gronlund@xxxxxxx.onmicrosoft.com" -GroupName "Testityötila 1 - Jäsenet"
Remove-SPOUserFromGroup : Käyttäjää ei löydy.
At line:1 char:1
+ Remove-SPOUserFromGroup -LoginName "tommi.gronlund@xxxxxxx.onmicrosoft ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Remove-SPOUserFromGroup], ServerException
    + FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.Principals.RemoveUserFromGroup
 

PS C:\> $users

Display Name                     Login Name                                              Groups                                                
------------                     ----------                                              ------                                                
Kaikki paitsi ulkoiset käyttäjät spo-grid-all-users/fc29145a-eaa5-4b45-8cba-30b45cf0918e {Testityötila 1 - Jäsenet}                            
Tommi Grönlund                   tommi.gronlund@xxxxxxx.onmicrosoft.com                  {Testityötila 1 - Jäsenet, Testityötila 1 - Omistajat}

**Comment by erwinvanhunen** [comment]
The login name parameter takes a value in the shape of the actual login name of the user. While when the user authenticates it usually uses the email address, the actual login name is most of the time something in the shape of "i:0#.f|membership|testuser@xxxx.onmicrosoft.com". I understand this is not very intuitive, and I will see if I can modify the cmdlet to work also with a normal email address instead of the full claims identity.

**Comment by erwinvanhunen** [comment]
I updated the cmdlet (see PR #836). The updated cmdlet will be available in the next master merge at the end of this month. Please provide feedback if the solution I provided above (e.g. with i:0#.f|membership|testuser@xxxx.onmicrosoft.com) solves your issue. If so I will close this issue. As from the next master release you will be able to use email addresses to remove users from groups too.

**Comment by tomgron** [comment]
Sorry for the delayed answer but actually this was a special group that required rolemanager to be added to login. I used this :

**c:0-.f|rolemanager|spo-grid-all-users/fc29145a-eaa5-4b45-8cba-30b45cf0918e** to solve the issue. Maybe this should be an option in this command to choose which user source is used to remove user from the group ? I guess at least there is windows and maybe some other special notations as well ?
