### ISSUE TITLE
GetProvisioningTemplate on-prem - missing method exception

### ISSUE THREAD

**Issue by PlanetWilson** [OfficeDev/PnP#844]
Tried to run against a publishing site and got a missing method exception looking for:-

Microsoft.SharePoint.Client.List.get_MajorVersionLimit()

or is this a dependency on the v16 DLLs even though on-prem?

**Comment by VesaJuvonen** [comment]
Thx Mark for this. This is clearly a bug related on the on-prem CSOM capabilities where that method is not available. We'll work on updating that part away from the code when executed with the on-premises setup.

**Comment by martindr** [comment]
This has been raised before: https://github.com/OfficeDev/PnP/issues/778.

Furthermore, I think it's been fixed in the source. After experiencing the error from within the PowerShell commandlets, I browsed the code in OfficeDevPnP.Core and it looked like the code had been addressed, with conditionals such as the following. 

```list.MaxVersionLimit = item.IsObjectPropertyInstantiated("MajorVersionLimit") ? item.MajorVersionLimit : 0;```

So I rebuilt the PowerShell project locally and no longer experience the errors.

**Comment by PlanetWilson** [comment]
Okay I was using latest nuget package. I referenced the 16 DLLs instead and got an array type mismatch error instead. I'll grab latest code, compile and try that.

**Comment by Duber** [comment]
Any news on this ? I'm getting this error on my on-prem sharepoint 2013 both with lastest pnp nuget and compiling source myself.

**Comment by erwinvanhunen** [comment]
According to Vesa's blog post: http://blogs.msdn.com/b/vesku/archive/2014/12/15/latest-api-updates-in-client-side-object-model-dec-2014-cu-for-sp2013.aspx, the MajorVersionLimit property is available in the December 2014 CU for SharePoint. It however requires that your server is also up to that level (or newer).

**Comment by Duber** [comment]
Thanks for your fast reply Erwin. So, for those with an older version this simply won't work ? no plans on patching this ?

**Comment by erwinvanhunen** [comment]
It's virtually impossible for us (unfortunately) to support all the different releases of CSOM, due to limited resources in the team. We have a 'baseline' supported version level that is the April 2015 CU for on-premises.
