### ISSUE TITLE
 "The page you selected contains a list that does not exist"  caused by Enterprise Keywords field

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP#858]
Hi 
I have been testing the provisioning engine with a site with Taxonomy fields in it.  I have hit a problem when the provisioning engine gets to "Enterprise Keywords" fields. I get a failure "The page you selected contains a list that does not exist".
I enclose the FieldXML (Comment edited by Erwin to format XML for easier reference):

```xml
<?xml version="1.0" encoding="utf-8"?>
<Field Type="TaxonomyFieldTypeMulti"
    DisplayName="Enterprise Keywords"
    StaticName="TaxKeyword"
    Name="TaxKeyword"
    ID="{23f27201-bee3-471e-b2e7-b64fd8b7ca38}"
    ShowInViewForms="TRUE"
    DefaultListField="TRUE"
    List="{ff5708af-fba2-405e-9029-3a6368cb9b47}"
    WebId="59eea740-3e15-49b8-942e-78f890024f6f"
    Required="FALSE"
    Hidden="FALSE"
    CanToggleHidden="TRUE"
    ShowField="Term1033"
    SourceID="{3622aa4b-4974-413e-9a7d-78b9904991d5}"
    Mult="TRUE"
    Sortable="FALSE"
    Group="Enterprise Keywords Group"
    Description="Enterprise Keywords are shared with other users and applications to allow for ease of search and filtering, as well as metadata consistency and reuse"
    AllowDeletion="TRUE"
    Sealed="TRUE"
    Version="5">
  <Customization>
    <ArrayOfProperty>
      <Property>
        <Name>SspId</Name>
        <Value xmlns:q1="http://www.w3.org/2001/XMLSchema" p4:type="q1:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">1203c05f-9d23-4eba-8d26-7b5e1fbd495e</Value>
      </Property>
      <Property>
        <Name>GroupId</Name>
      </Property>
      <Property>
        <Name>TermSetId</Name>
        <Value xmlns:q2="http://www.w3.org/2001/XMLSchema" p4:type="q2:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance\">00000000-0000-0000-0000-000000000000</Value>
      </Property>
      <Property>
        <Name>AnchorId</Name>
        <Value xmlns:q3="http://www.w3.org/2001/XMLSchema" p4:type="q3:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">00000000-0000-0000-0000-000000000000</Value>
      </Property>
      <Property>
        <Name>UserCreated</Name>
        <Value xmlns:q4="http://www.w3.org/2001/XMLSchema" p4:type="q4:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">false</Value>
      </Property>
      <Property>
        <Name>Open</Name>
        <Value xmlns:q5="http://www.w3.org/2001/XMLSchema" p4:type="q5:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">true</Value>
      </Property>
      <Property>
        <Name>TextField</Name>
        <Value xmlns:q6="http://www.w3.org/2001/XMLSchema" p4:type="q6:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">{1390a86a-23da-45f0-8efe-ef36edadfb39}</Value>
      </Property>
      <Property>
        <Name>IsPathRendered</Name>
        <Value xmlns:q7="http://www.w3.org/2001/XMLSchema\" p4:type="q7:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance

\">false</Value>
      </Property>
      <Property>
        <Name>IsKeyword</Name>
        <Value xmlns:q8="http://www.w3.org/2001/XMLSchema" p4:type="q8:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">true</Value>
      </Property>
      <Property>
        <Name>TargetTemplate</Name>
      </Property>
      <Property>
        <Name>CreateValuesInEditForm</Name>
        <Value xmlns:q9="http://www.w3.org/2001/XMLSchema" p4:type="q9:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">false</Value>
      </Property>
      <Property>
        <Name>FilterAssemblyStrongName</Name>
      </Property>
      <Property>
        <Name>FilterClassName</Name>
      </Property>
      <Property>
        <Name>FilterMethodName</Name>
      </Property>
      <Property>
        <Name>FilterJavascriptProperty</Name>
      </Property>
    </ArrayOfProperty>
  </Customization>
</Field>
```
Regards

Nigel

**Comment by erwinvanhunen** [comment]
What is the type of site you're exporting from? Team site? (STS#0)

**Comment by NPrice99** [comment]
It has a Pages folder and it also has a Look and Feel section of site settings which includes Page Layouts and Site Templates so it would be a publishing site.

**Comment by erwinvanhunen** [comment]
Doesn't have to be. It can be a team site with the publishing features activated. 

You can figure the template out like this:

```powershell
connect-sponline -url https://yoursite
$ctx = Get-SPOContext
$w = Get-SPOWeb
$template = $w.WebTemplate
$ctx.Load($w,$template)
$ctx.ExecuteQuery()
$w.Template
$w.Configuration
```

The last two values will list the template, e.g. STS#0

**Comment by NPrice99** [comment]
Hi Erwin, this is an on-premises site. Regards Nigel

**Comment by NPrice99** [comment]
The Site Template is "BLANKINTERNET#0"

**Comment by erwinvanhunen** [comment]
Ah. there we have it :-) We currently filter out built-in fields and other built-in functionality for a limited set of templates (STS#0, BLOG#0 and COMMUNITY#0 for O365 sites and STS#0 for on-prem). The engine checks for the site template and based on that it will parse the internal base template in the engine. Every artifact that is present in the basetemplate will be filtered out of the generated template before it's returned from the engine.

There are several ways to solve this:

1. If you use the PowerShell cmdlets, modify the template before you apply it and physically remove the reference to the TaxKeywords field from the SiteFields collection in the template first.
2. If you use code to generate the template, you can programmatically remove the TaxKeywords field from the generated template object.

**Comment by NPrice99** [comment]
Thanks Erwin - I am currently using code to generate the template, template = web.GetProvisioningTemplate (pcti) where pcti is the ProvisioningTemplateCreationInformation.  So I just need to wook out how to remove TaxKeyWords field from the generated template object.

**Comment by erwinvanhunen** [comment]
that's pretty simple:

```c#
int fieldIndex = template.SiteFields.FindIndex(f => f.SchemaXml.IndexOf(BuiltInFieldId._Author.ToString("D"), StringComparison.InvariantCultureIgnoreCase) > -1);
if (fieldIndex > -1)
{
     template.SiteFields.RemoveAt(fieldIndex);
}     
```

**Comment by NPrice99** [comment]
Hi Erwin I can confirm that the code above fixes this problem and that I have now hit the problem described in Issue #859. Regards Nigel

**Comment by erwinvanhunen** [comment]
For your information: we now added base templates for many more site types, including BLANKINTERNET#0. That would mean that when you use either the current dev branch or the master release which we will do later this week your taxkeywords field will be automatically filtered out by the engine.

**Comment by erwinvanhunen** [comment]
I will close this issue now.
