### ISSUE TITLE
The formula refers to a column that does not exist

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP#859]
Hi
I have created my XML file with the schema in it from my site that I want to replicate.  When I try a create a replica of this site I get this error "The formula refers to a column that does not exist.  Check the formula for spelling mistakes or change the non-existing column to an existing column.

Stack Trace - 
Microsoft.SharePoint.Client.ServerException was unhandled
  HResult=-2146233088
  Message=The formula refers to a column that does not exist.  Check the formula for spelling mistakes or change the non-existing column to an existing column.
  Source=Microsoft.SharePoint.Client.Runtime
  ServerErrorCode=-2130575273
  ServerErrorTraceCorrelationId=60320b9d-c8d8-80cb-513e-225e91e28781
  ServerErrorTypeName=Microsoft.SharePoint.SPException
  ServerStackTrace=""
  StackTrace:
       at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
       at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
       at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
       at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
       at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
       at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
       at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in c:\Users\admpric1384\Documents\GitHub\PnP-dev\OfficeDevPnP.Core\OfficeDevPnP.Core\AppModelExtensions\ClientContextExtensions.cs:line 54
       at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in c:\Users\admpric1384\Documents\GitHub\PnP-dev\OfficeDevPnP.Core\OfficeDevPnP.Core\AppModelExtensions\ClientContextExtensions.cs:line 36
       at Microsoft.SharePoint.Client.FieldAndContentTypeExtensions.FieldExistsById(List list, Guid fieldId) in c:\Users\admpric1384\Documents\GitHub\PnP-dev\OfficeDevPnP.Core\OfficeDevPnP.Core\AppModelExtensions\FieldAndContentTypeExtensions.cs:line 450
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template) in c:\Users\admpric1384\Documents\GitHub\PnP-dev\OfficeDevPnP.Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectListInstance.cs:line 175
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo) in c:\Users\admpric1384\Documents\GitHub\PnP-dev\OfficeDevPnP.Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 120
       at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation) in c:\Users\admpric1384\Documents\GitHub\PnP-dev\OfficeDevPnP.Core\OfficeDevPnP.Core\AppModelExtensions\WebExtensions.cs:line 1025
       at PnP.Program.Main(String[] args) in c:\Users\admpric1384\Documents\Visual Studio 2013\Projects\PnP\PnP\Program.cs:line 107
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

Regards

Nigel

**Comment by NPrice99** [comment]
Here is the XML for all of the calculated fields in the Site -

 
 
            <Field Type="Calculated" DisplayName="A-Z" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="Text" ReadOnly="TRUE" ID="{8f658a69-6f98-4711-81e5-1d8b3c70239e}" SourceID="{354c4d63-a6d5-41b7-b371-72068e7ebc99}" StaticName="A_x002d_Z" Name="A_x002d_Z" ColName="sql_variant1" RowOrdinal="0" Version="1">
              <Formula>=LEFT(Title,1)</Formula>
              <FieldRefs>
                <FieldRef Name="Title" />
              </FieldRefs>
            </Field>
 
            <Field Type="Calculated" DisplayName="Filed By" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="Text" Group="DH Columns" ID="{83bfcba5-de2d-4ee0-a241-2a2d63b3a6cf}" SourceID="{3622aa4b-4974-413e-9a7d-78b9904991d5}" StaticName="Filed_x0020_By" Name="Filed_x0020_By" Required="FALSE" ReadOnly="TRUE" Version="114" ColName="sql_variant2" RowOrdinal="0">
              <Formula>=_Author</Formula>
              <FieldRefs>
                <FieldRef Name="Author" ID="{1df5e554-ec7e-46a6-901d-d85a3881cb18}" />
              </FieldRefs>
              <FieldRefs>
                <FieldRef Name="_Author" />
              </FieldRefs>
            </Field>
            <Field Type="Calculated" DisplayName="Modified-Date" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="DateTime" ReadOnly="TRUE" Group="DH Columns" ID="{0d67b66e-43d1-415a-b814-830fd8257d8e}" SourceID="{3622aa4b-4974-413e-9a7d-78b9904991d5}" StaticName="Modified-Date" Name="Modified_x002d_Date" Required="FALSE" ColName="sql_variant3" RowOrdinal="0">
              <Formula>=Modified</Formula>
              <FieldRefs>
                <FieldRef Name="Modified" />
              </FieldRefs>
            </Field>
 
 
          <Field Type="Calculated" DisplayName="Filed By" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="Text" Group="DH Columns" ID="{83bfcba5-de2d-4ee0-a241-2a2d63b3a6cf}" SourceID="{3622aa4b-4974-413e-9a7d-78b9904991d5}" StaticName="Filed_x0020_By" Name="Filed_x0020_By" Required="FALSE" ReadOnly="TRUE" Version="114" ColName="sql_variant2" RowOrdinal="0">
              <Formula>=_Author</Formula>
              <FieldRefs>
                <FieldRef Name="Author" ID="{1df5e554-ec7e-46a6-901d-d85a3881cb18}" />
              </FieldRefs>
              <FieldRefs>
                <FieldRef Name="_Author" />
              </FieldRefs>
            </Field>
            <Field Type="Calculated" DisplayName="Modified-Date" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="DateTime" ReadOnly="TRUE" Group="DH Columns" ID="{0d67b66e-43d1-415a-b814-830fd8257d8e}" SourceID="{3622aa4b-4974-413e-9a7d-78b9904991d5}" StaticName="Modified-Date" Name="Modified_x002d_Date" Required="FALSE" ColName="sql_variant3" RowOrdinal="0">
              <Formula>=Modified</Formula>
              <FieldRefs>
                <FieldRef Name="Modified" />
              </FieldRefs>
            </Field>
 
            <Field Type="Calculated" DisplayName="A-Z" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="Text" ReadOnly="TRUE" ID="{8f658a69-6f98-4711-81e5-1d8b3c70239e}" SourceID="{354c4d63-a6d5-41b7-b371-72068e7ebc99}" StaticName="A_x002d_Z" Name="A_x002d_Z" ColName="sql_variant1" RowOrdinal="0" Version="1">
              <Formula>=LEFT(Title,1)</Formula>
              <FieldRefs>
                <FieldRef Name="Title" />
              </FieldRefs>
            </Field>
 
           <Field Type="Calculated" DisplayName="Filed By" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="Text" Group="DH Columns" ID="{83bfcba5-de2d-4ee0-a241-2a2d63b3a6cf}" SourceID="{3622aa4b-4974-413e-9a7d-78b9904991d5}" StaticName="Filed_x0020_By" Name="Filed_x0020_By" Required="FALSE" ReadOnly="TRUE" Version="114" ColName="sql_variant2" RowOrdinal="0">
              <Formula>=_Author</Formula>
              <FieldRefs>
                <FieldRef Name="Author" ID="{1df5e554-ec7e-46a6-901d-d85a3881cb18}" />
              </FieldRefs>
              <FieldRefs>
                <FieldRef Name="_Author" />
              </FieldRefs>
            </Field>
            <Field Type="Calculated" DisplayName="Modified-Date" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="DateTime" ReadOnly="TRUE" Group="DH Columns" ID="{0d67b66e-43d1-415a-b814-830fd8257d8e}" SourceID="{3622aa4b-4974-413e-9a7d-78b9904991d5}" StaticName="Modified-Date" Name="Modified_x002d_Date" Required="FALSE" ColName="sql_variant3" RowOrdinal="0">
              <Formula>=Modified</Formula>
              <FieldRefs>
                <FieldRef Name="Modified" />
              </FieldRefs>
            </Field>
           <Field Type="Calculated" Name="Checkmark" ID="{ebf1c037-47eb-4355-998d-47ce9f2cc047}" Required="FALSE" ResultType="Boolean" ReadOnly="TRUE" DisplayName="Completed" SourceID="http://schemas.microsoft.com/sharepoint/v3" StaticName="Checkmark" ColName="sql_variant1">
              <Formula>=PercentComplete&gt;=1</Formula>
              <FieldRefs>
                <FieldRef Name="PercentComplete" />
              </FieldRefs>
            </Field>
            <Field Type="Calculated" DisplayName="A-Z" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="Text" ReadOnly="TRUE" ID="{8f658a69-6f98-4711-81e5-1d8b3c70239e}" SourceID="{354c4d63-a6d5-41b7-b371-72068e7ebc99}" StaticName="A_x002d_Z" Name="A_x002d_Z" ColName="sql_variant1" RowOrdinal="0" Version="1">
              <Formula>=LEFT(Title,1)</Formula>
              <FieldRefs>
                <FieldRef Name="Title" />
              </FieldRefs>
            </Field>
 
           <Field Type="Calculated" DisplayName="Filed By" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="Text" Group="DH Columns" ID="{83bfcba5-de2d-4ee0-a241-2a2d63b3a6cf}" SourceID="{3622aa4b-4974-413e-9a7d-78b9904991d5}" StaticName="Filed_x0020_By" Name="Filed_x0020_By" Required="FALSE" ReadOnly="TRUE" Version="114" ColName="sql_variant2" RowOrdinal="0">
              <Formula>=_Author</Formula>
              <FieldRefs>
                <FieldRef Name="Author" ID="{1df5e554-ec7e-46a6-901d-d85a3881cb18}" />
              </FieldRefs>
              <FieldRefs>
                <FieldRef Name="_Author" />
              </FieldRefs>
            </Field>
            <Field Type="Calculated" DisplayName="Modified-Date" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="DateTime" ReadOnly="TRUE" Group="DH Columns" ID="{0d67b66e-43d1-415a-b814-830fd8257d8e}" SourceID="{3622aa4b-4974-413e-9a7d-78b9904991d5}" StaticName="Modified-Date" Name="Modified_x002d_Date" Required="FALSE" ColName="sql_variant3" RowOrdinal="0">
              <Formula>=Modified</Formula>
              <FieldRefs>
                <FieldRef Name="Modified" />
              </FieldRefs>
            </Field>
            <Field Type="Calculated" DisplayName="A-Z" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="Text" ReadOnly="TRUE" ID="{8f658a69-6f98-4711-81e5-1d8b3c70239e}" SourceID="{354c4d63-a6d5-41b7-b371-72068e7ebc99}" StaticName="A_x002d_Z" Name="A_x002d_Z" ColName="sql_variant1" RowOrdinal="0" Version="1">
              <Formula>=LEFT(Title,1)</Formula>
              <FieldRefs>
                <FieldRef Name="Title" />
              </FieldRefs>
            </Field>
 
            <Field Type="Calculated" DisplayName="Filed By" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="Text" Group="DH Columns" ID="{83bfcba5-de2d-4ee0-a241-2a2d63b3a6cf}" SourceID="{3622aa4b-4974-413e-9a7d-78b9904991d5}" StaticName="Filed_x0020_By" Name="Filed_x0020_By" Required="FALSE" ReadOnly="TRUE" Version="114" ColName="sql_variant2" RowOrdinal="0">
              <Formula>=_Author</Formula>
              <FieldRefs>
                <FieldRef Name="Author" ID="{1df5e554-ec7e-46a6-901d-d85a3881cb18}" />
              </FieldRefs>
              <FieldRefs>
                <FieldRef Name="_Author" />
              </FieldRefs>
            </Field>
            <Field Type="Calculated" DisplayName="Modified-Date" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="DateTime" ReadOnly="TRUE" Group="DH Columns" ID="{0d67b66e-43d1-415a-b814-830fd8257d8e}" SourceID="{3622aa4b-4974-413e-9a7d-78b9904991d5}" StaticName="Modified-Date" Name="Modified_x002d_Date" Required="FALSE" ColName="sql_variant3" RowOrdinal="0">
              <Formula>=Modified</Formula>
              <FieldRefs>
                <FieldRef Name="Modified" />
              </FieldRefs>
            </Field>
Regards

Nigel

**Comment by NPrice99** [comment]
I have tracked down the field causing the issue.  Its a custom field called "Filed-By" and it has a formula of  "=Author".  Normally the formula should be =[Author], but as soon as you hit "OK" it reverts back to "=Author".  Also an extra <FieldRef> has crept in called "_Author".  I don't know where this crept in from.

**Comment by NPrice99** [comment]
I clicked the wrong button ! - Hence the Re-Open.

**Comment by erwinvanhunen** [comment]
There is no reference to the _author field in your XML at all?

**Comment by NPrice99** [comment]
Yes there is, it is the internal name of the "Author" field and is a single line of text.  So Name = _Author and DisplayName=Author.  Also there is another field whose DisplayName="Filed By", which is a person field with an internal name of "Author", there is another field called "Filed By", which is the calculated file which references "Author" field.

**Comment by erwinvanhunen** [comment]
How has this site been created? E.g. how has the calculated Filed By column been created? The _author field refers to a SharePoint built-in field, _Author. Referencing that field through the UI doesn't work, but (haven't tested) through the API's it probably works, hence I'm wondering how it has been created.

**Comment by NPrice99** [comment]
The Site Template is "STS#0"

**Comment by NPrice99** [comment]
The Calculated Field "Filed By" was created using the UI using a formula of "=Author" Note no underline before Author.

**Comment by NPrice99** [comment]
There is another "Filed By" field which was renamed from the Author field =>. "Filed By" and is a "Person" field. The Field "Author" is a SIngle Line of Text created by the UI after the Author field was renamed to "Filed By"

**Comment by erwinvanhunen** [comment]
This is an interesting one. I will have to do some debugging here.

**Comment by NPrice99** [comment]
Do you need the XML Template ? it is 904KB

**Comment by erwinvanhunen** [comment]
No, not needed, I can actually reproduce it here.

**Comment by erwinvanhunen** [comment]
Okay, this one took a bit of testing, debugging etc.

I updated the engine, and created, through the UI, a site column, called Filed By. I made that one a calculated column and put [Author] in the formula.

Then I created a list, and added that site column to the list. SharePoint automatically added the Author field to it too.

Then I extracted a template with the latest build of the dev branch. The result of that is below (I removed irrevant artifacts):

```xml
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2015/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=1.3.615.0, Culture=neutral, PublicKeyToken=null" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-479855AF60B342B2AD02DC04E43C28C2">
    <pnp:ProvisioningTemplate ID="TEMPLATE-479855AF60B342B2AD02DC04E43C28C2" Version="1">
      <pnp:SiteFields>
        <Field Type="Calculated" DisplayName="Filed By" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="1033" ResultType="Text" ReadOnly="TRUE" Group="Custom Columns" ID="{9ad62185-4fb1-45fd-91eb-486bf6d753e3}" SourceID="{98c0c006-a6b4-496c-85d7-01727a3a6d27}" StaticName="Filed_x0020_By" Name="Filed_x0020_By">
          <Formula>=Author</Formula>
          <FieldRefs>
            <FieldRef Name="_Author" ID="{246d0907-637c-46b7-9aa0-0bb914daa832}" />
          </FieldRefs>
        </Field>
      </pnp:SiteFields>
      <pnp:Lists>
        <pnp:ListInstance Title="test" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/test" MinorVersionLimit="0" MaxVersionLimit="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" EnableFolderCreation="false">
          <pnp:FieldRefs>
            <pnp:FieldRef ID="246d0907-637c-46b7-9aa0-0bb914daa832" Name="_Author" DisplayName="Author" />
            <pnp:FieldRef ID="9ad62185-4fb1-45fd-91eb-486bf6d753e3" Name="Filed_x0020_By" DisplayName="Filed By" />
          </pnp:FieldRefs>
        </pnp:ListInstance>
      </pnp:Lists>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```

Then I created a new team site and applied the template to it, resulting in the site column to be created and the column to be added to the list without an error message.

It would be great if you could test it yourself with the dev branch.

**Comment by NPrice99** [comment]
Hi Erwin

Thanks for the prompt response.

I will test this afternoon and let you know the result.

Regards

Nigel

**Comment by NPrice99** [comment]
Hi Erwin

OfficeDev.Core.Tests does not compile with 49 errors – There is no constructor for….  Including ObjectComposedLook, ObjectField, ObjectFeatuires etc.

Regards

Nigel

**Comment by erwinvanhunen** [comment]
Good point. I will fix that tonight. For now just compile the core project on itself.




On Tue, Jun 2, 2015 at 9:40 AM -0700, "NPrice99" <notifications@github.com> wrote:
Hi Erwin

OfficeDev.Core.Tests does not compile with 49 errors – There is no constructor for….  Including ObjectComposedLook, ObjectField, ObjectFeatuires etc.

Regards

Nigel

**Comment by NPrice99** [comment]
Hi Erwin

It failed again :-


SharePoint Manager could only find two fields :-


Filed By


<Field Type="Calculated" DisplayName="Filed By" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="Text" Group="DH Columns" ID="{83bfcba5-de2d-4ee0-a241-2a2d63b3a6cf}" SourceID="{3622aa4b-4974-413e-9a7d-78b9904991d5}" StaticName="Filed_x0020_By" Name="Filed_x0020_By" Required="FALSE" ReadOnly="TRUE" Version="121"><Formula>=[Author]</Formula><FieldRefs><FieldRef Name="Author" ID="{1df5e554-ec7e-46a6-901d-d85a3881cb18}" /></FieldRefs></Field>



Author

<Field ID="{246D0907-637C-46b7-9AA0-0BB914DAA832}" Name="_Author" Group="Core Document Columns" Type="Text" DisplayName="Author" SourceID="http://schemas.microsoft.com/sharepoint/v3/fields" StaticName="_Author" Description="The primary author" Sealed="TRUE" AllowDeletion="TRUE" ShowInFileDlg="FALSE" />

In the list there are Three – the two above plus :-

Display Name = Filed By

Internal Name = Author

Type = Single Line of Text.

Which I assume is the OOTB Author Field.

My Template file is slightly different to yours:-

     <Field Type="Calculated" DisplayName="Filed By" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="2057" ResultType="Text" Group="DH Columns" ID="{83bfcba5-de2d-4ee0-a241-2a2d63b3a6cf}" SourceID="{3622aa4b-4974-413e-9a7d-78b9904991d5}" StaticName="Filed_x0020_By" Name="Filed_x0020_By" Required="FALSE" ReadOnly="TRUE" Version="121" ColName="sql_variant3" RowOrdinal="0">
              <Formula>=_Author</Formula>
              <FieldRefs>
                <FieldRef Name="Author" ID="{1df5e554-ec7e-46a6-901d-d85a3881cb18}" />
              </FieldRefs>
              <FieldRefs>
                <FieldRef Name="_Author" />
              </FieldRefs>
            </Field>

Ie I have both _Author and author as FileRefs compared with yours which only has _Author.

Regards

Nigel
________________________________

**Comment by erwinvanhunen** [comment]
Please get the latest dev build. Now you can compile the test project.

**Comment by NPrice99** [comment]
OK will do

**Comment by erwinvanhunen** [comment]
It's interesting that in your there are 2 separate fieldref collections for the field. That actually makes not much sense. We do not generate that XML, it's the server doing that, so I'm wondering how the Filed By field has been set up initially. Can you find the field xml of the Filed By sitecolumn and the _Author sitecolumn with SharePoint Manager and post it here?

**Comment by NPrice99** [comment]
Hi Erwin

I Sent them to you at 18:28 bst this afternoon.

Regards

Nigel

**Comment by erwinvanhunen** [comment]
Ah right (I don't follow this by email, but I use the github site). Okay, there I only see 1 fieldref in the field, while in the XML you posted about the template, the Filed By entry has 2 fieldrefs in there... That field XML you posted from your template, that was generated by the engine, correct? Was it a field element located in the SiteFields section or in the ListInstance section?

**Comment by NPrice99** [comment]
Hi Erwin

The Field XML with the two fieldrefs was generated by the engine.

I will check whether it’s in sitefields section or ListInstance section In about an hour before I download the latest version of the dev branch and recompile.

Regards

Nigel

**Comment by NPrice99** [comment]
Hi Erwin

It is the ListInstance section of the List “All Content”

Regards

Nigel

**Comment by NPrice99** [comment]
REcompiled OfficeDev.PnP and OfficeDev.PnP.Test - no errors. Thanks for fixing that.  Reran my Create-Template C# program still created the two entries in the List Instance again.  Reran the apply-Template C#  program and it still failed with the same error. (The formula refers to a column that does not exist.)

**Comment by erwinvanhunen** [comment]
what version of the schema are you using in your application? 201503 or 201505?

**Comment by NPrice99** [comment]
http://schemas.dev.office.com/PnP/2015/05/ProvisioningSchema

**Comment by NPrice99** [comment]
Generator=”OfficeDevPnP.Core, Version=1.3.615.0

**Comment by PaoloPia** [comment]
Well, I tested the same scenario. The export XML is good in my scenario. However, when I try to apply the template that I got from the source site template, I get the following error "The formula refers to a column that does not exist.  Check the formula for spelling mistakes or change the non-existing column to an existing column."

I'm trying to figure out the issue ...

**Comment by PaoloPia** [comment]
Ok! I think I found the issue. When we extract the Calculated Field definition, we get the SchemaXml of the field, which references the Author field in the formula using the InternalName (_Author). However, when we apply the template the _Author value is not valid. Hence, the "column does not exist" error. If we use the Author (Display Name) value it works. Now, the question is: should we fix the XML automatically generated by SharePoint? Or should we try to find another kind of solution?

**Comment by NPrice99** [comment]
Hi Paolo If this works OK with SharePoint OOTB and with SharePoint Manager 2013, either there is a fix in the SharePoint base code, or someone has amended the SharePoint base code to compensate for this error.  So is this a SharePoint bug ?  I don't know if Jeremy or Vesa has access to the SharePoint Bug database and can advise us? From my own personal point of view and the project I am on point of view, it would be quicker for the OfficeDev.PnP team to fix it rather than wait for the Microsoft Bug fixing juggernaut to fix it in 6 - 12 months time as I cannot move on generating a number of sites because this issue is preventing me from doing so. What other kind of solution did you have in mind ?

**Comment by NPrice99** [comment]
Are you saying that if I go through the Template finding where the formula is and changing _Author to Author it would all work or is there other things that would have to be changed before it worked ?

**Comment by NPrice99** [comment]
As this Template will be fairly static I am happy to do some Post Template build processing either programmatically (as I have done for Enterprise Keywords) or manually.

**Comment by NPrice99** [comment]
Bump ! - is there any news on a solution or workaround for this one ? Its starting to hold me up. Thanks

**Comment by YuriLeontyev** [comment]
Hi, I've tried to export my site and got the same issue. Is it still not fixed?

**Comment by YuriLeontyev** [comment]
> Bump ! - is there any news on a solution or workaround for this one ? Its starting to hold me up. Thanks

Hi, I've tried to export my site and got the same issue. Is it still not fixed?
