### ISSUE TITLE
Url Properties changed

### ISSUE THREAD

**Issue by braegelno5** [OfficeDev/PnP#867]
in STS0Template.xml the pnp:ListInstance Url property for every list has changed from Url="/.." to Url=".."

**Comment by erwinvanhunen** [comment]
The templates are based upon the new schema now, 201505, whereas they where based upon the old schema. Is this change breaking something for you?

**Comment by frankmarasco** [comment]
I should be good.

From: Erwin van Hunen
Reply-To: OfficeDev/PnP
Date: Monday, June 1, 2015 at 11:12 AM
To: OfficeDev/PnP
Subject: Re: [PnP] Url Properties changed (#867)


The templates are based upon the new schema now, 201505, whereas they where based upon the old schema. Is this change breaking something for you?

**Comment by braegelno5** [comment]
yes it breaks the list detection.. BaseTemplate to existing list
in STS0Template.xml the Url value is now Url="Shared Document" 
the real list has a Url="Shared Documents"

**Comment by erwinvanhunen** [comment]
That's correct. The templates are generated with site relative urls for the list, e.g. Url="Lists/test" for instance. The engine takes care of the correct Url for you.

**Comment by braegelno5** [comment]
it must be only a speller?
 https://[tenant].sharepoint.com/sites/130049/Shared%20Documents/
"Shared Documents" != "Shared Document"

i 'm able to change the code to check the url without the starting "/", but this speller?

**Comment by erwinvanhunen** [comment]
I updated that code today actually. Are you running the latest and greatest Dev branch?






On Mon, Jun 1, 2015 at 9:40 AM -0700, "Torsten Schuster" <notifications@github.com> wrote:
it must be only a speller?
 https://[tenant].sharepoint.com/sites/130049/Shared%20Documents/
"Shared Documents" != "Shared Document"

i 'm able to change the code to check the url without the starting "/", but this speller?


---

**Comment by braegelno5** [comment]
that's mysterious, now is standing Documents there with s, next debug running..
i will also check the last dev

**Comment by braegelno5** [comment]
ok with the last dev its working
