### ISSUE TITLE
Discussion board not supported in the provisioning enginge

### ISSUE THREAD

**Issue by blindboygrunt** [OfficeDev/PnP#881]
An error is thrown when using lists of the discussion board type in the provisioning engine. 
I guess that it has something to do with the complex structure of the discussion board list.

The error is:
 
Microsoft.SharePoint.Client.ServerException was unhandled
  HResult=-2146233088
  Message=Folders are not allowed for this list template.
  Source=Microsoft.SharePoint.Client.Runtime
  ServerErrorCode=-2146232832

**Comment by erwinvanhunen** [comment]
Please retrieve the latest dev branch, I just merged PR #882

**Comment by blindboygrunt** [comment]
Works like a charm, thanks for a quick solution!
