### ISSUE TITLE
JavaScript breadcrumb with user custom action

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP#889]
Common ask from the community: How to implement breadcrumb without custom master page.

Sample which shows how this can be done using JavaScript embed and user custom actions at site collection level, so that needed path is added to each page automatically.

**Comment by aaclage** [comment]
Working on that, should be included in the samples?

**Comment by VesaJuvonen** [comment]
Samples folder would be indeed d the right location, unless you are building this as more ready solution (Solutions folder). Scenarios are more for showing how Core component works. 

Looking forward on this. Thx André.

**Comment by aaclage** [comment]
understood.

**Comment by aaclage** [comment]
As follow up was created a pull request #925 call Core.GlobalBreadcrumbRibbon "Provision Global Breadcrumb & Ribbon in Site Collection"

**Comment by VesaJuvonen** [comment]
thx André. Will have a look and included that to library. Will let you know if there's anything to change.

**Comment by VesaJuvonen** [comment]
Looked through and implementation is solid for providing cross site collection navigation. With the breadcrumb we were however looking slightly different behavior in the embedded JavaScript. What I mean with that is that it should render the navigation node location in the site - so that it's truly dynamic and based on user location.

For example if you go to document library it would show Home - Library Name and if are in sub site of site collection it would show Home - Sub Site Name - Page/Library in the sub site. 

Your current implementation is great from deployment and management perspective (if all samples would be in this level), but the actual link resolving part is the one which should work like classic breadcrumb to fulfill the requirement.

We have few options with this one depending on your availability. #1 - you have time to adjust the logic to come up with the links and path #2 we get this in now as is and work in core team or with community to see if we can introduce the navigation node based logic.

I obviously should have been more precise with the initial ask-

**Comment by aaclage** [comment]
I had that and remade for what i have now....My understand was different from the initial requirement, i apologize for that. Please don't accept current version until the final logic is done.

**Comment by aaclage** [comment]
As talked in my last email, made the changes to reflect the SharePoint Folder Data. At this moment there is 3 features in the Sample, 2 Global Breadcrumb "SharePoint Data & JSON Data" and Global Ribbon in all Site Collection. You can validate the output of the sample. I am sorry for the other mistake.

**Comment by aaclage** [comment]
Topic can be close, correct?

**Comment by VesaJuvonen** [comment]
Good point. Closed this one. Thx for your assistance on this.
