### ISSUE TITLE
BrandingExtensions.SetDefaultPageLayoutForSite not working properly for subsites

### ISSUE THREAD

**Issue by robtor1** [OfficeDev/PnP#897]
I cant get SetDefaultPageLayoutForSite work for subsites.
My page layout is deployed to master page gallery/Company

This is the code im using

using (ClientContext clientContext = new AuthenticationManager().GetSettingsFileAuthenticatedContext(string.Format("{0}/Company", siteCollectionUrl)))
            {
                // Set default page layout
                var rootWeb = clientContext.Site.RootWeb;
                clientContext.Load(rootWeb, rw => rw.Url);
                clientContext.ExecuteQueryRetry();
                clientContext.Web.SetDefaultPageLayoutForSite(rootWeb, "Company/pre_WelcomePage.aspx");
                
            }

when i check the propertybag for __DefaultPageLayout on the subweb its empty

**Comment by VesaJuvonen** [comment]
Hi robtor1,
Sorry for massive delay on getting back to you. We are currently doing cleaning on the issues and hopefully you have been able to fix this issue already. There was originally some challenges with publishing sites in the PnP engine, but all of these should have been addressed already.

If this is still an issue, would suggest that it would be reported to PnP Core component repository at https://github.com/OfficeDev/PnP-Sites-Core.
