### ISSUE TITLE
DataRow provisioning of column URL

### ISSUE THREAD

**Issue by werocool** [OfficeDev/PnP#907]
When you provision a list with datarows that contain a field of type URL, the synthax URL,Description is not handled. See xml, example.

![xml](https://cloud.githubusercontent.com/assets/4926713/8068231/9b0d9a8e-0ec0-11e5-9138-dc3f1e5579fe.png)

**Comment by NPrice99** [comment]
I have also hit this problem.

**Comment by PaoloPia** [comment]
Yes, Thanks Nigel. I'm working on it.

**Comment by NPrice99** [comment]
Thanks Paolo – I dont know how you are ranking bugs and if you need to know if other people are hitting the same issues.  I wasn’t hassling Honest !

**Comment by PaoloPia** [comment]
No worries ... your comment was more than welcome, thanks for your great feedbacks and real-life testing! We really appreciate it.

**Comment by braegelno5** [comment]
the correct syntax here should be: 
<pnp:DataValue FieldName="url">URL, Description</pnp:DataValue>
checked, it works here like on the past server side code (space after comma)
if you only put the URL it will also added to the Description

**Comment by PaoloPia** [comment]
This one has been completed and available in dev branch. Please test it. Any feedbacks are more than welcome! Thanks.

**Comment by NPrice99** [comment]
It works for me.
