### ISSUE TITLE
Remove requirement for SiteFields in template to process LookupFields

### ISSUE THREAD

**Issue by pkskelly** [OfficeDev/PnP#913]
Scenario: when provisioning a site collection, we *should* provision site columns and content types to the root web. When a subsite is provisioned, we provision lists, contenttype bindings and set lookups for subsite level lists that use the site columsn / ctypes.
QUES: Why is at least one SiteField element required to enable processing of the lookup fields for a subsite? 

To get this scenario to work, I MUST include at least one SiteField element in the provisioning template for the subsite since (using the June 2015 release) the WillProvision() method of ObjectLookupFields class will only resolve the lookup field list id's for the subsite if the provisioning template has at least 1 SiteField (which BTW, will cause processing even if the SiteField is not a Lookup field). Requireing a subsite template to contain a SiteField to resolve lookups seems like a defect to me.

Is this desired behavior? If not, then I can log a UserVoice or GitHub issue to request a fix. A proposed fix might also be an extension method and change to the WillProvision() like so:

public override bool WillProvision(Web web, ProvisioningTemplate template)
{
if (!_willProvision.HasValue)
{
//_willProvision = template.SiteFields.Any();
_willProvision = template.SiteFields.Any() || template.Lists.Any(x => x.Fields.Any(f => f.SchemaXml.ContainsAttribute("List")));
}
return _willProvision.Value;
}

...and the extenion method

public static class StringExtensions
{
public static bool ContainsAttribute(this string schemaXml, string attrName)
{
XElement fieldElement = XElement.Parse(schemaXml);
var containsElement = (fieldElement.Attribute(attrName) != null);
return containsElement;
}
}

**Comment by jansenbe** [comment]
Closing this one, fixed by @erwinvanhunen
