### ISSUE TITLE
JSLink on Calendar list not rendering client side

### ISSUE THREAD

**Issue by werocool** [OfficeDev/PnP#922]
If you provision a Custom List and a Calendar list and add a simple test.js (with an alert) to a given web.

You then use OfficeDevPNP List Extension method "SetJSLinkCustomizations" to insert custom JS to page DispForm, EditForm and NewForm. This adds a javascript on the load of the webpart (form) via setting the property of the JSLink on the webpart (ListFormWebPart)

This works fine for the custom list but not the calendar. The JSLink is set but not rendered on the page load.

Sharepoint 2013 documentation state that this option is available:
https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.webpartpages.listformwebpart.jslink.aspx

The webpartpages could be set to RenderServer="True" and ClientSide="False"

**Comment by braegelno5** [comment]
In calendar lists this is also not working if you do all over the ui

**Comment by werocool** [comment]
Here is a "workaround" that I use for one of my clients. This will render a Javascript on all pages for a given Calendar List. I do not this is a good pull request.

 	/// <summary>
        /// Calendar issue 
        /// </summary>
        /// <param name="list"></param>
        /// <param name="pageType"></param>
        /// <param name="jslink"></param>
        public static void AddJSLinkWP(List list, PageType pageType, string jslink)
        {
            // Get the list form to apply the JS link
            Form listForm = list.Forms.GetByPageType(pageType);
            list.Context.Load(listForm, nf => nf.ServerRelativeUrl);
            list.Context.ExecuteQueryRetry();

            var file = list.ParentWeb.GetFileByServerRelativeUrl(listForm.ServerRelativeUrl);
            var wpm = file.GetLimitedWebPartManager(PersonalizationScope.Shared);
            list.Context.Load(wpm.WebParts, wps => wps.Include(wp => wp.WebPart.Title));
            list.Context.ExecuteQueryRetry();

            bool alreadyOverwritten = false;
            foreach (var webpart in wpm.WebParts)
            {
                if (webpart.WebPart.Title.Equals("JsLink"))
                {
                    alreadyOverwritten = true; 
                }
            }

            if (!alreadyOverwritten)
            {
                var oWebPartDefinition = wpm.ImportWebPart(GetScriptEditorWebPart(jslink));
                wpm.AddWebPart(oWebPartDefinition.WebPart, "Main", 0);
                list.Context.ExecuteQueryRetry();
            }

        }

        private static string GetScriptEditorWebPart(string jsLink)
        {
            return "<webParts>" +
                    "<webPart xmlns=\"http://schemas.microsoft.com/WebPart/v3\">" +
                    "<metaData>" +
                        "<type name=\"Microsoft.SharePoint.WebPartPages.ScriptEditorWebPart, Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c\" />" +
                        "<importErrorMessage>Impossible d’importer ce composant WebPart.</importErrorMessage>" +
                    "</metaData>" +
                    "<data>" +
                        "<properties>" +
                            "<property name=\"ExportMode\" type=\"exportmode\">None</property>" +
                            "<property name=\"HelpUrl\" type=\"string\" />" +
                            "<property name=\"Hidden\" type=\"bool\">False</property>" +
                            "<property name=\"Description\" type=\"string\">Permet aux auteurs d'insérer des extraits ou des scripts HTML.</property>" +
                            "<property name=\"Content\" type=\"string\">&lt;script type='text/javascript' src='" + jsLink + "'&gt;&lt;/script&gt;</property>" +
                            "<property name=\"CatalogIconImageUrl\" type=\"string\" />" +
                            "<property name=\"Title\" type=\"string\">JsLink</property>" +
                            "<property name=\"AllowHide\" type=\"bool\" > False</property>" +
                            "<property name=\"AllowMinimize\" type=\"bool\" > False</property>" +
                            "<property name=\"AllowZoneChange\" type=\"bool\" > False</property>" +
                            "<property name=\"TitleUrl\" type=\"string\" />" +
                            "<property name=\"ChromeType\" type=\"chrometype\" > None</property>" +
                            "<property name=\"AllowConnect\" type=\"bool\" > False</property>" +
                            "<property name=\"Width\" type=\"unit\" />" +
                            "<property name=\"Height\" type=\"unit\" />" +
                            "<property name=\"HelpMode\" type=\"helpmode\" > Navigate</property>" +
                            "<property name=\"AllowEdit\" type=\"bool\" > True</property>" +
                            "<property name=\"TitleIconImageUrl\" type=\"string\" />" +
                            "<property name=\"Direction\" type=\"direction\" > NotSet</property>" +
                            "<property name=\"AllowClose\" type=\"bool\" > True</property>" +
                            "<property name=\"ChromeState\" type=\"chromestate\" > Normal</property>" +
                      "</properties>" +
                    "</data>" +
                "</webPart>" +
            "</webParts>";
        }



        /// <summary>
        /// This method change the JS link of all type of form of a given list 
        /// </summary>
        /// <param name="list">The list</param>
        /// <param name="jsSuffix">The Javascript prefix (name of the list)</param>
        /// <param name="context">The client to execute the command</param>
        public static void SetJsWpLinkForForms(List list, string jsSuffix, ClientContext context)
        {
            //Display Form
            AddJSLinkWP(list,PageType.DisplayForm, list.ParentWebUrl + "/SiteAssets/" + jsSuffix + ".Display.js");
            context.ExecuteQuery(); //Execute Update

            //Edit Form
            AddJSLinkWP(list,PageType.EditForm, list.ParentWebUrl + "/SiteAssets/" + jsSuffix + ".Edit.js");
            context.ExecuteQuery(); //Execute Update

            //New Form
            AddJSLinkWP(list,PageType.NewForm, list.ParentWebUrl + "/SiteAssets/" + jsSuffix + ".New.js");
            context.ExecuteQuery(); //Execute Update
        }
