### ISSUE TITLE
Get-SPOProvisioningTemplate fails "Themeinfo-....." is invalid

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP#926]
![invalid-theme](https://cloud.githubusercontent.com/assets/8484048/8126513/13053196-10e7-11e5-81cb-52c921841185.png)
The theme is the default theme.  The site template is BLANKINTERNET#0.  The site has its own css file which change the colours of some of the items.
If I run the Get-SPOProvisioningTemplate from a C# program it works, but no signs  of any theme information.

**Comment by NPrice99** [comment]
A bit more information.  If I run the Get-SPOProvisioningTemplate twice in succession then I get this error on the second command.  If I execute a different command in between two Get-SPOProvisioningTemplate commands, then I don't get the error.  SO sounds like an uninitialized variable, which is taking its value from the previous run.

**Comment by VesaJuvonen** [comment]
We have been working on the updated theme handling for the engine few times and this should be now solid based on the community discussions also in Yammer. If this is not the case, just let us know and we'll have a look on this again. Thx for submitting and sorry for the way too long lead times on getting response on this submission.
