### ISSUE TITLE
Issue in OD4B.NavLinksInjection

### ISSUE THREAD

**Issue by TridentSharePoint** [OfficeDev/PnP#932]
https://github.com/OfficeDev/PnP/tree/master/Samples/OD4B.NavLinksInjection
When we deploy this script it create navigation however from Site Collection term store management if we change something and click save button. /_layouts/15/termstoremanager.aspx

page become blank and goes to infinite loop. it says SP is undefined etc. etc.

**Comment by patrick-rodgers** [comment]
Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.
