### ISSUE TITLE
Master Page not applied in Provisioning.Framework.Console

### ISSUE THREAD

**Issue by garima2510** [OfficeDev/PnP#936]
I am using Console framework for provisioning the sub-sites. When I created the template, I got correct link to the custom master page in ComposedLook section. But when I apply this template, master page is not set. 

I have tried two versions of this:
`<pnp:ComposedLook Name="Office" ColorFile="" FontFile="" BackgroundFile="" MasterPage="{sitecollection}/_catalogs/MasterPage/Custom.master" SiteLogo="/Style Library/Theme/Images/main_logo.png" AlternateCSS="" Version="0" />`

`<pnp:ComposedLook Name="Office" ColorFile="" FontFile="" BackgroundFile="" MasterPage="{masterpagecatalog}/Custom.master" SiteLogo="/Style Library/Theme/Images/main_logo.png" AlternateCSS="" Version="0" />`

**Comment by erwinvanhunen** [comment]
In the target site, is the master page available? If not, did you, when extracting the template tell the engine to persist the composed look files?

**Comment by garima2510** [comment]
Yes, it is available in target site as well as I set the PersistComposedLook to true. After the template is applied, I have to navigate to web's master page settings and manually set the custom master page. The icon setting is intact though.

**Comment by garima2510** [comment]
One more thing, I noticed that persist composed look files do not download the master page like other artifacts (spcolor, site logo and all). So I have to have the master page in the target site for this to work.

**Comment by patrick-rodgers** [comment]
@erwinvanhunen , can we just close this, I believe this is working now?

**Comment by VesaJuvonen** [comment]
We have done significant updates on the master page and branding handling in the engine, so this should absolutely work in on-premises and in SharePoint online based on the unit tests. Based on this, will close the issue. thx for reporting.
