### ISSUE TITLE
Error adding a Web Part to HOME.ASPX in a team site.

### ISSUE THREAD

**Issue by pstork** [OfficeDev/PnP#948]
When provisioning the default page in a team site the AddWebPartToWikiPage method fails because the default value for the WikiField contains <BR> HTML tags.  Since the method uses an XML parser it fails when parsing the <BR> tags because they are not self closing.  The example in the PNP uses a custom page with custom layout that does not include <BR> tags.

**Comment by jansenbe** [comment]
This has been recently fixed in the dev branch. Can you try using our dev branch code and see if the problem still exists. If not then please close this issue
