### ISSUE TITLE
MSDN reference [Download the package] redirect to page 404

### ISSUE THREAD

**Issue by dimitardanailov** [OfficeDev/PnP#949]
When I try to access [Download the package](http://www.microsoft.com/downloads/details.aspx?FamilyID=2c8011b0-441a-4bab-bf19-6b1009c7d8dd), I receive this message: **We are sorry, the page you requested cannot be found.**

Location at "Download the package" link: Welcome to the Office 365 Developer Patterns and Practices](https://github.com/OfficeDev/PnP/wiki)

**Comment by VesaJuvonen** [comment]
Sorry for that dead link. We have moved all the guidance from Microsoft download to MSDN. You can find the official MSDN guidance based on PnP program from following location: http://aka.ms/OfficeDevPnPMSDN
