### ISSUE TITLE
Template applying for console application gives exception.

### ISSUE THREAD

**Issue by MaikvanderGaag** [OfficeDev/PnP#952]
When applying a template that was generated with the last version of PNP it throws the below exception

Additional information: A duplicate field name "n40d8967e6974fe689454c82dc9979eb" was found.

Investigation tells me this is regarding taxonomy fields. If the template is needed for fixing the problem please let me know as it has customer specific information and do not want to share it in general.

**Comment by erwinvanhunen** [comment]
Maik, are you running this against an on-premises environment? As I can't reproduce it against SPOnline. The issue that shows up here too (Issue #969) shows against on-premises too.

**Comment by MaikvanderGaag** [comment]
Hi Erwin,

No it is against online.

Sent from my Windows Phone
________________________________
