### ISSUE TITLE
Groups missing in People Picker

### ISSUE THREAD

**Issue by krusk** [OfficeDev/PnP#957]
Hi all,
I am using the client side People Picker, but it doesn't seem to detect/resolve SharePoint groups, only individuals. Is this correct? What am I missing?
K.

**Comment by jansenbe** [comment]
This is possible: see the PrincipalType: https://github.com/OfficeDev/PnP/tree/master/Components/Core.PeoplePicker#principaltype. Should give you what you need. I'm closing the issue now, but feel absolutely free to re-open in case this is not solving your problem

**Comment by krusk** [comment]
Ah! It must be something in the directive I am using. I will dig deeper into that: https://github.com/jasonvenema/sharepoint-angular-peoplepicker

Thank you.

**Comment by jansenbe** [comment]
Feel free to reference your angular version in our PeoplePicker docs...makes it easier to discover. If you wish we can even completely host this in PnP...
