### ISSUE TITLE
Set default value of People Picker

### ISSUE THREAD

**Issue by krusk** [OfficeDev/PnP#959]
Hi all,
I need to set the default value of the People Picker field to a user. What should be used as the value/how would I set the value of the field? I tried using the login name, but it didn't work for me (ex. i:0#.f|membership|krusk@yourcompany.com).
Thanks,
K.

**Comment by jansenbe** [comment]
See https://github.com/OfficeDev/PnP/blob/master/Components/Core.PeoplePicker/Core.PeoplePickerWeb/Pages/Default.aspx.cs#L68 for the code in the PeoplePicker control sample that shows how this needs to be done

**Comment by krusk** [comment]
It appears that it requires all three values of title, email, and login to function. Is that accurate?

**Comment by jansenbe** [comment]
Title and login are certainly needed, think you can omit email address (not tested that)

**Comment by krusk** [comment]
Thanks, I have been trying that using JavaScript (Angular actually) as follows, but it doesn't seem to be taking it. Is there something I am missing to implement this via JavaScript?

    $scope.vm.cc = {
                Email: 'krusk@yourcompany.com',
                Login: 'i:0#.f|membership|krusk@yourcompany.com',
                Name: 'Rusk, K'
        }

**Comment by jansenbe** [comment]
Hmm…The implementation we have serializes the information into a JSON string which is then stored in a hidden control. When the control loads if checks for the content of that hidden control, deserializes the JSON and displays the default value




Best Regards,

Bert Jansen | Service Engineer | Office 365 SharePoint and OneDrive service engineering
Ready to use Office 365 add-in Patterns and Practices from http://aka.ms/officedevpnp

**Comment by krusk** [comment]
Thanks for the information Bert. You have been extremely helpful. Any clues on how I would hit this via JavaScript?

**Comment by BrianMichely** [comment]
Do you have an angular controller that initializes the javascript peoplepicker? Is your $scope.vm.cc being initialized there, or in a different controller? Finally, which controller are you binding ng-controller to?

**Comment by krusk** [comment]
Hi Brian,
I am using the following directive:https://github.com/jasonvenema/sharepoint-angular-peoplepicker
It looks like this in HTML:

    <sp-people-picker name="CC" id="CC" ng-model="vm.cc" min-entries="1" max-entries="20" allow-duplicates="false" show-login="false" show-title="true" min-characters="2" app-web-url="$scope.spAppWebUrl" />

I have a controller for updating where I attempt to set the value via the following. This controller is tied to the update page:

     $scope.vm.cc = {
                    Email: userInfo.Email,
                    Login: userInfo.LoginName,
                    Name: userInfo.Title
                }

Thanks,
K.

**Comment by BrianMichely** [comment]
Hmm. So think i tried the approach you mentioned and had the same problem but I would have to go look at the directive code again. I ended up going a different route with a peoplepicker controller, initializing the picker and from javascript I found I had to do this to get the picker set: Note that this was not for setting default, but wondering if you need to do the first piece below..When I get a little time, I will go look at the approach you are taking with the directive to see if anything pops out

//from Javascript
angular.element($("#divFieldOwners")).scope().updateSecondaryOwners(this._ResolvedUsers);

//Angular peoplepicker controller method
$scope.updateSecondaryOwners = function (data) {
            $scope.siteConfiguration.secondaryOwners = data;
        }

// PeoplePicker in html - binding to the peoplepicker controller
![picker](https://cloud.githubusercontent.com/assets/8309449/8234632/161cf4c2-15ab-11e5-8623-4f05a926bf9b.jpg)

**Comment by krusk** [comment]
Thanks Brian. I will give this a deeper look. It is more about reading the values that are stored in the database and showing them in an update form. 
In your method for the controller, where is data coming from/what is being passed in?

**Comment by BrianMichely** [comment]
The controller method gets its data from the javascript picker class via this:
angular.element($("#divFieldOwners")).scope().updateSecondaryOwners(this._ResolvedUsers);

The method updates the scope and the html is bound to the controller

I had a difficult time getting the picker js to play well with the angular scope. I will load up the sample you referenced and see if I can get it to work as well.

**Comment by krusk** [comment]
Awesome! Thanks Brian.

**Comment by BrianMichely** [comment]
Sure. No problem. Give me a little bit to get it setup and test in between some other current activities

**Comment by BrianMichely** [comment]
Ok, so, I used the directive you mentioned, and used the scenario of setting a default user and getting it to render in the picker. Here is what I did:
Added the picker into my view: (also added a PlaceHolder attribute)
![picker2](https://cloud.githubusercontent.com/assets/8309449/8254542/6638dc98-1667-11e5-800d-0b394ef01d02.jpg)

Then added this in the PeoplePicker.prototype.Initialize function:
// Can be set from another methods such as a method that makes a rest call to get current user
var email = "brian@michely.onmicrosoft.com";
var login = "i:0#.f|membership|brian@michely.onmicrosoft.com";
var name = "Brian Michely";

var user = new Object();
user.Login = login;
user.Name = name;
user.Email = email;                
this.PushResolvedUser(this.ResolvedUser(user.Login, user.Name, user.Email));
                
// This gets the value back into the angular scope object
// The function is defined in the directive class controller
angular.element($("#divPeoplePick")).scope().updateDefaultOwner(user.Email);

Then added this function defined in directive controller class
$scope.updateDefaultOwner = function (data) {
        $scope.defaultOwner = data;
}

End result - defaulted resolved user displayed in picker:
![defaultedpicker](https://cloud.githubusercontent.com/assets/8309449/8254738/dd10be70-1668-11e5-81a8-e4eb4278ccea.jpg)

**Comment by krusk** [comment]
That is a thing of beauty. I will need to play around with how to make it dynamic (aka, I am pulling the users stored once an item is created, so I will need to pass the variables in). Any ideas how I can do this within a controller instead of touching the directive script?

**Comment by BrianMichely** [comment]
No ideas at this time struggling with the same idea..

**Comment by krusk** [comment]
Thanks Brian. Maybe we will get it figured out together

**Comment by BrianMichely** [comment]
I know I can call out to a service or factory to get user data, but don't see how to do it without touching the directive class yet. I will look at it more over the weekend. my email is brianmic@microsoft.com if you want to ping me if you find something out

**Comment by krusk** [comment]
Hi Brian, I was able to get the same behavior as your example. The large challenge of using it within the directive is that I need to get my values for use in an update form that is unique per item being updated, and this would require retrieving the route parameter somehow. My current workaround is to use the people picker to retrieve values and then push these into a separate array via an "Add" button that can be updated via REST values.

**Comment by krusk** [comment]
Wow!  I just found a hook that should resolve this issue. Using the directive mentioned in my original post (https://github.com/jasonvenema/sharepoint-angular-peoplepicker) I was able to update the field values by calling this method:

    peoplePicker.RecipientSelected("i:0#.f|membership|myname@email.org", "Smith, Bob M", "bsmith@email.org");

You can also remove selected users in the field via:

    peoplePicker.DeleteProcessedUser('i:0#.f|membership|myname@email.org);

With this in play, you can easily envision using a service to retrieve users by ID, get their LoginName, Title, Email) and pass these in a loop to populate the field on load.
