### ISSUE TITLE
Enable-SPOFeature Can only be used on the Web you connect to

### ISSUE THREAD

**Issue by martinlingstuyl** [OfficeDev/PnP#962]
Hi,

Currently I cannot add for example a subweb as a parameter to the Enable-SPOFeature method.
This means, that if I iterate through a list of subwebs to enable a feature on all of them, I have to Re connect with Connect-SPOnline at every iteration.

The strange thing is: Get-SPOFeature DOES have a -Web Property.

Martin

**Comment by erwinvanhunen** [comment]
I'll check it out.

**Comment by erwinvanhunen** [comment]
I fixed this in PR #972 and it is available in the dev branch now. I will close this issue.
