### ISSUE TITLE
Add-SPOFieldFromXml 

### ISSUE THREAD

**Issue by etiennebailly** [OfficeDev/PnP#968]
Hello, i'm not sure but i think there is maybe a problem with Add-SPOFieldFromXml cmdlet: bellow my code : 

	$originField = "<Field Type='Choice' DisplayName='MyChoice' StaticName='MyChoice' Name='MyChoice'>" `
						+ "<Default>Best</Default>" `
						+ "<CHOICES>" `
							+ "<CHOICE>Good</CHOICE>" `
							+ "<CHOICE>Best</CHOICE>" `
							+ "<CHOICE>Awesome</CHOICE>" `
						+ "</CHOICES>" `
				+ "</Field>"		
	
Connect-SPOnline –Url "http:......" -Credentials $credentials	
Add-SPOFieldFromXml -List "Documents" -FieldXml $originField

I got a NullReferenceException :
 Add-SPOFieldFromXml : La référence d'objet n'est pas définie à une instance d'un objet.
Au caractère Ligne:1 : 1
+ Add-SPOFieldFromXml -List "Documents" -FieldXml $originField
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-SPOFieldFromXml], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.AddFieldFromXml

But i thiink my XML is good because with standard CSOM it worked  
$list.Fields.AddFieldAsXml($originField,$true,[Microsoft.SharePoint.Client.AddFieldOptions]::AddFieldToDefaultView)
	$list.Update()
	$ctx.ExecuteQuery()

**Comment by etiennebailly** [comment]
Just a little thing, i didn't used  Add-SPOField  because it does not propose a "Default Value" parameter that i needed here

**Comment by erwinvanhunen** [comment]
The error is because you don't specify an ID attribute in the XML while the method expects that property in order to log the action. I fixed that issue in the core library, see PR #973.

**Comment by etiennebailly** [comment]
Excellent :-),:-) thank you
________________________________
De : Erwin van Hunen<mailto:notifications@github.com>
Envoyé : ‎22/‎06/‎2015 21:26
À : OfficeDev/PnP<mailto:PnP@noreply.github.com>
Cc : Etienne Bailly<mailto:etienne.bailly@istep.fr>
Objet : Re: [PnP] Add-SPOFieldFromXml  (#968)


The error is because you don't specify an ID attribute in the XML while the method expects that property in order to log the action. I fixed that issue in the core library, see PR #973<https://github.com/OfficeDev/PnP/pull/973>.

**Comment by pierrecoach** [comment]
While using Add-SpoFieldFromXml, with an xml comment in the xml, I got the xml comment taken as choice
![image](https://cloud.githubusercontent.com/assets/5269604/9088758/021d98ca-3b92-11e5-84f4-a511bbde8567.png)

**Comment by erwinvanhunen** [comment]
The Add-SPOFieldFromXML uses the core CreateField(string) method. That method as a result calls the AddFieldAsXml CSOM SDK method. Basically we're taking the XML as is and send it off to the server to process. We have no control over the implementation of that method unfortunately.
