### ISSUE TITLE
When Creating a Taxonomy field from a Template get "Field Already Exists" on the Note Field

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP#969]
When you create a Template via Get-SPOProvisioningTemplate and it includes taxonomy fields. When you apply that template to provision the site with Site Columns, then you get an error "Field Already Exists". Because when creating the Taxonomy field, the Note field is also created.  So when the provisioning engine hits the Note Field in the Template, and tries to create that we get a "Field already exists" error.

**Comment by erwinvanhunen** [comment]
This seems to be a duplicate to issue #952. I will close this issue and refer to issue 952 for further communication.
