### ISSUE TITLE
Exporting and Importing Search Configuration

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP#986]
can I make a suggestion that there should be a SPO powershell command for Exporting and Importing Search configurations, including Mapped properties, and it should work like the rest of PnP ie incrementally. It should be part of the provisioning engine.

**Comment by iddycol** [comment]
I think this would be really useful. Within provisioning it would be nice to specify custom result sources and other search configurations and have their corresponding XML generated. Also, when provisioning a field as a site column we would want to specify a mapping to a refinable property in some scenarios.

**Comment by patrick-rodgers** [comment]
Closing this issue due to age. If you believe this is still an issue in the latest release please re-open and let us know.
