### ISSUE TITLE
Setting the Document Template attribuite of a list causes an "Invalid Template" error

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP#988]
I have found the cause of the Invalid Template Url - in the Provisioning template, the list on which it failed on was the only one which had DocumentTemplate="{site}/SiteAssets/Forms/template.doc". I set this to DocumentTemplate="" and the problem went away.

**Comment by JBoman32768** [comment]
I can reproduce this problem also - why is this closed?
